### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by robsalasco** [tanujnotes/Olauncher#1]
Hi! 

Great work! I really love your app! Would be nice to have it too in F-Droid repository.

Thank you!

**Comment by tanujnotes** [comment]
Absolutely. Olauncher will be available on F-Droid soon.

**Comment by tanujnotes** [comment]
I submitted Olauncher to F-Droid and merge request got approved but the app is still not available. There is some failed pipeline; I don't know what it is and what to do about it. Any help by anyone will be highly appreciated. Thank you.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7364

**Comment by Bubu** [comment]
It's available now: https://f-droid.org/en/packages/app.olauncher/

One thing I missed before merging: The app doesn't include a fallback png icon that f-droid could automatically extract, so you'll need to add an icon explicitly to your repo for f-droid to use. We just rewrote the page on how to do this: https://staging.f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by tanujnotes** [comment]
@Bubu Thank you very much. I'll update the metadata.

**Comment by Bubu** [comment]
On September 12, 2020 7:57:51 AM GMT+02:00, "Tanuj M." <notifications@github.com> wrote:
>Closed #1.
>

To clarify: this will only show up with a new release.
