### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by andinus** [tanujnotes/Olauncher#10]
Version: 0.5

Searching for "ff" currently doesn't list "Firefox" or "Firefox Klar". I know this was requested in https://github.com/tanujnotes/Olauncher/issues/9 point 5, I agree that searching for "ff" should prioritize "FFUpdater".

Maybe add an option for fuzzy searching or just de-prioritize fuzzy matches?

**Comment by tanujnotes** [comment]
Made some improvements in app search in latest update (v1.0). It's not exactly what you want but I'm satisfied with and it should be good enough for most people. Closing this issue for now.
