### ISSUE TITLE
Tap to lock and biometric authentication/smart-lock

### ISSUE THREAD

**Issue by Pontohi** [tanujnotes/Olauncher#100]
Seems to be an issue where if you opt to use the double-tap to lock, your phone will no longer be unlockable via fingerprints or smart lock due to security policy. This forces you to input your password or pattern on unlock instead. Locking via power button does not have this effect.

Device: Galaxy S10

Model: SM-G973U1

Android version: 10

Android security patch level: August 1'st, 2020

Olauncher version: 3.3

**Comment by tanujnotes** [comment]
Is anyone else able to replicate this issue? Ideally this should not happen since we're now using Accessibility service for locking the device.

**Comment by brnwlshubh** [comment]
> Is anyone else able to replicate this issue? Ideally this should not happen since we're now using Accessibility service for locking the device.

I'm also experiencing the same issue.

**Comment by Pontohi** [comment]
Update: I am a bit of a dumbass and didn't update my phone for a year or two. To anyone experiencing this issue you might want to consider checking for software updates. Leaving it open for the other guy, but y'all can close it up if you think it's resolved
