### ISSUE TITLE
[feature request] Disable gestures

### ISSUE THREAD

**Issue by Donkey-Doug** [tanujnotes/Olauncher#104]
Make it possible to disable gestures.

**Comment by tanujnotes** [comment]
Disable which gesture?

**Comment by yayayeet69** [comment]
I believe @Donkey-Doug means being able to choose to have no app open for the "swipe left" and "swipe right" gestures

<img width="540" alt="Screenshot_20210912-153500" src="https://user-images.githubusercontent.com/90543997/132973687-00133257-45e6-4f56-a874-ee54db6e7ca1.png">

**Comment by tanujnotes** [comment]
If you long press app names next to Swipe left/right app, you can disable them.

**Comment by yayayeet69** [comment]
Thank you for such a quick response! I'll definitely try swiping or long pressing first if I have another question.

**Comment by tanujnotes** [comment]
Check out the About page in settings for all the hidden features. I'll try to make this more obvious in future updates.

**Comment by JacksonCampbell99** [comment]
Don't make anything more obvious on the settings interface, but inform to look in the about page some other way. I love how you thought of everything and how it's hidden and so simple, making for really simple settings with powerful options built in.
