### ISSUE TITLE
[feature request] Show recent apps on homescreen

### ISSUE THREAD

**Issue by Donkey-Doug** [tanujnotes/Olauncher#109]
Make it possible to show the most recently used apps on the homescreen instead of pre-selecting a number of apps.

Together with issues https://github.com/tanujnotes/Olauncher/issues/101 and https://github.com/tanujnotes/Olauncher/issues/108 this implies that all apps everywhere can be sorted by recently used and going to the app list shows apps not already on the homescreen.

**Comment by tanujnotes** [comment]
No.
