### ISSUE TITLE
[feature request] Allow tapping next to name

### ISSUE THREAD

**Issue by Donkey-Doug** [tanujnotes/Olauncher#110]
Make it possible to launch an app from the home screen by pressing next to its name, just like the app list.

Example:

https://user-images.githubusercontent.com/50382414/125541022-95397532-b3e1-42e5-84dc-27ce5ce8433b.mp4

**Comment by Donkey-Doug** [comment]
Already found this discussion under closed. However, I still believe this could be implemented.

**Comment by JacksonCampbell99** [comment]
I would not be happy with this on my home screen. I am fine with it in the app list.
