### ISSUE TITLE
[Feature Request] On/Off Switch for landscape mode

### ISSUE THREAD

**Issue by Askiatr** [tanujnotes/Olauncher#113]
Dear Tanuj,

Thank you for your awesome creation! I have been using your launcher for two weeks and I noticed that in the landscape mode apps are shown over the clock. Because Auto landscape in my phone is always on, I sometimes run into that bug. Please fix it!

![Screenshot_20210720-132607_Olauncher.jpg](https://user-images.githubusercontent.com/87694406/126294456-4c8af2a5-440e-487f-a633-f49c2e2bb60d.jpg)

**Comment by tanujnotes** [comment]
Are you using Android 8?

**Comment by Askiatr** [comment]
Yes, I do

**Comment by tanujnotes** [comment]
This is Android 8 specific problem. In Android 8, due to some bug, apps running full screen cannot be locked into portrait. Other versions won't face this issue. Closing the issue for now. If someone sends a pull request with a fix, I'll add it.
