### ISSUE TITLE
[Bug] Changing display size doesn't effect clock and date

### ISSUE THREAD

**Issue by jacksongoode** [tanujnotes/Olauncher#114]
It does change the size of the labels but it makes the clock noticeably smaller when increasing the display scale.

**Comment by tanujnotes** [comment]
Android version??

**Comment by jacksongoode** [comment]
Actually, I was testing this and realized it does seem to change. It just might look like the fonts are slightly larger than the clock. Perhaps increase the size of the clock and date widget? I will close this issue now.
