### ISSUE TITLE
[Feature request] Set font color from palette and background color or image arbitrarily

### ISSUE THREAD

**Issue by jlemonde** [tanujnotes/Olauncher#118]
It would be nice if one could set colors from a palette. I notice two things: first, when certain images are in background, the white text is barely readable so changing the color could help; second, once I switched to a plain black background, I was unable to set background images again. BTW: can you set arbitrary images? I wasn't able to. 

What I personally want is to have a plain marine blue background with some blue or greenish text, or a background image I can choose.

Thank you for your work overall!!! This is by far the launcher that suits my needs the best, and I have become less of an addict thanks to it! 😊

**Comment by tanujnotes** [comment]
Currently there's no plan to add such feature. And yes, you can set any wallpaper you want from your phone settings or using a wallpaper app.
