### ISSUE TITLE
Allow changing app names

### ISSUE THREAD

**Issue by erazemk** [tanujnotes/Olauncher#12]
This is similar to #11, but would allow the user to set the app's names either just for those that are set on the desktop or (preferably) for all the apps that are installed.

This functionality would make it easier for a user to recognise what an app does quickly (since there are no icons), e.g. "Metro"/"Vinyl" could become "Music".

This functionality is implemented in [Slim Launcher](https://github.com/sduduzog/slim-launcher) so if needed, the basic implementation code is available from there.

**Comment by tanujnotes** [comment]
Rename app feature will be available but only for the apps on home screen.

**Comment by subnut** [comment]
@tanujnotes Any ETA?

**Comment by tanujnotes** [comment]
ETA: Before christmas.
