### ISSUE TITLE
Wallpaper review 

### ISSUE THREAD

**Issue by Supreme-Alexis** [tanujnotes/Olauncher#120]
Please i would be glad if some of the wallpapers come as scary or action kind of wallpapers. Thanks for your time

**Comment by tanujnotes** [comment]
Scaring people is not the purpose of Olauncher wallpapers. If you want specific type of wallpapers, you can always find them and apply yourself. :)

**Comment by Supreme-Alexis** [comment]
I am well aware of that but the serene view tends to get boring sometimes. So let's forget about the scary what about the action kind or humorous just some energy please.

**Comment by tanujnotes** [comment]
Fair enough. Send me the link of those wallpapers and I'll add them if possible. They should be high quality phone wallpapers with a permissive license.

**Comment by Supreme-Alexis** [comment]
Much obliged. List of a few links i know... Unsplash. Com, www.pexels.com, www.techradar.com

**Comment by tanujnotes** [comment]
I'm aware of the websites. I need the links to exact wallpapers. :)

**Comment by Supreme-Alexis** [comment]
Wallcoo. Net, high deviantart, hdwallpapers. Net
