### ISSUE TITLE
[feature request] switchable app lists for home screen

### ISSUE THREAD

**Issue by D-ominik** [tanujnotes/Olauncher#124]
Currently there is the app list for the home screen, where you can add up to 8 apps to. That's fine as it is. It would be great to have the possibility to create multiple "home screen app lists". It should be possible to choose in the settings which app list is shown on the home screen (mainly to edit the individual app list).

The key feature would then be a function to select the active (displayed) app list programmatically. In other words: control which of the home-screen-app-lists is shown using some kind of API, like "Android Intents" or something else. This way, one could then use any automation app (such as Tasker) to control the selection of apps on the homescreen.

For example, you could show a different app list at home than in the office. In the car, another list appears containing, for example, navigation apps.

**Comment by tanujnotes** [comment]
Currently this is beyond the scope of Olauncher | Minimal AF. Maybe in the future.
________________________________
From: Dominik Seeger ***@***.***>
Sent: Wednesday, September 15, 2021 3:11:35 PM
To: tanujnotes/Olauncher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanujnotes/Olauncher] [feature request] switchable app lists for home screen (#124)


Currently there is the app list for the home screen, where you can add up to 8 apps to. That's fine as it is. It would be great to have the possibility to create multiple "home screen app lists". It should be possible to choose in the settings which app list is shown on the home screen (mainly to edit the individual app list).

The key feature would then be a function to select the active (displayed) app list programmatically. In other words: control which of the home-screen-app-lists is shown using some kind of API, like "Android Intents" or something else. This way, one could then use any automation app (such as Tasker) to control the selection of apps on the homescreen.

For example, you could show a different app list at home than in the office. In the car, another list appears containing, for example, navigation apps.

**Comment by tanujnotes** [comment]
Currently this is beyond the scope of a minimal launcher like Olauncher. Maybe in the future.
