### ISSUE TITLE
White status bar symbols in light theme

### ISSUE THREAD

**Issue by Heike-HS** [tanujnotes/Olauncher#126]
Hi Tanuj
Since version 3.4.2 the status bar does not show in black in home screen whith light theme activated. Shoudn't it do that?
OS is Android 10.
Heike (@scherer26)

**Comment by tanujnotes** [comment]
Hi, can you please post a screenshot? That'd be helpful.

**Comment by Heike-HS** [comment]
'Show Status bar' is ON in olauncher settings.

**Comment by Heike-HS** [comment]
Next try...

![Screenshot_light theme_ white status bar](https://user-images.githubusercontent.com/76911118/135716546-770a72f7-d2f4-497f-a4f1-beb91ad38a56.png)

**Comment by MichiBaum** [comment]
I **do not** have the issue with my Xiaomi Mi 11 Lite.
- Olauncher V 4.3.2
- changed Olauncher dark  and light mode to test
- changed native settings dark and light mode to test

With my phone there is no Problem.
Hope it helps

**Comment by Ilithy** [comment]
Like @MichiBaum I don't have this display bug (see screenshot, in light theme).

![Screenshot_20220131-101315](https://user-images.githubusercontent.com/36798218/151768703-6d991417-fdf4-4a72-ad1b-6ecec1932737.png)


_Google Pixel 6 pro
Grapheneos - Android 12
Olauncher v3.4.3 (battery optimization disabled, access to sensors disabled)_

**Comment by tneo** [comment]
@Ilithy Off-topic, loving the back-ground. Would you mind sharing a link to that?

**Comment by Ilithy** [comment]
Hi @tneo This is not mine, but a background selected by Olauncher, I don't have access to it sorry.
_And I didn't install it anymorebecause I use the [OlauncherCF](https://github.com/jooooscha/Olauncher) fork, which doesn't have a changing wallpaper (but doesn't have internet access in return)_
Sorry again but @tanujnotes might know how to find it 🤔

**Comment by tanujnotes** [comment]
@tneo https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d
