### ISSUE TITLE
Mixture of triple and quadruple tapping changes theme and also crashes the app

### ISSUE THREAD

**Issue by JacksonCampbell99** [tanujnotes/Olauncher#130]
It appears that excessive triple tapping to change the theme while the app is still in the process particularly crashes the app. Mixture of tripling quadruple had the same effect. This isn't really a problem because I could assume that sending commands over and over to an app would make it crash. It also causes it to remove default from the launcher. Quadruple tapping sends you away from the launcher to the last app you're using. Going home pops up a thing to choose the default launcher. The quadruple tap appears to be a feature since when used on its own it is totally consistent and Android doesn't bring up a crash notice.

**Comment by tanujnotes** [comment]
Removed this feature for now. If was causing crash and confusion for many users. Will try to find a better way to integrate this in the future.

**Comment by JacksonCampbell99** [comment]
No!!! My favorite feature! Please don't remove double tap to change theme!

**Comment by tanujnotes** [comment]
I'm sorry man. I know it was convenient but it was also getting me some bad reviews. I'll try to fix it in future updates.

**Comment by JacksonCampbell99** [comment]
What else has changed or been added that I'm missing in the new version?

**Comment by tanujnotes** [comment]
Nothing major. Just fixed some minor annoyances and added public roadmap link: https://tanujnotes.notion.site/Olauncher-Roadmap-1522aa8182424415b5b89bed923b0ccd

**Comment by JacksonCampbell99** [comment]
Not looking forward to missing great features while double tap is coming back. I use it daily. Manually switching constantly is not at all convenient.

**Comment by tanujnotes** [comment]
Here's the latest version with triple-tap enabled
https://www.dropbox.com/s/4yw97ui0acvbvqz/Olauncher-v3.4.3-TT.apk?dl=1

**Comment by JacksonCampbell99** [comment]
I'm getting this error when I try to install it after downloading it.
![Screenshot_20220101-115409_Package installer.jpg](https://user-images.githubusercontent.com/76508020/147859147-73f2a794-6b6e-4225-82a3-1f42d581a0f1.jpg)
I'll have to reinstall it I guess.

**Comment by tanujnotes** [comment]
Uninstall the existing Olauncher app then install from the apk. They both have same signature and version number that's why the conflict.

**Comment by JacksonCampbell99** [comment]
I ended up doing that.

**Comment by JacksonCampbell99** [comment]
Can you please bring back triple tap? I'm missing it.

**Comment by tanujnotes** [comment]
@JacksonCampbell99 Triple tap to change theme?

**Comment by JacksonCampbell99** [comment]
Yes, I'm missing it haha.
