### ISSUE TITLE
1000ms press and hold for settings is really long

### ISSUE THREAD

**Issue by JacksonCampbell99** [tanujnotes/Olauncher#131]
It always feels like 3 seconds, even though it isn't. I'd appreciate 500ms or just 750ms if the former is too short.

**Comment by yephny** [comment]
I agree, the wait is too long just to launch a hidden app.

**Comment by teemue** [comment]
I think it's just fine as it is. At least I don't need to access settings that often. Shouldn't hidden apps be shown if they are supposed to be used?

**Comment by JacksonCampbell99** [comment]
@teemue Out of sight, out of mind. I only want to use social apps for specific things that might come up, so I hide them in there. The longer time on press is good for that. I want it shorter for when I change theme and background settings back and forth, which I do often.

**Comment by yephny** [comment]
@teemue Even if they're rarely used, I don't understand why you'd need to wait to launch them.

**Comment by tanujnotes** [comment]
Long press for settings is currently Android's default long press delay + 600 milliseconds. Reduced the added time to 500 ms. Different phones can have different long press time so can't do much about this.

**Comment by JacksonCampbell99** [comment]
I just installed the new version by the link you sent me, and the long press on home screen seems longer even though you said you shortened it. Also, the haptic is gone (not sure if I care about that).

**Comment by yephny** [comment]
The vibration was removed by the developer intentionally, it was an unwanted feature.

**Comment by tanujnotes** [comment]
I was getting complaints about the vibration. Different phones vibrate with different intensity and so it's quite annoying on some phones. Long press duration was shortened by 100ms. I don't want to lessen it further or it will result in accidental opening of settings page.

**Comment by JacksonCampbell99** [comment]
I must be misunderstanding something. I've been taking about long pressing on the home screen to access Olauncher settings.

**Comment by tanujnotes** [comment]
I'm talking about the same. It's currently less than 1 second. Long ago it was around half second and I got a lot of complaints regarding accidentally opening Olauncher settings.

**Comment by JacksonCampbell99** [comment]
Ok, I see.
