### ISSUE TITLE
"Swipe down on the app list" doesn't work in a specific circumstance

### ISSUE THREAD

**Issue by yayayeet69** [tanujnotes/Olauncher#137]
If you open the app drawer, swiping down to return to the home screen doesn't work if the app drawer has few enough apps where you can't scroll the app drawer up and down.

This occurs if you have only a few apps installed on your phone or have hidden enough from the app drawer. 

To return to the home screen, you must press the back button on the navigation bar (or back gesture if using gestures)

**Comment by tanujnotes** [comment]
This is fixed and will be available in the next release.
