### ISSUE TITLE
[Feature Request]An option to add a music control widget and a weather wind get linked to Google weather

### ISSUE THREAD

**Issue by Mielisi** [tanujnotes/Olauncher#140]

**Comment by yephny** [comment]
I think it contradicts with the app's goal of keeping it as simple and minimal as possible.

**Comment by Clasher31HD** [comment]
No, i think not. I mean it would be an option to turn on and off by default

**Comment by tanujnotes** [comment]
Widgets might be added sometime in the future but they're not the priority. Closing this issue for now.
