### ISSUE TITLE
Landscape on phone is ON

### ISSUE THREAD

**Issue by ANDREW007CZ** [tanujnotes/Olauncher#144]
I've downloaded the non-rotating (only landscape) version but it still rotates when I tilt my phone.

Sony Xperia X Compact, A 8 Oreo
Olauncher 3.4.2
![Screenshot_20211129-111913](https://user-images.githubusercontent.com/26521196/143850621-8004248e-2e4d-44a1-b2c2-b5eabb4b7b03.png)

**Comment by tanujnotes** [comment]
Can you try downloading from F-Droid or Play Store once?

**Comment by ANDREW007CZ** [comment]
Sorry for no response. Last version I downloaded from F-Droid. Landscape still present.
![Screenshot_20220112-102639](https://user-images.githubusercontent.com/26521196/149103656-507fe064-415d-4cde-b1af-26295c23c569.png)

**Comment by tanujnotes** [comment]
Oh I forgot to mention before. Due to a bug present only in Android 8, full screen transparent apps cannot be locked into portrait mode. I can't really do much here. :|

**Comment by tanujnotes** [comment]
By the way I just added better support for landscape mode and fixed the UI overlaps. Try the olauncher-landscape apk from the latest release here: https://github.com/tanujnotes/Olauncher/releases/tag/v3.4.3

**Comment by ANDREW007CZ** [comment]
I see. Cool, thx for info, will try.
