### ISSUE TITLE
Double Tap to Lock screen sometimes not working

### ISSUE THREAD

**Issue by skyGtm** [tanujnotes/Olauncher#150]
First of all thank you for creating such a beautiful and minimalistic app. I have been using it for few months now, and I am happy to say, I'm LOVIN' it.

Problem:
Double tap to Lock not working, when screen is unlocked via FingerPrint/Pin Code then Double Tapping don't Lock screen immediately.

https://user-images.githubusercontent.com/50160188/149554499-83b5b11b-8aa5-4a50-85ab-aeaa62e38c37.mp4

Works When:
1. when Recent apps is opened and closed

https://user-images.githubusercontent.com/50160188/149554167-f12a4b11-8568-4754-b1c5-0734b9445843.mp4

2. When show all Apps is opened and closed

https://user-images.githubusercontent.com/50160188/149554176-91711dcd-6d93-4592-939e-81d55db345be.mp4

Workaround:
I have been using this open source app ![Lock](https://github.com/seguri/Lock) in one of the app slots. which works flawlessly.
If Olaucher fixes the issue, I will have one app slots available in home screen for other apps.

Android Version: 9 (Pie), Huawei Nova 3i
Accessibility State: ON
Double Tap to Lock State: ON
Battery Optimization: Disabled for Olauncher

If required, feel free to ask for Logcat and debug app testing. 
Thank you

**Comment by tanujnotes** [comment]
Can you check your phone see if there's something called `Startup manager`. If you find it, toggle the switch in it for Olauncher. And if you have an app called PowerGenie in your phone, toggle the switch there as well if you haven't already. More details: https://dontkillmyapp.com/huawei
Let me know if this fixes the issue.

**Comment by tanujnotes** [comment]
Looks fine. This is most probably app's fault then. I'll see what I can do.

**Comment by D-ominik** [comment]
It would be good to know, if the double tap does not work or if the triggered lock action fails. The swipe left/right gestures do always work. Unfortunately the double tap thing is a fixed action and no app can be selected, like with the swipe gestures.

**Comment by tanujnotes** [comment]
Anyone who comes here: Check the About page in Olauncher settings, take the suggested steps, and if that doesn't fix it, I don't know what will. :|
