### ISSUE TITLE
Notification Filter

### ISSUE THREAD

**Issue by chrishappy** [tanujnotes/Olauncher#151]
I think the only feature this app lacks to compete with the other big ones is filtering notifications.

E.g. I want notifications from my "Calendar Alarm" app, but don’t want my phone to act up when I get a new message.

**Comment by tanujnotes** [comment]
Currently there's no plan to add notification filter.
Besides, Android already handles notification pretty well. What you mentioned can already be achieved depending on your phone and OS. Just long press on the notification and you should see the option to silence it or disable it altogether.
