### ISSUE TITLE
Add an option to disable launcher animations

### ISSUE THREAD

**Issue by ferlanero** [tanujnotes/Olauncher#152]
In order to have even a more minimalist launcher add an option to disable launcher animations in settings page. This option would be great for increase performance in e ink devices too (like Hisense A5 Pro & A5 Pro CC)

**Comment by tanujnotes** [comment]
Not a priority.

**Comment by aichi-t** [comment]
Hi @tanujnotes 👋 
I had some questions regarding this feature request. But first of all, thanks for developing this launcher, I'm simply in love with it. I've tried countless launchers over the past few years including Nova, Niagara and minimalist phone launcher but Olauncher is definitely my favorite.

**Question**:
Do you have an idea on why Olauncher doesn't respect the system wide animation settings? Perhaps, does the app use a non-standard API to create animations? 

**Context:**
I have all animations turned off from the developer settings on Android but the animation within Olauncher persists. As you can see in this screen recording. Going back and forth between the settings app has no animation but opening the drawer does. 

I was thinking of investing some time to address this request but wanted to get your input first.

https://github.com/tanujnotes/Olauncher/assets/49226803/ee4f206d-1a17-4517-9ca3-89cbcd07d952

**Comment by tanujnotes** [comment]
These are 2 different animations. One is related to app opening/closing, which a launcher may or may not control. Olauncher doesn't. In that case, some phones add a default app launch animation, some don't.

The app drawer animation is a custom animation which occurs inside the app. I'm not entirely sure but I think disabling animations from phone settings doesn't disable the custom animations in an app, which is what seems to be happening here.

Anyway, I have added a check for refresh rate before applying the app drawer animation. If the refresh rate is less than 10, no animations. This should cover most e-ink displays. Coming in the next udpate.

**Comment by ferlanero** [comment]
This

> Anyway, I have added a check for refresh rate before applying the app drawer animation. If the refresh rate is less than 10, no animations. This should cover most e-ink displays. Coming in the next update.

This will bring new life to my Hisense A5 Pro CC & A9 e-ink phones. Thanks!
