### ISSUE TITLE
Rename App Labels

### ISSUE THREAD

**Issue by tobiasschmidt89** [tanujnotes/Olauncher#155]
Hey Tanuj,

it would be great if you could add an option to rename the Label of the Apps. As everything is Text based it would be a nice way to tidy up the App List and Homescreen. 

e.g. I would like to rename "Keep notes" to "Notes".

Nothing critical, but a nice enhancement.

Thanks for the great launcher and kind regards.

**Comment by tanujnotes** [comment]
You can already rename home screen apps. Long press on them and start typing for RENAME option. Renaming for all apps might be added later.
For more tips, please visit the About page in settings.

**Comment by ferlanero** [comment]
I'm so sorry, no need for more tips. I found it: You need to long press the app in main screen and when choosing list appears,just start typing the name you desire. Then a "Rename" button appears. This is all what I need. Thanks for all your effort on this incredible launcher!
