### ISSUE TITLE
Material You Colors

### ISSUE THREAD

**Issue by tobiasschmidt89** [tanujnotes/Olauncher#156]
Hello Tanuj,

it would be great if you could make Olauncher follow the current Material You colors.

E g. Currently my Pixel Phone shows a off white color on the lock screen. It would be great if Olauncher could pick up the same off white colors.

Thanks for the great launcher.

**Comment by tanujnotes** [comment]
I do plan to add this in the future but since this will be available only to Android 12 users, this is not a high priority.
