### ISSUE TITLE
[Feature Request] Move search fields

### ISSUE THREAD

**Issue by Ilithy** [tanujnotes/Olauncher#159]
It would be very handy to have an option to display the search field (from the drawer) at the bottom of the screen.

This makes one-handed navigation on large-screen smartphones much easier.

Thank you very much.

**Comment by tanujnotes** [comment]
That was my initial plan. But putting the search bar at bottom resulted in some unintended technical and design issues which I wasn't able to resolve. Since keyboard pops up automatically as soon as you launch app drawer, I hope this is not a big issue.

**Comment by Ilithy** [comment]
Clearly not :), thanks for the explanation.
