### ISSUE TITLE
[Feature Request] Battery indicator in the home screen

### ISSUE THREAD

**Issue by lichingyun** [tanujnotes/Olauncher#162]
is possible to add the battery indicator to the date/time indication in olauncher? 
with this I don't need to enable the statusbar and the upper shadow can disappear 😊 ( this can partially solve the bug #76 "2  shadows")
I am using Lineage Os 18.1 my phone is a Xiaomy Redmi Note 5 Whyred

**Comment by lichingyun** [comment]
#
![example_circle_battery](https://user-images.githubusercontent.com/79099214/152662437-3c65e3cb-73c3-4bf5-ac7d-a230b62be727.jpg)
I have found this picture 😇 I think this xan be a good idea, the circle is the battery level

**Comment by trev-dev** [comment]
There is a similar widget that comes with Motorola devices. I don't know what it is about the circle indicator that I like, but I do enjoy it. I would also take a line if I can get it, as the app is laid out like "justified text" on the whole.

**Comment by Ilithy** [comment]
I admit, I like it too, discreet and explicit enough (no need to be accurate to the percent)

**Comment by tanujnotes** [comment]
I get a lot of request for this and just don't get it so please help me understand. Event with status bar hidden, battery is visible on lock screen and whenever you're using any app. Exactly how much time you guys are spending on the home screen? (I know it looks gorgeous but still)

**Comment by DadiBit** [comment]
I personally keep some apps with the status bar hidden (SystemUI Tuner), so I sometimes end up not seeing the battery percentage.
Although I agree that the launcher should be used to launch stuff and not to glance at it, I also think that having immediately a feedback on the battery percentage could help with productivity (eg: I'm in a rush and I want to know if the will survive until I can get a chance to charge it)...
One possible solution (I came up with recently) to clear the clutter, is to create a custom top status bar (keeping notches into consideration) and hiding it when the user wants to see the system status bar. It could also be a bottom bar but I'm not too sure it would be as user friendly... I'm also not too sure one could easily tap the hour and open the clock, something that could be mitigated if the bar was at the bottom.
Regarding it's content: I would keep it minimal, like the clock and the battery icon... 
With that said, at this point it would make more sense to just install a separate custom status bar app
