### ISSUE TITLE
[Feature request] Let users choose in which timeframe to open calendar app

### ISSUE THREAD

**Issue by ndulisdul** [tanujnotes/Olauncher#163]
There should be an option that lets you choose in which time frame the calendar is being opened upon tapping the date. I'm pretty certain that people open the calendar more often to see what's going on in a specific week or month rather than checking what's going on on the current date.

Another minor request: Possibility to add folders/categories to home screen. Privacy-friendly environments often force you to use 5 different apps whereas google etc. may offer an app that does it all. Also, people increasingly use several messengers where it used to be just whatsapp and sms.

Amazing launcher! The feature that opens apps automatically in search mode is mind blowingly simple and efficient.

**Comment by tanujnotes** [comment]
These features are not a priority at the moment. They might be added in the future. Thank you for using Olauncher.

**Comment by yephny** [comment]
Hey @tanujnotes , why don't you make the calendar button simply launch the default calendar app, instead of using it as a widget that opens the current date within the calendar app? It would be trivial to implement, and would directly solve the issue at hand.
