### ISSUE TITLE
Translation of application descriptions into Turkish.

### ISSUE THREAD

**Issue by gaometri** [tanujnotes/Olauncher#167]
[values-tr-rTR.zip](https://github.com/tanujnotes/Olauncher/files/8075017/values-tr-rTR.zip)

Translation of application descriptions into Turkish.

**Comment by gaometri** [comment]
No problem.  You can use.

**Comment by Ilithy** [comment]
Thank you, I take care of it quickly

**Comment by Ilithy** [comment]
Done on #160 , thanks again

**Comment by tanujnotes** [comment]
I'll come back to this when adding translations. Closing it for now.
