### ISSUE TITLE
[Feature Request] Screen time diplayed on home screen

### ISSUE THREAD

**Issue by alping** [tanujnotes/Olauncher#169]
It would be great if there was an option to display accumulated daily screen time on the home screen (e.g. "2 h 23 m" or "2:23")

I use usageDirect (on FDroid) for tracking app and screen time, but I would like a more obvious reminder of the fact that every time I use my phone I spend some of my limited time (and often more than I want to).

I realize that this being a minimalistic launcher, careful consideration has to be put into adding any new features. However, I think that this feature would be in line with the goal of the app (as I understand it) to "focus on the things that actually matter".

Thank you for your work,
Peter

**Comment by tanujnotes** [comment]
This feature is currently out of scope. Maybe in the future.
