### ISSUE TITLE
Regex match application names

### ISSUE THREAD

**Issue by erazemkokot** [tanujnotes/Olauncher#17]
Currently applications have to be an exact match when selecting them using the keyboard, so for example, you have to type "f-droid" for F-Droid to be a match (`F-`) is usually enough.

This is a bit annoying, since you have to switch between characters of the alphabet (default keyboard layout) and the special characters.

What I propose is to match any characters of an app and maybe prioritise those that are together.

So ideally F-Droid could be found either by typing "F-" or "fdroid". The same principle would apply to other apps of course.

**Comment by tanujnotes** [comment]
Fixed in the latest version (v1.0).
