### ISSUE TITLE
Scale wallpaper to fit

### ISSUE THREAD

**Issue by BWPanda** [tanujnotes/Olauncher#170]
Is there a way you can set the wallpapers to scale so they fit the entire screen?

I ask because today's wallpaper is too skinny for my phone and so has black vertical bars on either side: https://i.redd.it/ev7xudy24rt11.jpg

**Comment by BWPanda** [comment]
Same with this one: https://i.redd.it/eqxbv1q482681.jpg

**Comment by Ilithy** [comment]
you must have a really wide screen with a very high resolution, personally I currently have a pixel 6 pro with a 6.7" panel and a resolution of 3120 x 1440 px and I have no black border...

**Comment by BWPanda** [comment]
Nope, just a Xiaomi Mi A1:
- 5.5 inch screen
- 1080 x 1920 pixel resolution

**Comment by hxd2772** [comment]
I have the same issue with a Samsung galaxy s7

**Comment by tanujnotes** [comment]
This happens when the wallpaper is too tall and phone screen is not. Need to fix the wallpaper scale logic for all screen types.
