### ISSUE TITLE
support PWA and "add to home screen"

### ISSUE THREAD

**Issue by kylrth** [tanujnotes/Olauncher#173]
I'd like to be able to add progressive web apps or shortcuts to my Olauncher menu by clicking "Install" or "Add to home screen" from the Firefox menu, but Olauncher seems to not support this. (You can see [here](https://github.com/mozilla-mobile/fenix/issues/7616) that Firefox for Android removes those buttons when the launcher doesn't support them.)

Is there a chance that support could be added for PWAs or shortcuts?

**Comment by foxB612** [comment]
Seems duplicated with #20

**Comment by kylrth** [comment]
yeah
