### ISSUE TITLE
change link app from clock widget

### ISSUE THREAD

**Issue by domiEf** [tanujnotes/Olauncher#175]
I would love to be able to set the app you reach when you click on the clock widget.

currently it brings you to alarm clock but I don't use the standard alarm. 

thanks a lot for the great launcher.

**Comment by tanujnotes** [comment]
In my testing, it shows all clock apps when you click time. It's possible that you have a default clock set. Try resetting the default clock app in your phone settings and let me know if it works after that.

**Comment by tanujnotes** [comment]
You can now (v4.0.6) long press on time and date to select which clock and calendar apps to launch.
