### ISSUE TITLE
rename apps on lockscreen

### ISSUE THREAD

**Issue by domiEf** [tanujnotes/Olauncher#176]
some apps have terrible names or stuff like pro/free/classic/... in the name.

it would be very nice to be able to change the shown name, it would create a simpler look.

Example: "locus Map classic", i want it to show just "Maps".

thanks a lot. when I'm on my computer at home, I'll buy you some coffees, app is already great!

**Comment by oscarale-camorlinga** [comment]
I second this request! As much fun as opening up an apk, editing the name, and then repacking sounds, it would be much easier to just have an option to rename an app from the launcher. For example renaming apps like "Open Camera" to "Camera" or "QKSMS" to just "Messages" would be great. Maybe have a pencil icon next to the little (i) icon when you tap and hold on an app name to edit the name.

App looks and feels awesome as it is! Great work so far.

**Comment by Charles7z** [comment]
This would be nice.

Possibly an edit icon in the app drawer when long pressing on app, like show & info icons.

**Comment by dasauto1** [comment]
You can already rename the apps. Select the app you want to display. Once added long press as if you are selecting another app, type the name you want the already selected app to show and click on rename on the right. I had renamed almost all my apps similarly.
