### ISSUE TITLE
[Feature request] Option to autoswitch between light and dark themes based on system

### ISSUE THREAD

**Issue by Ke1i** [tanujnotes/Olauncher#177]
Hi..
Thanks for the awesome launcher.
Is it possible to have an option that switches the launcher's theme based on the system theme?
I'm on Android 11 and it's possible to change the system theme (light/dark) based on the time of day or on custom hours.
As it is, I have to manually switch Olauncher's theme when my system theme changes.

**Comment by Ilithy** [comment]
Hello, already implemented, it is enough to remain two or three seconds the finger on the mode of the theme, that will pass it in mode "follow system".

**Comment by Ke1i** [comment]
Oh.. I didn't realize. I only saw two options, light and dark.
Just saw 'system' after hovering my finger for a few more seconds, thanks.

**Comment by Ilithy** [comment]
You're welcome

**Comment by harryloewen** [comment]
Thank you for the hint. Does someone know why this option is somewhat hidden? Could we make it a top level option?

**Comment by tanujnotes** [comment]
Two reasons:

1. When the daily wallpaper is On, sometimes automatically switching themes causes crash. Not sure why.

2. We currently don't have a very good collection of wallpapers for light theme because they're hard to find. So I want most people to stick with dark theme.

Once these issues are resolved, System theme can become a top level option.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/177#issuecomment-1213481126

@tanujnotes, I switched launchers a while ago because that option was hidden. Hiding it is really silly. I can only now reconsider reusing OLauncher again because I *happened* to stumble across a solution here, in GitHub!

**Comment by tanujnotes** [comment]
@RokeJulianLockhart Why is it silly?

**Comment by tanujnotes** [comment]
When I say wallpaper, I mean Olauncher's daily wallpaper, which had some issues when switching from/to dark or light mode. I meant most people stick to one theme when using Olauncher.

But the real reason why every thing in Olauncher is the way it is - I like the way things are, enough people seem to share my feeling and, most importantly, I'm not much interested in changing anything.

Thank you for your interest.
