### ISSUE TITLE
Swipe down to dismiss app drawer stops working

### ISSUE THREAD

**Issue by Charles7z** [tanujnotes/Olauncher#178]
Ignore this. I downloaded the landscape version on my phone, didn't read everything 🤷

 Installed correct version, seems fine!

Nope, didn't wait long enough. Still doing it.

I've tested this a couple times by clearing app data and restarting the phone, nothing permanently fixes.

After some period the swipe down gesture to dismiss the app drawer stops working.

After clearing data and setting up app all was working till I hid apps. 

Other times I just forgot it wasn't working because I've become so used to back or home to escape app drawer.

Normally not much of an issue as you are launching apps. I only noticed because I've been testing this app with others.

Setup
Moto G Power 2021
Android 11

**Comment by tanujnotes** [comment]
It happens when you type a few characters and the list is short enough that it's not scrollable. Should work fine in the latest update.
