### ISSUE TITLE
Clock widget on top does not launch timers or stopwatch

### ISSUE THREAD

**Issue by lacan** [tanujnotes/Olauncher#183]
The show Date/Time option is awesome because I can get a clock on the top left of my Home screen.

However. Unlike when opening the "Clock" app, then I click on the time display I can only set alarms and it timers or stopwatches, forcing me to call upon the "Clock" app itself when doing that.

This is not the case with the default UI where pressing on the time date widget actually opens the "Clock" app with all options (alarm, timer and stopwatch).

Is there any way to change the behaviour?

Best

Is there a way

**Comment by Juan-132** [comment]
Any updates on this one? I miss this too. The standard clock app has: Alarm, Timer, Stopwatch at the bottom

**Comment by tanujnotes** [comment]
This probably won't be fixed. I did some searching and I couldn't find any Intent that Android provides to launch clock apps like it does for alarms, calendars, browsers, etc.

The issue depends on how the clock app is implemented as well. E.g. Xiaomi phones launches the full clock app while Samsung phones are launching just the alarm screen.

Anyway, if someone proposes a solution for this, I'll implement it. For now I'm closing the issue.

**Comment by arcstur** [comment]
Same thing here (was about to open a new issue). Opening "Clock" shows all options, and tapping the time only opens Alarms. 
The launcher "minimalist phone" opens Clock correctly on my phone if I remember it well.
