### ISSUE TITLE
Lagging on pixel 6 graphenos

### ISSUE THREAD

**Issue by Grkrz** [tanujnotes/Olauncher#187]
Hej the app is working slow. When I am tapping an app sometimes have to type twice for it to work.

**Comment by tanujnotes** [comment]
Does it happens to home screen apps only? Or any app in the app drawer?

**Comment by Grkrz** [comment]
Hej 
I think it is mostly the case with the main screen.

**Comment by PoorPocketsMcNewHold** [comment]
Doesn't seems specofically to be the rom, as it's working fine of a Pixel 4 grapheneos.

**Comment by Grkrz** [comment]
Hej 
I think it is mostly the case with the main screen.



Jul 4, 2022, 14:56 by ***@***.***:

**Comment by Soren90** [comment]
This is happening for me on OnePlus stock rom as well. Has anyone been able to solve this?
