### ISSUE TITLE
[Feature Request] Auto light and dark mode depending on time

### ISSUE THREAD

**Issue by hxd2772** [tanujnotes/Olauncher#188]
The feature specified in the title would be nice since this launcher is very clean and I prefer it over Niagara launcher. 
Thank you for developing this app!

**Comment by TettaVolante** [comment]
You can do that by setting the theme to system in Olauncher settings 
-you do that with a long press on the dark/light option- 
and then schedule the dark and light themes
-search for 'schedule' or 'dark' in android settings-

**Comment by hxd2772** [comment]
My phone does not have a dark mode

**Comment by TettaVolante** [comment]
Can't help with that, sorry

**Comment by hxd2772** [comment]
Oh well, I will still use this over Niagara!😃
