### ISSUE TITLE
installed app not listed after hiding

### ISSUE THREAD

**Issue by adrianjost** [tanujnotes/Olauncher#189]
I think I have hidden an app from my work profile (slack) a couple of days ago but somehow now can't find it anymore. It's not appearing in the general app list and not in the hidden list either. It's also not available in the list if applications to put in the main screen.

I currently need to search the app in the work profile play store in order to open it again. So I am confident that it's still installed.

Please let me know, how I can help troubleshoot this issue. I've already tried to reinstall the application but it's still not appearing anywhere. Other apps from the work profile I have hidden also work just fine.

**Comment by tanujnotes** [comment]
Hey, can you try reinstalling Olauncher? It should fix the issue for now. I'll see what I can do.

**Comment by adrianjost** [comment]
Sure. Just cleared all saved data of OLauncher and it's now back in the list.

**Comment by Sagarparvizali** [comment]
Same issue with me, i hide couple of apps and now i can't find them anymore

**Comment by tanujnotes** [comment]
Long press anywhere on the home screen to open settings. Tap on the 'Olauncher' text on the top to see your hidden apps. For complete feature list, please visit the About page in settings.

**Comment by Sagarparvizali** [comment]
Thank you, yeah it's there...

Long Tap on homescreen<<Tap on Olauncher<<hidden apps
