### ISSUE TITLE
Disable wallpaper

### ISSUE THREAD

**Issue by teemue** [tanujnotes/Olauncher#19]
Probably a bug? I tried daily wallpaper but prefer black background. Turning wallpaper off won't disable it.

**Comment by tanujnotes** [comment]
When you disable the wallpaper, the current wallpaper stays. That's expected behaviour because if someone liked a wallpaper and wanted to keep it for longer period, they can just turn off the daily wallpaper update.

**Comment by teemue** [comment]
I understand. How about adding a third option to the options of daily wallpaper - like ON / FREEZE / OFF?

**Comment by tanujnotes** [comment]
Wallpaper is a part of the OS itself, not the app that only I control. Any app can change the wallpaper. It will be too complicated to keep a track of previous wallpaper and revert back to it and do it correctly. Too much effort for little gain. I hope you understand.

**Comment by teemue** [comment]
Ah, I thought it's a setting inside the launcher. Well, case closed then, I have black background now :-)
