### ISSUE TITLE
Add Persian calendar option

### ISSUE THREAD

**Issue by ashrafimostafa** [tanujnotes/Olauncher#193]
Hi,

I'm Persian people and use Olauncher as my default launcher for while, the feature that i need is that show date in Persian format. may i send PR for that? 
I want to add option in setting page for choosing date format.

**Comment by Erictheplague** [comment]
Use default

**Comment by tanujnotes** [comment]
Hi, we won't be supporting this level of customisation because multiple types of date formats are used throughout the world and supporting multiple of them won't be practical. Feel free to fork the repo and make changes for yourself. Let me know if you need any help. Thank you.
