### ISSUE TITLE
When opening 'Phone' swiping, the number screen always shows

### ISSUE THREAD

**Issue by Darkmaster006** [tanujnotes/Olauncher#194]
Hello! This app is great and very helpful, but there's one bug I've found: when opening the 'phone' app from the 'swiping' feature, the phone app always opens on the screen with numbers and not 'last screen used', as I have it configured. When I opem 'Phone' normally, it does opem in the last screen used. (More correctly, when swiping, Phone opens in last screen but immediately changes to numbers screen). Any way to fix this? Thank you.

**Comment by tanujnotes** [comment]
Go to Olauncher settings and set it to open your Phone app. It should work as expected after that.
