### ISSUE TITLE
[ENH] Make homescreen easier to use with one hand

### ISSUE THREAD

**Issue by Juan-132** [tanujnotes/Olauncher#202]
![Screenshot_20220730-173511_Olauncher](https://user-images.githubusercontent.com/59505296/181924021-b1a01a44-68f6-4024-8fab-58f724f469f3.jpg)

Most devices are pretty big these days, which makes it difficult to reach the top with one hand. 

Why not move the app list, and clock down a bit, and put most of the whitespace at the top?

**Comment by tanujnotes** [comment]
Latest release has the option to move apps to the bottom. It's currently rolling out. Should be available in next few days.

**Comment by Juan-132** [comment]
Thanks @tanujnotes

I'll keep an eye out for the update

**Comment by Juan-132** [comment]
@tanujnotes

Hoe do I enable the new feature?
I don't see any option in settings after updating

**Comment by tanujnotes** [comment]
Tap on App alignment and look at the left side for Bottom: On/Off
