### ISSUE TITLE
[ENH] Bigger touch area for items on home screen

### ISSUE THREAD

**Issue by Juan-132** [tanujnotes/Olauncher#203]
![Screenshot_20220730-173511_Olauncher](https://user-images.githubusercontent.com/59505296/181925736-d511684f-7417-401c-b1b2-b089ca23dc31.jpg)

I like the items aligned on the Left.
but use the phone right handed.

It would be nice if the touch  area for the items would not only be the text itself, but the white space to the right as well.

This makes it easier to select an item with one hand.

**Comment by ongots** [comment]
For me, an enlarged area causes false clicks.

**Comment by tanujnotes** [comment]
This is a bad idea because it will cause unexpected clicks and conflicts with double tap to lock.

**Comment by verekia** [comment]
Love everything about this launcher except this. I would also prefer a full-width clickable area, like in Minimalist Phone launcher. It never caused false clicks to me when I was using it. They highlight that whole area on click so it's explicit. Maybe having it as an option. But i understand that we can't always get what we want. So thanks for making this app anyway :)
