### ISSUE TITLE
Stop delivering 3.5.0-beta via FDroid

### ISSUE THREAD

**Issue by gitfineon** [tanujnotes/Olauncher#204]
Good morning 
this version boke my phone today. The launcher does not open after the upgrade this morning and I can't do a downgrade, because uninstall tells: 
```
Error -2: the system failed to delete the package because it is the active device policy manager.
```
I went to the settings via pull down menu and switched back to trebuchet as home app for now. But the uninstall message is still the same. Just restarted the device with Trebuchet active, but still not possible to uninstall Olauncher via FDroid. Found out, that I have to use the Settings > Apps and notifications menu to uninstall Olauncher, because it can "deactivate & uninstall".

| Uninstall attempt via FDroid | Uninstall via Settings |
| -- | -- |
| ![Screenshot_20220801-081106_F-Droid](https://user-images.githubusercontent.com/11716650/182085458-23292cbe-9e32-48c9-981d-964c0559e0fe.png) | ![Screenshot_20220801-082205_Settings](https://user-images.githubusercontent.com/11716650/182085462-c361173d-dad4-4b63-90dd-22eef1c74ea8.png) |

**Comment by tanujnotes** [comment]
Hi, it's possible that Olauncher has device admin permission on your phone and that's why it can't be deleted. We needed that permission for double tap to lock in older versions but not anymore. Please disable it from your phone settings and you should be able to uninstall. 
I'm aware of the issue in  the latest version and working on it.

**Comment by gitfineon** [comment]
Wow, that was quick. But it is not possible to change settings if the app does not open at all. I managed to uninstall via settings. And was able to reinstall Olauncher afterwards, but now all my settings are gone!

**Comment by tanujnotes** [comment]
Hey, would you be able to test this apk for me? You'll have to install the older version first ([v3.4.3 or older](https://github.com/tanujnotes/Olauncher/releases/tag/v3.4.3)) and then update via this apk. Sorry for the inconvenience. Actually it's not crashing on any of my devices so I can only guess-fix.
APK: https://wormhole.app/xdBqW#tAou5q4KH4_V93H42qoD-g

**Comment by gitfineon** [comment]
I'll do so after work!

**Comment by tanujnotes** [comment]
Never mind. I found a way to replicate it. Issue is fixed and sending an update.

**Comment by gitfineon** [comment]
Oh, I missed to thank you for your kind work! Btw. great Wallpaper today!
