### ISSUE TITLE
[ENH] Also move clock down when app list is moved down

### ISSUE THREAD

**Issue by Juan-132** [tanujnotes/Olauncher#205]
In followup from: https://github.com/tanujnotes/Olauncher/issues/202

Thanks for this new feature! 

I would suggest also moving the clock down, if the app list is moved down. 
The clock is also a clickable surface, and would benefit from one handed use. 

Right now it also look a bit weird with the big gap between app list and clock. 
Why not position the clock at the same level as on the lock screen? 

LOCKSCREEN
![Screenshot_20220802-093913_Olauncher](https://user-images.githubusercontent.com/59505296/182319806-29c3a3ea-7fd7-4ab2-9e48-25fb3a40818b.jpg)

HOME SCREEN 
![Screenshot_20220802-093919_Olauncher](https://user-images.githubusercontent.com/59505296/182319810-62e4b4dc-9c88-452d-9b49-1d0a2b6c673a.jpg)

Thanks for making this great launcher!

**Comment by tanujnotes** [comment]
This will require a significant rewrite of user interface which is not planned for anytime soon.
