### ISSUE TITLE
[Bug] Too easy to accidentally change home screen apps

### ISSUE THREAD

**Issue by Juan-132** [tanujnotes/Olauncher#207]
Situation:
Accidental long press on applist item on home screen

To reproduce:
1. Long press an item on the home screen
2. Touch area to the left (away from the textitem) 

Result: A new default app is selected, and user is returned to the home screen

Expected result: Action is cancelled,  and user is returned to the home screen

https://user-images.githubusercontent.com/59505296/182327546-c14661eb-704f-494b-b27c-ecb95c6ebb25.mp4

**Comment by tanujnotes** [comment]
This is by design. App drawer apps are full width (while home screen apps are not). If you accidentally change a home screen app, change it back.

**Comment by Juan-132** [comment]
@tanujnotes

How about providing visual feedback after the change.  For example that the changed item highlights once after being changed

Because right now it's too easy for the user to make errors without noticing

**Comment by Juan-132** [comment]
Changing home screen apps is something you do infrequently,  but right now is very easy to do (and makes it easy for errors to slip in as well)

**Comment by tanujnotes** [comment]
If memory serves me well, you'll probably the first person to complain about this. If more people report a similar issue, I'll look into it. Sounds good?

**Comment by Juan-132** [comment]
Excellent 👌

It is just a suggestion for improvement

**Comment by jooooscha** [comment]
@Juan-132 In my [forked version](https://github.com/jooooscha/Olauncher) I implemented a lock for the home screen, which prevents accidental change. This might solve your problem
