### ISSUE TITLE
[Feature Request] Per-app delayed launch

### ISSUE THREAD

**Issue by jaxankey** [tanujnotes/Olauncher#209]
If we could assign a delay before launch for each app (default 0), this would greatly help avoid focus-stealing apps. The pre-launch delay screen should be as boring as possible, just saying the app name and "delayed launch" with no timer or countdown or any other eye-catching / exciting information. Then the app launches.

Such delays really deter impulsively opening apps that steal focus, e.g., reddit or angry birds (I know this because I play angry birds offline and the 30-second internet timeout while it tries to connect is enough for me to basically never play it any more). This would be easy to implement and do some good for the world.

**Comment by tanujnotes** [comment]
Out of scope.
