### ISSUE TITLE
Question? When Gesture Navigation is enabled use the left/right back navigation gesture to open the app shortcut instead.

### ISSUE THREAD

**Issue by topsy-turvy99** [tanujnotes/Olauncher#221]
When Gesture Navigation is enabled use the left/right back navigation gesture to open the app shortcut instead of direct left/right Gesture on the main page?

Reason: it'll lead to less Accidental opening of the gesture shortcut apps, i personally turned it off for this reason.

Is it feasible to auto switch to when Gesture Navigation is enabled?

Or other option i can think of is to add a toggle to either use the back gesture or direct gesture on homescreen.

**Comment by topsy-turvy99** [comment]
Wow, the ticket got closed faster than i could think off 😅, i guess i asked or suggested wrong features for the Launcher

**Comment by tanujnotes** [comment]
There's nothing wrong with it. It's just not a priority. There are already multiple open tickets with bugs reported and  enhancements. I'd prefer to work on them first whenever I have time.

If you're willing to contribute, you're more than welcome. Look at the issues with bug/enhancements tag.
