### ISSUE TITLE
Tap on date do not open calendar

### ISSUE THREAD

**Issue by Npa972** [tanujnotes/Olauncher#223]
Tap on time open alarm (simple-clock)
Tap on date do nothing (with one calendar). I do not try with others calendars (simple-agenda...).

Thanks you this app is great !
Keep it simple please !

**Comment by tanujnotes** [comment]
Which phone, Android version and calendar app you're using?

**Comment by Npa972** [comment]
Redmi 9C, android 11, one calendar
Thank's

**Comment by Npa972** [comment]
Thanks'you !

**Comment by tanujnotes** [comment]
You can now (v4.0.6) long press on time and date to select which clock and calendar apps to launch.
