### ISSUE TITLE
Google Calendar Integration 

### ISSUE THREAD

**Issue by pvcodes** [tanujnotes/Olauncher#224]
Hey! The launcher is Minimal snd good AF! 
but the google calander integration would a alot more handy. By the way this integration is inspired from another launcher called 'niagara launcher` in there pro version they have integrated the google calander, which show the upcoming event/reminder and stuff.

Also, I would like to help during the integration!

**Comment by tanujnotes** [comment]
This is not planned at the moment. Maybe in the future.

**Comment by pvcodes** [comment]
> This is not planned at the moment. Maybe in the future. 

Okay! Can I fork it, and give it a try?

**Comment by tanujnotes** [comment]
Sure. Feel free to post here once you're done. I'd love to take a look.

**Comment by pvcodes** [comment]
Yup! I'll get back to you soon!

**Comment by Ilithy** [comment]
Hi;
If I may say so, [Olauncher CF](https://github.com/jooooscha/Olauncher) includes the possibility to choose the calendar application, if you want to avoid doing a job already done ;-)

Have a nice day

**Comment by pvcodes** [comment]
🥲

**Comment by pvcodes** [comment]
> Hi;
> If I may say so, [Olauncher CF](https://github.com/jooooscha/Olauncher) includes the possibility to choose the calendar application, if you want to avoid doing a job already done ;-)
> 
> Have a nice day

🥲

**Comment by Ilithy** [comment]
@pvcodes I don't want to restrict you, if you want to code it, please yourself <3

**Comment by pvcodes** [comment]
> @pvcodes I don't want to restrict you, if you want to code it, please yourself <3

Maybe not, when it didn't know that that feature is not implemented, that gave me  the energy to do that, but now I'll already been done and I know that it's been done. I'm lazy again.

Hopefully, I'll think of some diff feature or something to get back on it!

PEACE!

**Comment by pvcodes** [comment]
@llithy, BTW the download is failing from f-driod, it says `the apk doesn't exit`

**Comment by Ilithy** [comment]
Really very strange, for my part no problem, here are two captures taken from my pixel (Store: Neo droid), I just updated it, and everything is normal
![Screenshot_20220901-095919](https://user-images.githubusercontent.com/36798218/187863934-479da31e-4421-47a7-a4f9-08aff0a990a4.png)

![Screenshot_20220901-100120](https://user-images.githubusercontent.com/36798218/187863969-d6a19237-6641-42b9-a620-63991193c909.png)

Sorry for the French screenshots

**Comment by pvcodes** [comment]
@Ilithy yeah! It's working now. But there is no google calander integration (i.e., on home screen, it shows the today's event/reminder fetched from google calander).

**Comment by Ilithy** [comment]
Ha you want deep integration...
It seems complicated to me given the minimalist design of the launcher, no? In any case, sorry for misleading you 🙏

**Comment by pvcodes** [comment]
Naah, it's fine. I wasn't able to clear it in the first place. Secondly, the integration can be a complicated and tricky part, but result would be a lot helpful, according to me.
