### ISSUE TITLE
bang issue

### ISSUE THREAD

**Issue by bastschonet** [tanujnotes/Olauncher#227]
Hi, the bang feature is great..., but if an app is installed containing a bang in its name this feature will not work.

Example: the app "Refous!"

If i swipe up, insert a "!" the app Refocus! starts immediately. No chance to use the bang feature.

Suggestion: ignore the bang for launching an app...?

**Comment by seven58o** [comment]
Same with Lose It! calorie counting app. Meant to mention this awhile back, actually.
