### ISSUE TITLE
[Feature request] Rename appdrawer apps.

### ISSUE THREAD

**Issue by benggc** [tanujnotes/Olauncher#236]
Hello, I wanted to start the post with a big thank you to all the authors.
This app is a amazing and (FREE!) tool that can help you regain control over the time spent on the phone without paying (tons of $) for a "smart-dumb phone".

I'am currently using the launcher with no start screen apps, so if I only need to set an alarm or check time to not be tempted. I only miss one feature in the app: rename apps in app drawer. Some applications have silly names and it would be amazing to rename it even for the pure sake of aesthetics! Or maybe If you want to add another obstacle to turning that app you have to type it!( which in opposite it make's running the apps faster than typing them by hand!).

Is this feature planned in the future?

**Comment by tanujnotes** [comment]
This will most likely require an in-app database. That'll complicate our rather simple app. For that reason, there's no plan to add this feature. I hope you understand.

**Comment by Ilithy** [comment]
@benggc 
If I may say so, [OlauncherCF](https://github.com/jooooscha/Olauncher) (fork of Olauncher), supports this feature (and several others), it may be useful for you.
