### ISSUE TITLE
Can't download daily wallpaper if is OFF

### ISSUE THREAD

**Issue by hctorres02** [tanujnotes/Olauncher#237]
Currently, there is no way to download the daily wallpaper if the option is not ON.

However, sometimes daily wallpaper doesn't please and there is no option to recover the previous one or predict which one will be applied.

**Comment by tanujnotes** [comment]
Yeah those limitations are there for various reasons. The best you can do is download the wallpapers you like and use them later when you don't like the daily wallpaper. Solving the issues you mentioned is out of scope.
