### ISSUE TITLE
Recent apps switcher

### ISSUE THREAD

**Issue by francisferras** [tanujnotes/Olauncher#238]
Hey Tanuj,

I’m using your app for a few days and I am enjoying it.

Nevertheless there’s something that is nerve racking. 
Swiping the menu button up shows me all the open apps. Then I can swipe left and right to kill them or change between them.

However now with your app I can’t swipe left and right. They don’t show up except the one you’re using. 

The turnaround is that  I can click on an empty space next to the visible app. It allows me to change app.. but is really tricky.

Thanks for your work!

**Comment by tanujnotes** [comment]
Hi Francis, can you download any other launcher and let me know if the issue exists with other launchers as well or just Olauncher.

**Comment by francisferras** [comment]
Hello Tanuj,

I've downloaded other launchers and it happens also with these new apps.
I guess is my costum rom issue!?

Any idea why?

Thanks in advance.

Francis

**Comment by tanujnotes** [comment]
Android in general is not very kind to third party launchers. Various issues are there related to recent apps and gesture navigation. It's an OS level issue so can't be fixed with by app devs.
