### ISSUE TITLE
[Feature Request] Simplify Settings Page Aesthetic

### ISSUE THREAD

**Issue by ixxie** [tanujnotes/Olauncher#239]
First of all, thank you for building and maintaining this amazing piece of software for free! :pray: I really appreciate what this launcher has done to my focus and well being.

The aesthetic in the app is amazing; perfect minimalism. So why does the settings page have these darkened background overlays? Do they serve a purpose? They seem to divide the setting page into segments, but the subheadings already perform this function. My request: simply remove the background overlays.

**Comment by tanujnotes** [comment]
They increase the contrast between the texts and background wallpaper making it easier to see smaller fonts in settings.

**Comment by ixxie** [comment]
In that case, how about making the overlay simply cover the whole background instead of making them boxes?

**Comment by tanujnotes** [comment]
Why?

**Comment by ixxie** [comment]
I guess I cannot really make any rational compelling argument; it is simply a preference of aesthetic simplicity, which is what attracted me to your launcher in the first place. But then again, its the settings page, so its not that big of a deal of course. I would totally understand if you would just dismiss the idea.
