### ISSUE TITLE
[Feature Request] Contacts Launcher

### ISSUE THREAD

**Issue by ixxie** [tanujnotes/Olauncher#240]
I would love it if Olauncher included features for navigating and maybe even managing my contacts. I know this is a big request and not a trivial change.... so why on earth should Olauncher do this? 

I think the amazing thing about Olauncher is the sense of focus it brings to the use of my phone. Often, I would want to contact someone. Depending on the person, I would need to use a different app to do so. Contacts apps often show you how you can reach a person (e.g. WhatsApp, Telegram, Signal, Email, etc). But these contact apps often suffer from clutter and distraction. Likewise, opening the chosen app in order to select the person is another source of distraction: I see other messages and notifications.

If Olauncher had native contacts support, I could extend it's focus to reaching out to my contacts. I would select my contact from a simple list - swipable from the launcher home - and then select my mode of contact (call, message, app, whatever) from a simple list again.

I know this is a big one, but consider this one vote in a direction to take in case you are looking for a bigger project.

**Comment by Aerolome** [comment]
yeeeeeeeeeeeeeeah i guess this is more for a fork

**Comment by tanujnotes** [comment]
Sorry but there's no plan to implement anything like this for now.
