### ISSUE TITLE
Add option to disable automatically launching an app if there is only 1 search result

### ISSUE THREAD

**Issue by SeriousBug** [tanujnotes/Olauncher#242]
When searching for apps, if there is only 1 search result, that app is immediately launched.

It would be nice to add an option so this can be disabled. It can be a little jarring, especially if you make a typo and launch an app you didn't mean to.

**Comment by tanujnotes** [comment]
This is has been discussed before. There's no plan to add option to disable this feature. I understand that it can be inconvenient at times but positives far outweigh the negatives. So we're keeping it as it is.
