### ISSUE TITLE
[Feature Request] AMOLED Mode

### ISSUE THREAD

**Issue by MatiasMFM2001** [tanujnotes/Olauncher#243]
Hi!

I suggest a new `OLEDark` theme. It's already possible to get it manually:
1. Olauncher settings:
    1. Theme mode -> Dark
    2. Daily new wallpaper -> Off
2. Android settings: Set your wallpaper to an image which only has black pixels (RGB `#000000`)

But it would be awesome to enable it directly from Config panel, instead of doing my steps

Goodbye!

**Comment by tanujnotes** [comment]
Hi, if you long press On/Off next to Daily new wallpaper, you can have a black wallpaper. For complete feature list, please visit the About page in settings.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/243#issuecomment-1279897070

@tanujnotes, but why hide the option behind a long-press? That's awfully unintuitive.
