### ISSUE TITLE
Google app "Add to homescreen" not working

### ISSUE THREAD

**Issue by azsch** [tanujnotes/Olauncher#246]
On the Google app, there is an option to add weather to homescreen. This does nothing in Olauncher.

![Screenshot_20221027_125305_Google](https://user-images.githubusercontent.com/116802219/198266343-77a1d2c0-98ca-4e16-8e40-784bdad8cdcc.jpg)

**Comment by pratikkabade** [comment]
Olauncher only has apps.
That's why you can't get that shortcut on olauncher homescreen.

**Comment by tanujnotes** [comment]
Olauncher does not support widgets or shortcuts.
