### ISSUE TITLE
Close all apps on "recent apps" screen

### ISSUE THREAD

**Issue by novalore** [tanujnotes/Olauncher#247]
The "recent apps" screen displayed when the user touches the square button only includes one icon (screenshot). It would be very useful to have also a "close all apps" button. This functionality is present in most launchers and many users are used to it.
I would appreciate this feature very much

**Comment by tanujnotes** [comment]
Hey, Olauncher does not affect recent apps screen in any way. Android is controlling it. Is the problem only with Olauncher or any other downloaded launcher on your device?

**Comment by novalore** [comment]
Only other launcher on my phone is quickstep and when I use it a "clear all" link is displayed.
I thought it was launcher-dependent

**Comment by tanujnotes** [comment]
Sorry but I'm not sure how I'll go about fixing this issue because as I mentioned above, Olauncher does not touch recent apps screen. Some people have complained about similar issues but it's almost always phone/OS dependent.
