### ISSUE TITLE
Feature Request: Add rename app feature

### ISSUE THREAD

**Issue by nett00n** [tanujnotes/Olauncher#249]
I use some apps with not Latin names. [^1]

It's not very convenient to search on both languages and remember on which language app is named.

It would be great if I could to give the own names for apps or add tags for them.

Also, [Google Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.maps) and [Yandex Maps](https://play.google.com/store/search?q=yandex%20maps&c=apps) have the same display name "Maps" and there is no option to identify which one is presented [^2]

[^1]: Picture 1
![photo_2022-11-01_13-08-14](https://user-images.githubusercontent.com/1846116/199210594-e5de047c-9e9a-426c-8992-038e3e6ed2be.jpg)
[^2]: Picture 2
![photo_2022-11-01_13-17-14](https://user-images.githubusercontent.com/1846116/199211929-9fdcb87b-ea46-446f-95ee-d2fedd167a61.jpg)

**Comment by jooooscha** [comment]
Since Tanujnotes does not seem to respond, I want to show you my launcher forked from this one called [OlauncherCF](https://github.com/olaunchercf/olaunchercf). My version does support this feature for several versions now.

**Comment by seven58o** [comment]
According to this post from 2 days ago... You can. Not true? 

https://github.com/tanujnotes/Olauncher/issues/245#issuecomment-1299990220

![Screenshot_20221104-062937](https://user-images.githubusercontent.com/31391748/199951754-ec9f1d46-4b24-462e-bb3b-4e13e479d19f.png)

**Comment by tanujnotes** [comment]
You can rename home screen apps but not app drawer apps. Check out the About page in Olauncher settings for complete feature list.

**Comment by metaldudu** [comment]
> You can rename home screen apps but not app drawer apps. Check out the About page in Olauncher settings for complete feature list.

after the application lists shown, just press top of screen then input new name, then press 'rename' right. 
it affects the app your longpressed

**Comment by JacksonCampbell99** [comment]
Replying to the main post, I have many apps with duplicate names and even some with 3 apps with the same name. You just learn which is which. Many Samsung and Google apps have the same name. Almost all the Samsung one comes first. You could alternatively look at your phone's default launcher and look at the order of apps in the app drawer.

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/releases/tag/v4.0.0
