### ISSUE TITLE
Bold font?

### ISSUE THREAD

**Issue by cassidyjames** [tanujnotes/Olauncher#25]
I love Olauncher, but I was wondering if you'd consider using a bold/heavy font weight by default—or at least allow choosing a font weight. The left alignment combined with a bold font would give a nice [Swiss Style](https://en.m.wikipedia.org/wiki/International_Typographic_Style) typographic look. 

It could also make it easier to read for some folks, especially depending on their wallpaper.

**Comment by tanujnotes** [comment]
Given who you are, I feel like I should just do whatever you suggest. 

I'll experiment with different font weights, show it around and whichever gets highest votes or makes most sense, will make it in the next update. Thank you very much for the suggestion.

**Comment by dar5hak** [comment]
And Roboto being a neo-grotesque sans serif makes it all the more Swiss.

**Comment by tanujnotes** [comment]
I have changed the font weight to what default Android offers. It looks good and visibility improves significantly. Although I have started getting emails saying they loved the thinner font. Let's see how this goes. Thank you for the feedback.

**Comment by dar5hak** [comment]
The visibility has indeed improved, especially against noisy wallpapers (but I'm sure that's a combination of this and #22).
