### ISSUE TITLE
Feature Request: App list alignment

### ISSUE THREAD

**Issue by nett00n** [tanujnotes/Olauncher#250]
There is only start screen alignment option. [^start-screen-alignment]

It would be great to have alignment options for app list too [^applist-alignment]
[^start-screen-alignment]: ![photo_2022-11-01_16-22-34](https://user-images.githubusercontent.com/1846116/199243545-55c6ab3b-b646-47d2-8309-b9ac57196e9a.jpg)
[^applist-alignment]: ![photo_2022-11-01_16-22-34 (2)](https://user-images.githubusercontent.com/1846116/199243550-ad7df155-cedb-4c6a-84c3-84dc83240501.jpg)

**Comment by tanujnotes** [comment]
Long press on Left/Center/Right in the settings to change the alignment in app drawer. 

Check out the About page in settings for complete feature list.
