### ISSUE TITLE
swipe to search for chromium based browsers is broken in Android 12+

### ISSUE THREAD

**Issue by paerbac** [tanujnotes/Olauncher#252]
When I set swipe to search to the brave browser (or chrome for that matter), it opens up a new window/instance of the app every time in android 12+. This does not occur when using the app from the home screen list or in the drawer. This would be fine if there wasn't a maximum instance count of 5 for chromium based android browsers, but because of this limitation, if I don't clear the browser instances, after swiping to search five times, it will not allow me to swipe to search and send an error message saying only five windows are allowed at a time. This could be fixed either by having the swipe to search. Use the widget implementation of search from chromium base browsers or if you allowed swipe down to search to just launch the app in the regular way, but whatever implementation olauncher is using to launch the search on chromium browsers is causing a new instance to be opened each time.

**Comment by paerbac** [comment]
The window/instance feature that the swipe feature is conflicting with is explained here; https://www.ghacks.net/2021/08/24/google-chrome-will-support-a-multi-window-experience-for-android-12/

**Comment by tanujnotes** [comment]
I tested this on Android 12 & 13 with Brave and other search options. I could not replicate the issue. This could be a device or app version specific issue.
