### ISSUE TITLE
Add app aliases (or edit app names)

### ISSUE THREAD

**Issue by jondrews** [tanujnotes/Olauncher#253]
I realise your FAQ says that app name editing isn't planned... But things can get quite confusing when we hide the app icons: Some apps have identical names to others (eg, Google Photos and the android stock photos app both display as "Photos"). Other apps have names that aren't memorable or appropriate.

Being able to add an alias (eg "Google Photos" or "Android Photos") would make for a much simpler experience. 

Just editing the app name, like you can do with the homescreen app shortcuts, would be even cleaner.

**Comment by tanujnotes** [comment]
Duplicate #249
