### ISSUE TITLE
Feature request: URL as selected app

### ISSUE THREAD

**Issue by Lars-** [tanujnotes/Olauncher#254]
I personally use a lot of systems that unfortunately only work in the browser.
It would be cool if it would be possible to enter a URL instead of selecting an app to display on the home page.

**Comment by tanujnotes** [comment]
Enter a url where?

**Comment by Lars-** [comment]
Well, you can select apps now by holding the app on the homescreen and then selecting an app. Instead of selecting an app, it would be extremely handy if I could link to a URL. So it opens that URL in whatever browser you normally use instead of a regular app.

**Comment by tanujnotes** [comment]
Sorry but this is out of scope. You can pin webpages on most browser's homepage. Maybe try that if you haven't already.

**Comment by Lars-** [comment]
That is indeed my workaround. Thank you for your response, have a nice day!
