### ISSUE TITLE
Feature Request: App name Aliases

### ISSUE THREAD

**Issue by arran-nz** [tanujnotes/Olauncher#258]
A problem arrises when you install a new app with a similar name as an existing app, therefore breaking muscle memory when opening said app.

I propose OLauncher allows the user to set an optional alias for each app.

For example, for "F-Droid" an alias could be added, "fdd" which would allow the user to quickly find apps without dealing with conflicts from similar app names.

**Comment by ashrafimostafa** [comment]
may i working on this feature request?

**Comment by tanujnotes** [comment]
@ashrafimostafa Sure. But first, please show us the design/UI of how it'll look and what the user flow will be. UI doesn't have to be perfect but the user flow has to be as simple and clean as possible.

**Comment by ashrafimostafa** [comment]
@tanujnotes sorry for delay in response. I think about to two general ideas the first one is open a minimal bottom sheet after long press on application name, and show this option in bottom sheet:
1. hide app(which is currently is available in app long press)
2. app setting(which is currently is available in app long press)
3 app usage (open phone default wellbeing setting that show the user app usage )
4. text box for app alias and a switch next to it that let the user to enable that app can be find only with it alias or both app name and alias.

the second idea is is to add alias text next to hide(after app long press), by clicking on alias an dialog with edit text open and so on.


let me know about your idea.

**Comment by tanujnotes** [comment]
@ashrafimostafa To use bottom sheet, some material library will be added which will increase the apk size. It's not a big deal but I'll avoid it if I can.

**Comment by tanujnotes** [comment]
Updates on #249
