### ISSUE TITLE
notifications and widgets

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#259]
Is it possible in the next update to have the number next to the app name when a notification arrives? Example: "Whatsapp 1", "Messages 2" on whatsapp there is one notification and on messages there are two notifications. Would it also be possible to swipe left on the main screen to have a page dedicated to Widgets? Could these additions be inserted without weigh down the launcher?

**Comment by tanujnotes** [comment]
Check the public roadmap in Olauncher settings for upcoming features. No plan for notifications though.

**Comment by refaelsh** [comment]
> Check the public roadmap in Olauncher settings for upcoming features. No plan for notifications though.

I can't find `roadmap` in Olauncher's settings. Please advise.

P.S.
I am also interested in Widgets.
