### ISSUE TITLE
Add mapping to home button

### ISSUE THREAD

**Issue by fatings** [tanujnotes/Olauncher#260]
Clicking the home button while at the launcher does nothing, which wastes a possible interaction that doesn't mess with the UI.

**Comment by tanujnotes** [comment]
What do you want it to do? Suggestions are welcome. And if there are other launchers which are doing something similar, please point me towards them.

**Comment by fatings** [comment]
I would suggest being able to launch an application.
Nova has this:
![Screenshot_2022-12-01-12-21-48-81_3822ac0e29cfec8970059bb21d01f05e](https://user-images.githubusercontent.com/39002567/205051671-8a4cf29f-76f5-453f-a3e3-62a916a61d41.jpg)

**Comment by t0kvgh** [comment]
I'm using a Samsung phone,  hold home  button will trigger a system action.  I just hope this feature does not conflict with system behavior.

**Comment by fhinok** [comment]
I suggest that the home button opens the app drawer, so swipe up could be used to launch any app

**Comment by fhinok** [comment]
> 

or open a search view whicht finds apps, contacts and settings. for example lynx launcher allows to do this
