### ISSUE TITLE
Searching system settings

### ISSUE THREAD

**Issue by codeinabox** [tanujnotes/Olauncher#267]
One feature that I miss from Action Launcher that I'd love to see in this app is the ability to search system settings eg "battery" would bring up the battery settings

**Comment by codeinabox** [comment]
Out of curiosity if I wanted to implement this feature myself, would you accept a pull request?

**Comment by tanujnotes** [comment]
Yes, that'd be great. But it can not interfere with the default app search and auto-launch.

One way this can work is how bang search currently works in Olauncher. If you start the app search with "!", auto-launch gets disabled and pressing enter on keyboard redirects you to duckduckgo search in browser. Maybe you can use the "!" for searching settings as well.
