### ISSUE TITLE
[Feature Request] Backup/restore Settings to json, xml or csv

### ISSUE THREAD

**Issue by The-Repo-Club** [tanujnotes/Olauncher#273]
- [X] I have searched existing issues for this feature.

#### Motivation behind feature

Move settings from one system to another easily as well as needing to reinstall the app.

#### Proposed Feature

Backup of the settings in the app into a json xml or csv file so it can be used to restore at a later time

**Comment by tanujnotes** [comment]
https://developer.android.com/guide/topics/data/autobackup
Olauncher already supports Android's default data backup/restore if it's on in your phone settings.  Anything more than that is out of scope.

**Comment by The-Repo-Club** [comment]
`android:allowBackup` is not enabled in this app.

**Comment by tanujnotes** [comment]
https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

Oh, thank you for pointing it out. Seems like it's on by default but I'll add it just to be safe.
