### ISSUE TITLE
Calenders not launched as regular app when opened from the date

### ISSUE THREAD

**Issue by rcheetah** [tanujnotes/Olauncher#274]
When opening the Calendar by tapping on the date, the app is launched in some kind of overlay mode. 
What I mean by that is, that it is not opened as an app. It is not in the multitasking menu, and when leaving the window, the current state is not saved.

In my case I have set Business Calendar as my default calendar. When I tap on the date to open the app, and then start adding a new appointment and switch to a different app while doing so (e.g. to copy something or check for details in WhatsApp), I can't switch back to the calendar. Also when I enter the calendar app again by tapping on the date, it is launched as a new instance, and the previous state is forgotten (so the new appointment is not saved, and I can't go back and save).

This behavior is different with the clock app. If I start the clock app by tapping on the time, the app is launched normally, and visible in the multitasking window. Also if I start Business Calendar as an app (from the app list or as a shortcut on the launcher home) then everything works normal. It's just if I start it by clicking on the Date.

Sadly, I'm no android developer. I don't know what happens here, but I guess it's some kind of different way of opening an app (as an overlay or a modal or something like that). It's similar when for example you are in an app and you click an email address. The you will be forwarded to you email app, but often in some kind of lose state, where the app is only open from within the first app. And you can't switch between the first app and the email app 

Do you have an idea what's wrong here? It would be nice to have less items on the app list and still use the calendar. But this is totally workaroundable by adding the calendar as an app to the start screen. Nonetheless it's annoying ^^

**Comment by The-Repo-Club** [comment]
hey i just did this on my Pixel 7 and it works as an app itself to open Google Calendar maybe its the app you use not Olauncher doing that?

**Comment by rcheetah** [comment]
Oh, yes I tested it with a different calendar app, and this one works. Though it still works with the app on the homescreen, but not with the date. Are these handled differently, so does the date use a different system call than the app on the homescreen? If so, I can issue this to the Business calendar, but I need to be able to name the problem.

**Comment by tanujnotes** [comment]
I did some quick search and there's not much that can be done about this. It depends on device and how the individual calendar apps handle the request.

**Comment by tanujnotes** [comment]
You can now (v4.0.6) long press on time and date to select which clock and calendar apps to launch.
