### ISSUE TITLE
Add Weather to Home Screen

### ISSUE THREAD

**Issue by Bailey-Moir** [tanujnotes/Olauncher#275]
It would be very helpful to add a weather button to the home screen. It could be below/above the date and it could be enabled in 'Appearance'.

**Comment by Minibus93** [comment]
I'd really like this too, so while I understand, as #145 stated, that it may be out of Olauncher mind, I feel this should be considerated

**Comment by evanlesmez** [comment]
Definitely would be useful. Lunar launcher does it ok, but you need a OWM API key and must enter city.
