### ISSUE TITLE
Feature request: battery indicator when statusbar hided 

### ISSUE THREAD

**Issue by kotleni** [tanujnotes/Olauncher#277]
When you turn on full screen mode, you can't see battery percentage, it's very annoying.

**Comment by Heike-HS** [comment]
It is rather a feature than a bug that even no battery indicator is shown when status bar is hidden. So, please add this only as an option.
Heike

**Comment by tanujnotes** [comment]
Too many people have asked for this too many times for too long. Apologies for the delay everyone.

It's finally arriving. Battery % will only be visible when status bar is hidden. This is what it'll look like:

![IMG_20230110_193528](https://user-images.githubusercontent.com/11060605/211573730-d4b7e4e5-059a-44f5-be05-e813927248a8.jpg)

**Comment by kotleni** [comment]
@tanujnotes, Thx u

**Comment by tanujnotes** [comment]
@joelostblom I understand what you're saying. In fact, that's the reason why I took so long to add this. Luckily, so far almost everyone seems to be okay with this change so I guess it will stay the way it is. Please give it some time. You'll most likely get used to it.

**Comment by omomom666** [comment]
> @tanujnotes Would you consider making this behavior optional? I am using olauncher because it is minimal and features like mandatory battery percentage adds visual noise which I feel is the opposite of the spirit of olauncher (as I understand it at least). I don't need to see my exact battery percentage each time I look at my home screen and I like that it is a calm place with just a few apps and the time, so I think an option to turn this off would be helpful.

I'm with you. I don't think this is an good change. It is a step away from the minimalistic look and fell and for me it doesn't add anything. It should be optional in my opinion.
