### ISSUE TITLE
Typing could already start searching

### ISSUE THREAD

**Issue by aggsol** [tanujnotes/Olauncher#28]
It would save the swipe up. The superflous motion moves the thumbs away from the keyboard and is distracting. (see KISS launcher how search and keyboard are handled there for inspiration)

**Comment by tanujnotes** [comment]
But typing already starts searching. Here's how it currently works - you swipe up, app list and keyboard appear, start typing and it will start searching the apps, or, scroll the app list and keyboard disappears. If there's anything that's not working exactly as I mentioned, please let me know.

**Comment by aggsol** [comment]
I think I phrased it wrong. When I swipe up I change into the search view. I would want the first character to already go there without swiping up when I start typing in the first vie with the four shortcuts.

**Comment by tanujnotes** [comment]
That might require significant work and since most users already love the existing design, I'm more interested in using my time to fix some serious issues I got to know about in last few days. I hope you understand. Thank you.
