### ISSUE TITLE
"About" page is marked unsafe by Notion

### ISSUE THREAD

**Issue by TheOnlyGhostwolf** [tanujnotes/Olauncher#283]
Hello!
It seems like the [About page](https://tanujnotes.notion.site/tanujnotes/Olauncher-Minimal-AF-4843e398b05a455bb521b0665b26fbcd) for the launcher has been marked unsafe by Notion.

![Screenshot_2023-01-17-13-46-40-062-edit_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/31188082/212891077-d682fee3-6794-40a3-a3bd-7b828e14f647.jpg)

**Comment by tanujnotes** [comment]
This is fixed. Thank you for letting me know.
