### ISSUE TITLE
Apps list (swiping up) is empty for ~5 seconds after unlocking the phone 

### ISSUE THREAD

**Issue by pauleks** [tanujnotes/Olauncher#284]
Hello!

I'm experiencing an issue, where the apps list sometimes stays empty for a few seconds after unlocking the phone. Is this an expected behavior or could this be an issue with my phone's manufacturer's OS?

![Screenshot_2023-01-17-13-41-34-763_app.olauncher.jpg](https://user-images.githubusercontent.com/31188082/212891626-505e4c98-dd38-4936-bafc-09e57b97c947.jpg)

I use Xiaomi Redmi Note 9, with MIUI Global 13.0.3 (Android 12), Olauncher version 3.6.4

**Comment by tanujnotes** [comment]
Is this still happening in the latest update?
