### ISSUE TITLE
Settings menu wouldn't open on a long press as it used to

### ISSUE THREAD

**Issue by gabops** [tanujnotes/Olauncher#285]
Hi,

Thank you for Olauncher, it is great! The reason for opening this is because after a recent update, I've started to have an issue by which I cannot open the settings menu after a long press anywhere on the screen. The app simply crashes and the system shows a "Olauncher keeps stopping" message.

My phone is an OPPO Find X5 with Android 13.

If you need any more information, please let me know.

**Comment by tanujnotes** [comment]
Have you tried the latest version?

**Comment by gabops** [comment]
Hi, @tanujnotes 

Yes, I've tried and works as expected now. This issue can be closed. Thank you for your fix!
