### ISSUE TITLE
Double tap to lock not working with newest Android update

### ISSUE THREAD

**Issue by Darkmaster006** [tanujnotes/Olauncher#288]
Hello, I would like to report this new bug I found. I already tried reinstalling the app, turning the phone on and off, turning the feature on and off, turning battery optimization on and off, is there anything else I can try? Double tap to lock does not work since I updated Android to the latest version, which is  13, with One UI 5.0, in Samsung Galaxy A33 5G.
Software: A336MUBU4BVL1 / A336MOWO4BWA1 / A336MUBU4BVL1.
Double tap to lock does work with the default Android launcher.
Thank you for your work! Hope I can help in any way to fix it, let me know.
Double tap to lock worked when I'd not yet updated. I also have no protection at all (when I press to show my screen it just starts in Olauncher).

**Comment by tanujnotes** [comment]
I'm using One UI 5 and unable to replicate this issue. If reinstalling hasn't fixed this issue, I don't know what will.
