### ISSUE TITLE
Google Fit misaligned on home screen

### ISSUE THREAD

**Issue by dar5hak** [tanujnotes/Olauncher#29]
I right-aligned the icons and they look fine, except for Google Fit, which has extra gap on the right. It looks okay when left-aligned.

![Screenshot_20200923-200647.png](https://user-images.githubusercontent.com/8205055/94027701-c0f0ef00-fdd8-11ea-9a68-55d10c11c86d.png)

**Comment by hltbrg** [comment]
Seems to affect all apps with short names

**Comment by tanujnotes** [comment]
@hltbrg Can you please give some examples? I want to test it on my device and see if I can do anything about it.

**Comment by dar5hak** [comment]
@tanujnotes I tested for Docs, Meet, Lens and VLC. The gap is there but it's less than that of Fit.

One thing I observed is that all short names start from the same left position.

![Screenshot_20200924-102455.png](https://user-images.githubusercontent.com/8205055/94102784-92165f80-fe50-11ea-9c4b-f77e86cf6ca6.png)

This probably means that the activity allocates a minimum width to each app and then aligns them to left inside that.

Because this also happens with the centre-align option.

**Comment by tanujnotes** [comment]
Ohhh... That probably explains it. I might have set a minimum width for smaller app titles earlier when apps were only left aligned, to make it easier for users to click. It's a quick fix. Thank you very much.

**Comment by tanujnotes** [comment]
Nope. I was wrong. There was no minimum width. This was something else.

**Explanation**: When you open app for the first time, you see a text hint 'Select' to choose your home apps. When you choose 'Fit' or 'VLC', you see the app name. Today, after 4+ years as an Android developer, I found out that text hint also plays a role in text view width. Since 'Select' is wider than 'Fit', minimum text width of the home apps is decided by 'Select' and not the actual app title.

There are a few ways to fix this. I just replaced the text hint 'Select' with 'App'. :)

**Comment by dar5hak** [comment]
Whoa, that's interesting to know. Glad you found a fix.

At the risk of playing the Devil's advocate, how will the newly rebranded Vi behave in this case?

**Comment by tanujnotes** [comment]
Oh crap. I'll add a proper fix in future updates. For now this will have to do as there many high priority issues to work on.

**Comment by hltbrg** [comment]
Without knowing too much about front end, but is it possible to right align the text in all text views when having the apps right aligned? In that case the with can still be wider to have more area to press on.

**Comment by tanujnotes** [comment]
This sounds possible. I'll have to set alignment to each text and not just the parent layout but I think this is the most fool proof solution. I'll try it out. Thank you for the tip.

**Comment by tanujnotes** [comment]
This issue is finally fixed for good. Thank you guys for all the help.
