### ISSUE TITLE
Feature Request: Common or recent app

### ISSUE THREAD

**Issue by franz101** [tanujnotes/Olauncher#292]
Instead of manually defining apps.
Add a top1 / common / frequent / recent automatic app.
Something along the lines:
```
private fun showFrequentApps() {
    val usageStatsManager = getSystemService(Context.USAGE_STATS_SERVICE) as UsageStatsManager
    val endTime = System.currentTimeMillis()
    val startTime = endTime - TimeUnit.DAYS.toMillis(7)
    val usageStatsList = usageStatsManager.queryUsageStats(UsageStatsManager.INTERVAL_DAILY, startTime, endTime)
    usageStatsList.sortWith(LastTimeUsedComparator)

    val frequentApps = mutableListOf<String>()
    for (usageStats in usageStatsList) {
        if (usageStats.lastTimeUsed > startTime) {
            frequentApps.add(usageStats.packageName)
        }
    }

    // display the frequentApps list in your launcher
}
```

**Comment by tanujnotes** [comment]
For most people, these top apps will be social and other time wasting apps. I don't think it's a good idea to show these apps on the top in app drawer.

**Comment by franz101** [comment]
Created a PR, curious on feedback on the code. If you don't see it as useful, will just use it for my personal use.

**Comment by tanujnotes** [comment]
Code looks fine but I won't be able to accept the PR. Maybe you should create a fork, in case others are interested in this feature.
