### ISSUE TITLE
Locking phone while viewing multitasking doesn't correctly return to home screen

### ISSUE THREAD

**Issue by alpha-tango-kilo** [tanujnotes/Olauncher#295]
Not sure if this is an Android or GrapheneOS specific thing, but when I lock my phone while in the task switcher, it returns to the home screen.

However, doing this with Olauncher doesn't render the home screen, just my wallpaper. The default GrapheneOS launcher shows my home screen as expected.

Before locking:
![multi tasking](https://user-images.githubusercontent.com/12728900/217609609-f23874b5-dfd1-4173-8de0-7e9ea88fa24c.png)

After unlocking:
![blank homescreen](https://user-images.githubusercontent.com/12728900/217609626-8d190bf2-1263-4600-98de-325ad0b443b6.png)

Pressing the home or back button gets things back to normal.

As with all 'fun' bugs, this doesn't happen 100% of the time, but maybe 90% of the time

**Comment by tanujnotes** [comment]
In 2 phones that I tested, if I open recent apps then lock-unlock the phone, I still see the recent apps screen. This might be a device or Android specific thing. It doesn't seem like a big issue. Also, I can't replicate it so I won't be working on it.
