### ISSUE TITLE
Feature Request: PIN or password to prevent changes

### ISSUE THREAD

**Issue by timmrogers** [tanujnotes/Olauncher#296]
This application is almost perfect for my 92 year old mother-in-law. 

She finds her phone to be overwhelming, and cannot reliably use standard applications like Phone, Messages, and so on. Olauncher works very well for her.

However, I would like to be able to lock it such that she cannot accidentally make any changes to the configuration. Specifically, she sometimes long-presses on a menu item, and then chooses a different application. This is very confusing and frustrating to her.

If I could set a PIN (different from the unlock code for the phone) which appeared before any configuration option, that would be perfect.

Thank you very much!

**Comment by Conaclos** [comment]
An option to lock the menu in the settings could be enough?

**Comment by tanujnotes** [comment]
Adding such feature is out of scope for this launcher.
@timmrogers what I can do for you is provide a separate apk, where once you set the apps on home screen, it can't be changed. At least not without clearing data or reinstalling. Let me know if you want this.

**Comment by tanujnotes** [comment]
@Conaclos Sorry but there's no plan to add any new menu option.

**Comment by timmrogers** [comment]
That is very kind of you.

If you are willing to offer me a custom .apk, I'd appreciate it. Thank you!

(I understand that you have chosen not to add any more features to
Olauncher. I get it - but it does seem a shame. It is a great app, and
while I suspect that it does what you'd like it to do, it could be so
useful for other "use cases" with just a few additions and tweaks. But
perhaps someone else will choose to fork it.)

Thanks again.

**Comment by Conaclos** [comment]
@timmrogers 
You can propose the change to a fork of Olauncher such that [OlauncherCF](https://github.com/OlauncherCF/OlauncherCF) or [mlauncher](https://github.com/HeCodes2Much/mLauncher).

**Comment by timmrogers** [comment]
Helpful! Thank you - I'll check them out.

Thank you.

**Comment by tanujnotes** [comment]
@timmrogers https://drive.google.com/file/d/1hF_pnipGsiek5iKlndEAsM-bcMC4eebt/view
