### ISSUE TITLE
[Feature request] add an option to resize the app search bar and font size.

### ISSUE THREAD

**Issue by Waylander05** [tanujnotes/Olauncher#297]
![Screenshot_20230210-105815_Olauncher](https://user-images.githubusercontent.com/99947510/217997520-88cda09b-9c8a-4bc5-a284-c5843e9e9d18.png)
can we have an option to resize the app search bar? It takes some screen real estate, especially for smaller phone like the one I have.
adding an option to resize the app drawer font could also be helpful to reduce the amount of time scrolling on one hand.

I really like this app as it shaves off the amount of times I clicked on social media apps needlessly. I hope it adds a lot of customization in the future.

**Comment by tanujnotes** [comment]
Providing this level of customization is out of scope for Olauncher.
Also, I'd suggest to use the search to open apps instead of scrolling. It's generally more efficient even if it might take some time to get used to.
