### ISSUE TITLE
Bug with date and Time widget

### ISSUE THREAD

**Issue by akashpal-21** [tanujnotes/Olauncher#3]
Hi, there seems to be a bug where i am seeing time in both fields as opposed to date in one and time in another.
Screenshot for reference is attached.

Thanks

**Comment by akashpal-21** [comment]
#
![Screenshot_20200727-001510_Olauncher](https://user-images.githubusercontent.com/46517170/88487118-f06ab300-cf71-11ea-82c6-aaed5b7944c2.png)

**Comment by tanujnotes** [comment]
This issue exists on phones with 24-hour time format. Fixed. Thank you for letting me know.
