### ISSUE TITLE
Next update added battery percentage

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#300]
Hi, Launcher is a good launcher. In the next update is it possible to add the battery percentage next to the time and date? I await a reply. Thank you

**Comment by tanujnotes** [comment]
Battery percent is already there. It shows up only when you turn off the status bar in Olauncher settings.

**Comment by wbadart** [comment]
Hi @tanujnotes, is this the right place for a related feature request? I was wondering if it'd be possible to add a setting for toggling the battery display independently of the status bar setting.

**Comment by tanujnotes** [comment]
@wbadart Do you want to show or hide the battery percentage (regardless of the status bar)?

**Comment by tanujnotes** [comment]
At the moment I'm planning to add any such option. But I'll see if I can make any design changes so that it doesn't bother anyone.

**Comment by Livio78** [comment]
Thank you
    Il giovedì 2 marzo 2023 alle ore 20:27:24 CET, Tanuj ***@***.***> ha scritto:  
 
 


At the moment I'm planning to add any such option. But I'll see if I can make any design changes so that it doesn't bother anyone.

**Comment by tanujnotes** [comment]
I'm sorry I meant not planning to... 😬
