### ISSUE TITLE
Add external search results to Olauncher Search

### ISSUE THREAD

**Issue by antonselukh** [tanujnotes/Olauncher#301]
I would be nice to be able to delegate the text queries to:
1. internal android Settings search. It's possible from Google assistant, therefore it is possible from text search too
2. App Marketplace of choice (no need to make query, just have an option in the list to transfer the query to Google play store, or others)
3. Internet Search engine of choice (same as previous applies)

**Comment by tanujnotes** [comment]
1 and 2 are out of scope for Olauncher. But, if someone implements it in a way that it doesn't interfere with existing app search, I can consider it.
3. It already supports [bang search](https://duckduckgo.com/bangs). Type `!g something` and press the search button in keyboard.
