### ISSUE TITLE
some apps are hidden underneath keyboard 

### ISSUE THREAD

**Issue by original-taste** [tanujnotes/Olauncher#302]
https://user-images.githubusercontent.com/54194460/221316150-7d7b3c26-395b-4091-bf9c-1e2cb2b92cdb.mp4

if there just one app that is under the keyboard, and to see that app we swipe up, it doesn't show the apps. instead closes and goes to home screen

**Comment by tanujnotes** [comment]
Just press the back button to hide the keyboard for now. I'll get to it sometime in the future. It has been there for a long time. Almost no complaints so, low priority.

**Comment by original-taste** [comment]
yeah that can work.
