### ISSUE TITLE
Launcher switching to landscape mode

### ISSUE THREAD

**Issue by hudcap** [tanujnotes/Olauncher#307]
My launcher recently (past week?) started switching to landscape mode when I rotate my phone. I'm 99.9% sure this never happened before.
I'm not using Android 8 (which was reported in other issues).

Thanks for an awesome launcher!

**Comment by orestisfra** [comment]
Got the same issue. This must be a recent update for tablets or something. I didn't see anything in the release notes though. There should be a setting to lock/disable orientation. Let's hope for a quick response from the developer. Awesome work so far.

**Comment by tanujnotes** [comment]
@hudcap @orestisfra  From where did you get the update? Play Store, F-Droid or APK?

**Comment by hudcap** [comment]
Play Store for me

**Comment by tanujnotes** [comment]
I just checked. Looks like I have uploaded the wrong apk. It will be fixed in the next update, this week.
If yo don't want to wait, you can get the right apk from here: https://github.com/tanujnotes/Olauncher/releases

**Comment by hudcap** [comment]
Thanks for the quick response!
Not sure if you want to leave this open until the update, so I'll leave it up to you.

**Comment by orestisfra** [comment]
Since this is still open, I also confirm that I got the update from the play store.

**Comment by jackgreyhat** [comment]
I actaully like this feature :) would it be possible to make this configurable with a toggle in the settings menu?

**Comment by tanujnotes** [comment]
I also publish a landscape supporting apk with every release. Please check out Github releases.
