### ISSUE TITLE
Built in calculator?

### ISSUE THREAD

**Issue by jmhobbs** [tanujnotes/Olauncher#308]
What would you think of adding a simple, built in calculator?

Maybe if you started typing and it didn't match any apps, but did match a calculable expression it would do the math?

Or you could reserve any expression starting with `=` as being a calculation request. 

I love Olauncher, but it'd be nice to just pull down and do quick math instead of starting up calculator.  Maybe out of scope.

**Comment by tanujnotes** [comment]
This is out of scope for this launcher.
I like the idea but I don't think implementing a calculator where the input is in raw text format is a trivial task.
