### ISSUE TITLE
Parallel apps appear only once

### ISSUE THREAD

**Issue by a3y3** [tanujnotes/Olauncher#31]
**Issue**: Oxygen OS has a feature called [Parallel Apps](https://forums.oneplus.com/threads/parallel-apps.901248/) that allows certain apps to be run with multiple accounts. For example, for WhatsApp, the default Oxygen OS launcher displays two different apps with the same name, but different logos, to help distinguish between them.

However, OLauncher only displays a single entry for WhatsApp, and clicking that entry opens a System UI dialog to allow the user to choose between them. Although this works, it's not ideal, as the user is forced to wait for the System UI dialog to pop open and then choose the correct version of WhatsApp.

**Suggestion**: Display two different entries for the parallel app with a `(Parallel)` text next to the second entry to help differentiate between them.   

**Steps to Reproduce**: 
- Enable parallel apps in system settings on an Oxygen OS ROM
- Open the parallel app in OLauncher to see the System UI dialog.

**Device**: OnePlus 6
**Android Version**: 10

**Comment by tanujnotes** [comment]
Hi, I'm aware of the issue and I'm working on it. Thank you for your patience.

**Comment by a3y3** [comment]
Sorry to reopen this PR, but on the latest version of the app I still see WhatsApp twice. The second one has a dot before it.

However, clicking both of them opens the System UI dialog asking me to choose which version of WhatsApp to use. The intended behaviour would be to open the parallel version of WhatsApp on clicking the label with the preceding dot.

**Comment by tanujnotes** [comment]
I read somewhere that some phones do not allow third party apps to open dual apps normally. I have tried few launchers and I found it true for all of them. I need to know if this issue is fixable before I start fixing it.
