### ISSUE TITLE
Renaming apps affects work and personal versions at the same time

### ISSUE THREAD

**Issue by DavidEspinola** [tanujnotes/Olauncher#310]
Hi! First of all, thanks for this awesome launcher!

I'm using work profile and I have work and personal versions of some apps (for example Calendar). When I change the name of one of them, the other gets the same name automatically.

**Comment by tanujnotes** [comment]
Yeah this is expected because renaming uses package name, which is same for the same app in different profiles. Currently there's no plan to fox this but maybe in the future.
