### ISSUE TITLE
bug: renaming application does not display updated name on "Apps on home screen" listed name

### ISSUE THREAD

**Issue by bigpaulo** [tanujnotes/Olauncher#314]
You are allowed to rename application in the full application list, and it displays the updated application name correctly in that list, but the updated application names are not displayed on the "Apps on home screen" list, they remain the original unedited application name.

**Comment by tanujnotes** [comment]
This is expected. It's possible that people want a different name on the home screen. 

What you can do is set the app on home screen once again after renaming in the app drawer.
