### ISSUE TITLE
Document how to remove Apps from the shortlist 

### ISSUE THREAD

**Issue by tburny** [tanujnotes/Olauncher#317]
Hi I am using the latest version of OLauncher and so far it is really great!

However I accidentally added an app to the short list. Now how can I remove it from the list again to free up its slot?

I read all of the documentation and FAQ but I could not find any hints.

**Comment by tanujnotes** [comment]
You cannot remove it. You can only replace it. Long press on the app name on the home screen and select any app from the list.

**Comment by tburny** [comment]
Thanks for your help! Maybe this info can be added to the FAQ?

Q: How can I change/modify/remove entries from the short list?

A: Simply long press the entry you would like to change. This will open the list of all apps (similar to swiping up). Tap the app that you want to use instead and it will replace the previous one.


IMHO the behavior is a bit unclear / confusing. I though "oh it just opens the app drawer". Maybe it is possible to give users some kind of hint? Like "now choose the ones app"?

**Comment by tanujnotes** [comment]
A hint will be shown when the user long presses the home screen apps.
