### ISSUE TITLE
The number of "Apps on home screen"

### ISSUE THREAD

**Issue by shoti** [tanujnotes/Olauncher#318]
Hi. First things first, thanks for this project, it is excellent.

now about business )) It's not really an issue, but a question, is there any particular reason why the home screen apps maximum N is 8? imo would be nice to increase it, maybe just hardcoded (like 10-12 max?) or if there'll be enough time for this in a smarter way, like calculating screen size and offering optimal N of maximum apps. Thanks!

**Comment by tanujnotes** [comment]
The biggest reason - it's easier to maintain. More features equals more problems equals more complaints which I do not have time to deal with. Besides, it's enough for most people.
