### ISSUE TITLE
Feature Suggestion: Differeniate Work Profile and Normal User Profile Apps 

### ISSUE THREAD

**Issue by theunknowninfinite** [tanujnotes/Olauncher#320]
The launcher is pretty cool.I like it and have been using it as my primary launcher on my device.However I do have a feature suggestion that could be  helpful for others.It certianly would be for me. 
It would be great  if there was a way to differeniate work apps and normal user apps in the launcher. Maybe a different font style or some slight difference in how the apps are displayed for the work profile apps.

**Comment by tanujnotes** [comment]
There's already a small dot in front of work profile apps. No plan to make any further changes.
