### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#324]
In the next update, would it be possible to have the ITALIAN LANGUAGE? Thank you

**Comment by tanujnotes** [comment]
Planning to add translations soon.

**Comment by Livio78** [comment]
Thank you 
    Il domenica 23 aprile 2023 alle ore 22:26:29 CEST, Tanuj ***@***.***> ha scritto:  
 
 


Planning to add translations soon.

**Comment by noscirep** [comment]
@tanujnotes Is Swedish one of the languages you are planning to add? If not, I would be happy to translate Olauncher into Swedish.

**Comment by tanujnotes** [comment]
@noscirep Sure!

Anyone who wants to add their language, reply on this thread with the translations. This is the file with all the text to translate - https://github.com/tanujnotes/Olauncher/blob/master/app/src/main/res/values/strings.xml

How/what to translate:

You'll see lines like below in the file. Leave the key_word as it is. Translate 'What user sees'.
`<string name="key_word">What user sees</string>`

**Comment by Livio78** [comment]
Thank you, I hope the Italian language will be added as soon as possible. Again I thank the developer for this launcher.

**Comment by essy16** [comment]
> In the next update, would it be possible to have the ITALIAN LANGUAGE? Thank you

I have added Italian Language

**Comment by Livio78** [comment]
Thank you. Can you confirm that in the next update it will be possible to set the Italian language? Thank you
   Il sabato 20 maggio 2023 alle ore 11:01:25 CEST, Esther Cynthia ***@***.***> ha scritto:  
 
 



In the next update, would it be possible to have the ITALIAN LANGUAGE? Thank you


I have added Italian Language
