### ISSUE TITLE
Change Wallpaper Manually

### ISSUE THREAD

**Issue by Ganesh910** [tanujnotes/Olauncher#327]
A user enables "Daily New Wallpaper". But what if the user didn't like the new wallpaper? He has no option to choose another wallpaper. There must be some option to change the wallpaper or skip the wallpaper. We can have a separate portion for wallpapers for telling preferences and other customization of wallpaper. You can guide me through the steps to achieve this functionality and I would learn anything required and like to contribute to it.

**Comment by tanujnotes** [comment]
I'd say that Olauncher is not a wallpaper app so these issues are out of scope. Users can set any wallpaper they want from their phone settings or Gallery app. They can also long press On/Off next to Daily new wallpaper for a completely black background.
