### ISSUE TITLE
Different lock screen and launcher wallpapers

### ISSUE THREAD

**Issue by yarcod** [tanujnotes/Olauncher#33]
Hi!

First of all, great work on the launcher! I find extremely refreshing to have the interface so minimal - and I'm saying this coming from Niagara launcher! Also, very happy to see it as open source! 

Anyway, I would like to request the ability to have a daily image set as wallpaper and/or lock screen image, or to have either of them static. Say, for example, that I'd like to have a picture of my family on my phone where I see them very often, but then have another wallpaper change every day for variation. It shouldn't interfere with the simplicity of the launcher, right? 😊

Thanks in advance, and once again, great job!

**Comment by tanujnotes** [comment]
Thank you for the appreciation.

All I can say at the moment is that I have big plans for Olauncher wallpapers but none of them are priority right now. I currently busy with fixing a ton of serious issues that people complained about in last few days alone. I'll back to wallpapers later.

I hope you understand. Thank you.
