### ISSUE TITLE
How do I add a language like Italian to Olauncher? Thank you

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#332]
How do I add a language like Italian to Olauncher? Thank you

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/blob/master/app/src/main/res/values-it/strings.xml
This is the Italian language file. Please check it out and if you have any suggestions, please let me know.

**Comment by tanujnotes** [comment]
Well, you can't directly add the Italian language. I'm working on adding it and it should be available in the next update. What you can do is help me with the translations. 

https://github.com/tanujnotes/Olauncher/blob/master/app/src/main/res/values-it/strings.xml
This is the Italian language file. Please check it out and if you have any suggestions, let me know.

**Comment by Livio78** [comment]
thank you

    Il sabato 13 maggio 2023 alle ore 12:14:53 CEST, Tanuj ***@***.***> ha scritto:  
 
 


Well, you can't directly add the Italian language. I'm working on adding it and it should be available in the next update. What you can do is help me with the translations.

https://github.com/tanujnotes/Olauncher/blob/master/app/src/main/res/values-it/strings.xml
This is the Italian language file. Please check it out and if you have any suggestions, let me know.
