### ISSUE TITLE
App history is not accessible from the OLauncher.

### ISSUE THREAD

**Issue by ErikSulzbach** [tanujnotes/Olauncher#338]
I use gestures and when I swipe up, I can't reach my recently opened apps. The action is locked somehow.

When I am in other apps the function works. But this should also be possible from the home screen.

My specs:
Samsung Galaxy Note 10 Plus
One Ui 4.1
Android 12

![Screenshot_20230519-091759_Olauncher](https://github.com/tanujnotes/Olauncher/assets/83572689/1d19bbc7-d628-4b19-b7ad-995ec7fac397)

![Screenshot_20230519-091835_One UI Home](https://github.com/tanujnotes/Olauncher/assets/83572689/30963d24-17d5-4c2d-989e-6de469416e61)

**Comment by tanujnotes** [comment]
Hi, on Samsung devices, you'll have to swipe up and hold to see your recent apps when on homescreen. Hope this helps.
