### ISSUE TITLE
[Feature Request ]Home button when already on the home, opens search.

### ISSUE THREAD

**Issue by Minkiu** [tanujnotes/Olauncher#34]
Hey there,

I think this has more to do with the fact that I am on Android 9 without gestures and the bottom Navbar, but something I was used to on Nova:
When the user hits home, and the user is already on the home screen, the search box (the swipe up gesture) opens.
Could this be added? Maybe as an option?

Thanks for this nice launcher.
Cheers.

**Comment by tanujnotes** [comment]
Thank you for the appreciation.

About the issue, already have swipe up gesture to open search and it just works so I'm not keen on providing one more way to do the same thing. Also, users or different Android flavours might already have a assigned a task to home button. I'm quite hesitant in messing that up and upsetting people.

I hope you understand.

**Comment by Minkiu** [comment]
Yeah makes sense, that's why I was suggesting it as a option you can set, by default disabled, I guess it will just take me a while until I stop pressing the home button expecting the search to show ha! 

Just to clarify I mean a simple tap while being on the Home screen, not a long-tap, I have that mapped to Firefox for example.

Thanks again, feel free to close.
