### ISSUE TITLE
Full width row in home page

### ISSUE THREAD

**Issue by Nguyen-Hoang-Nam** [tanujnotes/Olauncher#342]
I've found that when click app in home page, I must click in name of app instead of the row that contains the app name.

![bug1](https://github.com/tanujnotes/Olauncher/assets/74345759/d49ef970-bfb0-4653-aeff-70df16fa284a)
![bug2](https://github.com/tanujnotes/Olauncher/assets/74345759/45154b0a-391d-44cc-85a6-52053f9f30d8)

**Comment by tanujnotes** [comment]
On app drawer, it is already full width. On home screen, if we made it full width, it will conflict with double tap to lock gesture.

**Comment by PhilipWhiteside** [comment]
@tanujnotes would you accept a PR if it was user configurable? 

I don't use double tap to lock and would happily keep that disabled and opt in enable full width.
