### ISSUE TITLE
double tap issue

### ISSUE THREAD

**Issue by bastschonet** [tanujnotes/Olauncher#346]
pixel 4a, android 13
olauncher 4.0.2

After switching on the device the "Double tap" feature only works, if the home screen will be left for any reason. E.g. open apps list, settings, any app. 
Reproduceable.

Already cleared cache and restarted device.

Known bug?

**Comment by tanujnotes** [comment]
I'm not able to replicate this and I haven't heard from anyone else who might be having a similar issue. This is might be a device specific quirk. Please try reinstalling Olauncher and restarting your phone. That generally fixes one-off issues like this.

**Comment by bastschonet** [comment]
Thanks a lot for your reply 

reinstalled and restarted.
Problem persists.

hm, I use an unrooted pixel 4a, with only few apps and latest android.

hm, I hope I find the cause

**Comment by bastschonet** [comment]
Hi. Found the cause 😀
If I disable the "accessibility menue shortcut" (in my case as gesture) the double tap feature works fine again.
Would be great if yoi can look into this.
