### ISSUE TITLE
Last item in app drawer is hidden behind navigation bar, when searching

### ISSUE THREAD

**Issue by Steellow** [tanujnotes/Olauncher#348]
When searching for an app, the last item is hidden behind the navigation bar which makes it impossible to click on it, or click+hold to do stuff like delete.

![IMAGE 2023-05-26 08:33:47](https://github.com/tanujnotes/Olauncher/assets/20144380/9287f565-b065-4b65-bbeb-2dc70b488e45)

**Comment by tanujnotes** [comment]
This is known and unfortunately expected... will fix it later.
