### ISSUE TITLE
Bug quando si ingrandisce il testo nelle scritte delle impostazioni versione 4.0.4

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#349]
Nella versione 4.0.4 con supporto per le lingue, ingrandendo il testo vengono tagliate le scritte relative all'allineamento Sinistra, centro e destra.

Una soluzione sarebbe quella che quando si ingrandisce  il testo, vengono ingrandite solo le scritte della Homepage e dell'app drawer, mentre le scritte nelle impostazioni non devono variare in dimensioni.

Questo non succedeva nelle versioni precedenti all'intrdouzione delle lingue fino alla versione 4.0.2.

Corregete il problema. Grazie

P.S. non chiudete la problematica, ma cercate di corregere

**Comment by tanujnotes** [comment]
Listen, this is a free app with a lot of bugs in it. Use it if it works well for you. Don't if it doesn't. I'm quite annoyed by your constant reviews edits, issues and emails. I have better things to do than playing customer support for you. Next time you face an issue, hire an Android developer to fix it for you. Please do not contact me in anyway. Please!

**Comment by Livio78** [comment]
Sorry for the inconvenience and inconvenience caused to me. I will not do it again. Congrats for Olauncher, for me it is the most beautiful minimalist launcher
    Il venerdì 26 maggio 2023 alle ore 13:11:32 CEST, Tanuj ***@***.***> ha scritto:  
 
 


Listen, this is a free app with a lot of bugs in it. Use it if it works well for you. Don't if it doesn't. I'm quite annoyed by your constant reviews edits, issues and emails. I have better things to do than playing customer support for you. Next time you face an issue, hire an Android developer to fix it for you. Please do not contact me in anyway. Please!
