### ISSUE TITLE
Clock freezes randomly

### ISSUE THREAD

**Issue by a3y3** [tanujnotes/Olauncher#35]
**Issue**:  The clock on the home screen will randomly freeze and show time from 2-3 hours ago. Clicking the clock (which opens the associated app) and going back to home usually fixes it in a few minutes.

**Steps to Reproduce**: 
Uknown

**Device**: OnePlus 6
**Android Version**: 10

**Comment by ksga** [comment]
Same issue.
Running stock Android 10 (OxygenOS 10.0.0) on Oneplus 5T

**Comment by tanujnotes** [comment]
Please update the app and let me know if this issue still appears.

**Comment by ksga** [comment]
Seemed to work, but now it has frozen again a few times for me with v1.4.
Still running stock Android 10 (OxygenOS 10.0.0) on Oneplus 5T

**Comment by tanujnotes** [comment]
I'll fix it in the next update.
