### ISSUE TITLE
Add ability to choose language

### ISSUE THREAD

**Issue by Minibus93** [tanujnotes/Olauncher#353]
After the 4.0.4 the translations came to Olauncher.

I wish it would've also come with the ability to pick which language to use because I (and probably other people too) don't want it to use my default phone language

Thanks as always for Olauncher!

**Comment by Livio78** [comment]
Spero che la tua richiesta d scegliere quale lingua usare, venga accolta nel prossimo aggiornamento senza appesantire troppo il launcher e spero a breve. Grazie

**Comment by tanujnotes** [comment]
You should be able to choose app language in the latest update. 
https://support.google.com/android/answer/12395118

**Comment by Minibus93** [comment]
Mhhh, unless it's a Android 13 only thing, on Android 12, MIUI 13 (Global) and Olauncher 4.0.5, the linked guide doesn't seem like it is applicable.

However, I know that MIUI 14 will move to Android 13, so I'm wondering if things will change in the next MIUI update

**Comment by Livio78** [comment]
In my opinion it is not a solution change the system language. The language change should be done within the Olancher settings, as it can already be done with its FORKs Olauncher CF (Clutter Free) and mLauncher. I hope the language change in Olauncher settings happens in the next update and hopefully soon. Thanks, I await an answer
    Il lunedì 12 giugno 2023 alle ore 15:24:17 CEST, Tanuj ***@***.***> ha scritto:  
 
 


You should be able to choose app language in the latest update.
https://support.google.com/android/answer/12395118

**Comment by Livio78** [comment]
668365

**Comment by Livio78** [comment]
In my opinion it is not a solution change the system language. The language change should be done within the Olancher settings, as it can already be done with its FORKs Olauncher CF (Clutter Free) and mLauncher. I hope the language change in Olauncher settings happens in the next update and hopefully soon. Thanks, I await an answer

**Comment by kotleni** [comment]
This is a example for programmatically change app language: (java)

```java
public static void setLocale(Activity activity, String languageCode) {
        Locale locale = new Locale(languageCode);
        Locale.setDefault(locale);
        Resources resources = activity.getResources();
        Configuration config = resources.getConfiguration();
        config.setLocale(locale);
        resources.updateConfiguration(config, resources.getDisplayMetrics());
}
```

**Comment by tanujnotes** [comment]
Other than this Github issue, I haven't received any request for language change feature. Almost everyone seems to be okay with Olauncher using their default phone language. Also, Android 13 and above provide the option to change app language from phone settings. For these reasons, this language change option most likely won't be added in the app.

**Comment by Minibus93** [comment]
While the issue is closed as "non planned" I just want to update a thing regarding one of my statements

> However, I know that MIUI 14 will move to Android 13, so I'm wondering if things will change in the next MIUI update

Currently, this is not a feature in MIUI, and no one knows if it'll ever be a part of MIUI. My POV is that Xiaomi may not consider this feature too useful, or even just consider it EVER,, especially when any app's developer can already easily integrate an in-app language picker, using that same API, that would work on any Android version, while this feature of app picking langauge via system settings is only available since Android 13...

In any case, I respect your decision of not planning to implement this, my goal was just to update one of my state for those who may end up reading this issue.
