### ISSUE TITLE
Wallpaper keeps changing when Olauncher is not the default launcher

### ISSUE THREAD

**Issue by ejmin** [tanujnotes/Olauncher#358]
Steps to reproduce:

- set Olauncher as default 
- enable daily wallpaper change 
- set any other launcher as default (Nova in this case) 
- wait <24 hours
- voilà, wallpaper changed 

Would it be possible to detect if it's default and change the wallpaper only when it's the default launcher? 

Android 13, Pixel 6 Pro
Olauncher v4.0.4 fdroid

**Comment by tanujnotes** [comment]
That's intentional. Many people use other launcher but keep Olauncher for its daily wallpaper. You can always turn it off in the settings.

**Comment by ejmin** [comment]
That makes sense.
