### ISSUE TITLE
Bug: App list does not always respond to the "App alignment" -setting

### ISSUE THREAD

**Issue by hugohutri** [tanujnotes/Olauncher#359]
I changed the "App alignment" value from "left" to "center"
What I expected: The home screen and app list to be centered
What happened: The home screen was centered, but the full app list was not

In this demo, I changed the value 3 times. First 2 times it did not work, last time it somehow worked.

https://github.com/tanujnotes/Olauncher/assets/55588133/ab77fc93-471b-49d2-9768-2a1984de5346

Phone: Samsung Galaxy S23
(And also happens on Oneplus 7t)

**Comment by Heike-HS** [comment]
It's not a bug, it's a feature. ;-)
If you longpress on "left - center - right" your current home screen app alignement will apply to all apps.
See description of Olauncher under "About" on the bottom of the settings screen.

**Comment by hugohutri** [comment]
> It's not a bug, it's a feature. ;-) If you longpress on "left - center - right" your current home screen app alignement will apply to all apps. See the description of Olauncher under "About" at the bottom of the settings screen.

Ah, thank you! I had been using Olauncher for months, but I must have missed this feature then :P
However, I feel like the UX suffers a bit from this feature because it is not clear that it should do this. Maybe there should be 2 options instead?
