### ISSUE TITLE
Is there a way to get the url of the current wallpaper?

### ISSUE THREAD

**Issue by arturbosch** [tanujnotes/Olauncher#36]
Hi,

happy user of this app here.

I really like the current wallpaper and was thinking if I can get the link to it ?

Thanks for the well done launcher.

**Comment by arturbosch** [comment]
Ah just found https://gist.githubusercontent.com/tanujnotes/481074b27ad4dc2607326c97439bb3ac/raw, thx!

**Comment by tanujnotes** [comment]
Glad you found it. Other way to get the current wallpaper url is to click on 'Daily wallpaper update' text in Olauncher settings. Works only when daily wallpaper update is ON.
