### ISSUE TITLE
Clock opened from Home screen is missing the Clock app navigation drawer

### ISSUE THREAD

**Issue by holtkampjs** [tanujnotes/Olauncher#360]
# Issue / Bug

I've used Olauncher for some time now and love the experience. There has been one feature with an issue I frequently find myself inconvenienced by. That is the fact that the Clock app when launched by the clock display in the home screen differs from the Clock app when launched from the navigation drawer. 

<img src="https://github.com/tanujnotes/Olauncher/assets/76000251/fc3e3deb-273d-437e-bb2c-751cb7f8f913" alt="drawing" width="400"/>
<img src="https://github.com/tanujnotes/Olauncher/assets/76000251/16cccb29-497b-45a5-9b71-49bae1ada76d" alt="drawing" width="400"/>

On the left, you can see the Clock app when launched by tapping on the clock display visible in the home view. On the right, you can see the Clock app when launched as a normal application from the navigation. As you can see, the drawer at the bottom for navigation within the Clock app is present in the right while missing on the left.

I would consider it a great improvement to launch the clock in its normal form as an app (the right hand view) from both methods of launching the application.

**Comment by tanujnotes** [comment]
This is Samsung specific issue. Might be fixed later.
