### ISSUE TITLE
Idea: App aliases/extra tags for search?

### ISSUE THREAD

**Issue by AdamDoesThingsSometimes** [tanujnotes/Olauncher#361]
Hi there, I'm loving Olauncher! :)

I was just using Tusky (a mastodon reader) and started typing in "Mastodon" because I was being absent-minded. It might be cool to add a feature to add an alias feature to add other words to look up an app with. :)

**Comment by tanujnotes** [comment]
I think app rename feature can help with this. No plan to add aliases.

**Comment by AdamDoesThingsSometimes** [comment]
Sorry, I'm a moron and didn't realise the rename feature was already in the launcher!

Yes, that's exactly what I had in mind! Sorry about that - definitely no need for anything else. :)

**Comment by AdamDoesThingsSometimes** [comment]
Sorry, I'm a moron and didn't realise the rename feature was already in the launcher!

Yes, that's exactly what I had in mind! Sorry about that - definitely no need for anything else. :)
