### ISSUE TITLE
Show installed PWA in list

### ISSUE THREAD

**Issue by break6700** [tanujnotes/Olauncher#369]
PWAs (Progressive web apps) should be listed like any other app.

### Steps

- Install PWA on phone (e.g. UberEats in chrome)
- Swipe to see list of apps
- New PWA is listed

## Other

I absolutely love this launcher. I have recommended it to lots of people and have received compliments on how clean my android experience is.

**Comment by tanujnotes** [comment]
Thank you! Please check the issue #20
