### ISSUE TITLE
Turn off automatic keyboard show

### ISSUE THREAD

**Issue by jacekel** [tanujnotes/Olauncher#37]
Can u next add option, to turn off automatic keyboard show after slide up, to show application on mobile phone?

/more /hide application on app list (but i read will be added). :)

Good work bro! :)

**Comment by tanujnotes** [comment]
Once you start scrolling the app list, keyboard disappears immediately.

Are you aware of this and don't want the keyboard to appear at all OR scroll to hide keyboard is enough? Please let me know.

**Comment by jacekel** [comment]
Ah not here. :D hahhahahaa


--
Best Regards,
   Jacek Laszewski

------ Original Message ------
From: "Jacek" <jacek@foryou.pl>
To: "tanujnotes/Olauncher" 
<reply@reply.github.com>
Sent: 05.10.2020 17:31:16
Subject: Re[2]: [tanujnotes/Olauncher] Turn off automatic keyboard show 
(#37)

**Comment by jacekel** [comment]
I would like there to be an option to not display it at all by expanding the menu.
When you add an additional option, such as removing an application from the menu list, the pop-up keyboard will not be needed.

**Comment by tanujnotes** [comment]
Got it. I'll see what I can do.

**Comment by kaugummiheld** [comment]
> Once you start scrolling the app list, keyboard disappears immediately.

While this is definitely working right now, I second for an option to default to not show the keyboard when opening the all apps list. :slightly_smiling_face:

**Comment by tanujnotes** [comment]
Interesting. I never thought of it that way because my keyboard looks... not bad.
A lot of people are asking for ability to hide keyboard by default so I'll be adding it as soon as I can.

**Comment by tanujnotes** [comment]
Done. Wait for the next update (v1.3). Thank you.

**Comment by jacekel** [comment]
> Done. Wait for the next update (v1.3). Thank you.

Thank U! :)
