### ISSUE TITLE
[FR] support to use pinyin for search Chinese character

### ISSUE THREAD

**Issue by LogicFan** [tanujnotes/Olauncher#371]
It's hard to search using Chinese characters since it will involve several steps to type it. it would be nice to allow using Pinyin to search it instead. 

pinyin is an alphabetical representation of Chinese characters that resembles its pronunciation. it has a 1-to-many relationship where 1 pinyin may match multiple characters. 

the proposed change would be when we match the app label, we convert all Chinese characters to their corresponding pinyin and then do the regular match.

I can work on this if this FR sounds reasonable. 

A possible alternative solution is to rename all Chinese apps one by one manually, but it will be time-consuming.

**Comment by tanujnotes** [comment]
How would you implement this?

**Comment by LogicFan** [comment]
i plan to change https://github.com/tanujnotes/Olauncher/blob/52563b04a4e47151ba2822aaebfc15f95251c983/app/src/main/java/app/olauncher/ui/AppDrawerAdapter.kt#L114
by adding another or condition.

for translating Chinese character to Pinyin, i plan to use https://github.com/promeG/TinyPinyin this library

**Comment by tanujnotes** [comment]
This problem exists for other languages as well and things will get too complicated if we started fixing this for all the languages.
