### ISSUE TITLE
Daily wallpaper fails to update on devices with non-western Arabic numerals locale

### ISSUE THREAD

**Issue by asubah** [tanujnotes/Olauncher#372]
Hi,
First, thank you for the great work.

The following method fails on devices with locale that has non-western Arabic numerals  (1 2 3) such as locale with Eastern Arabic numerals (١ ٢ ٣). Which prevents the daily wallpaper from updating.

https://github.com/tanujnotes/Olauncher/blob/52563b04a4e47151ba2822aaebfc15f95251c983/app/src/main/java/app/olauncher/helper/Utils.kt#L350

The reason for this issue is the following line:

https://github.com/tanujnotes/Olauncher/blob/52563b04a4e47151ba2822aaebfc15f95251c983/app/src/main/java/app/olauncher/helper/Utils.kt#L356

As mentioned in the [Kotlin docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/format.html), if the locale argument is not set, the `String.format` method will use the default locale.
So the value of `key` will be `٧_٧` instead of `7_7` on some devices.
Which will make this line throw an exception:

https://github.com/tanujnotes/Olauncher/blob/52563b04a4e47151ba2822aaebfc15f95251c983/app/src/main/java/app/olauncher/helper/Utils.kt#L372

An easy fix would be to set the `locale` argument in `String.format` to null, which will stop it from applying any localisation.
You can test it from my fork.

```kotlin
val key = String.format(null, "%d_%d", month + 1, day)
```

https://github.com/asubah/Olauncher/blob/112bee49f0f26b01c49c2a9800c393fafab272b9/app/src/main/java/app/olauncher/helper/Utils.kt#L356

**Comment by tanujnotes** [comment]
Hi, thank you very much for this. Will be sending an update soon.
