### ISSUE TITLE
Not localized string for RU language

### ISSUE THREAD

**Issue by kotleni** [tanujnotes/Olauncher#376]
This string need to be translated.

![image](https://github.com/tanujnotes/Olauncher/assets/38311102/824e3fdc-dc85-4689-90af-9b8848beae9f)
![image](https://github.com/tanujnotes/Olauncher/assets/38311102/93c7804f-5ece-4da8-851f-77251998ab81)

**Comment by tanujnotes** [comment]
What's the Russian for App? Tell me and I'll add it.
