### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by noscirep** [tanujnotes/Olauncher#380]
Since I am not very familiar with GitHub (yet), I hope it's okay that I submit my Swedish translation of Olauncher this way (attached file, I added ".txt" at the end to be able to attach it). Please let me know if there are any issues with the translation. I will do my best to keep it up to date.

Should the quotation marks in the "bottom_on" (beginning and end, plus a space after "On") and "no_hidden_apps" (end) strings really be there? I have kept them in my translation to be on the safe side. Also, shouldn't the "instagram" and "twitter" strings be marked as "translatable=false"?

[strings-se.xml.txt](https://github.com/tanujnotes/Olauncher/files/12213169/strings-se.xml.txt)

**Comment by tanujnotes** [comment]
Hi, both bottom_on and no_hidden_apps had typos which is now fixed. Thank you for pointing it out.
While words like Twitter can't be translated, they can still be written in different languages. Twitter in Japanese is ツイッター. I hope that clears things up.

I've added the Swedish translation. It will be available in the next update.
