### ISSUE TITLE
Adding hierarchy or folders 

### ISSUE THREAD

**Issue by ekg** [tanujnotes/Olauncher#386]
It would be a little less minimal, but it would really help me to have clusters or folders of similar apps. For instance I have ten messaging apps and three web browsers.

Say I wanted to patch Olauncher to do this. Where would I start editing? What's a plan of attack to implement this?

**Comment by tanujnotes** [comment]
Hi, there's no plan to add folders. You can try renaming the apps in a way that makes it easier for you to manage them.

**Comment by ekg** [comment]
I understand. I'm talking about making a fork of this and editing this myself. This isn't a feature request. It's a coding advice request.

**Comment by tanujnotes** [comment]
@ekg Oh, sorry, I misunderstood.

I think the easiest way to do this would be to create a list of apps for each folder and then saving the json in the preference file. You can take a look at how Hidden apps are managed in Olauncher and that should give you a good starting point.

To show the folders, I'd add them at the top of the app list in the app drawer screen. I wouldn't touch the existing app list, just add a new view at the top to show the folders.

Same deal if you want to show folders on the home screen. Try not to touch the existing app list. Create a new view to show folders, maybe at the bottom or on the other side. It'll be easier.

Let me know if you have questions or want a more detailed answer.
