### ISSUE TITLE
Swedish translation unavailable - wrong language code

### ISSUE THREAD

**Issue by noscirep** [tanujnotes/Olauncher#387]
I just upgraded Olauncher to version 4.1.0 on a device with the system language set to Swedish, but the app is still in English. I realize now that I used the wrong language code for my translation file: it should be "sv", not "se" (language code, not country code). Perhaps even "sv-rSE"? My apologies.

By the way, here is the updated translation (rename as appropriate): [strings-sv-rSE.xml.txt](https://github.com/tanujnotes/Olauncher/files/12329127/strings-sv-rSE.xml.txt)

**Comment by tanujnotes** [comment]
[Olauncher apk.zip](https://github.com/tanujnotes/Olauncher/files/12335945/Olauncher.apk.zip)

I've made the changes and pushed the code. Would you be able to test it? My phone for some reason doesn't have Swedish language.

**Comment by noscirep** [comment]
Thank you, @tanujnotes! I just installed the APK that you attached and can confirm that the app is now in Swedish for me.

**Comment by tanujnotes** [comment]
Great! New update sent. Thank you for your help.
