### ISSUE TITLE
[Feature request] Add a folder support

### ISSUE THREAD

**Issue by darkvadd7** [tanujnotes/Olauncher#39]
Hi, and congratulations for this great launcher.
I want to suggest something: is it possible to add support for folders. For exemple, in the first menu, there is a folder named "Messaging" and when click on it, a secondary menu replaces it with "ProtonMail", "Signal". And swipe left could return on the first menu.
What do you think about that?

**Comment by tanujnotes** [comment]
Hi, currently there's no plan to add folders in any form. If there's anything else I can help with, please let me know. Thank you.
