### ISSUE TITLE
50% less scrolling

### ISSUE THREAD

**Issue by xi7** [tanujnotes/Olauncher#391]
https://github.com/tanujnotes/Olauncher/assets/67331785/5e00d24e-3a50-42b2-84f6-dff4b71e7693

half boring scroll apps , 2 columns 🙂

**Comment by tanujnotes** [comment]
I like how it looks. But, it's generally harder to look for stuff in a grid layout than a straight list.

**Comment by xi7** [comment]
https://github.com/tanujnotes/Olauncher/assets/67331785/f4aa4937-7bc6-4018-9baa-82ed471bb28d

may need to consider scroll 200 apps look much slower than scroll 100 using 2 columns.

second example, we can the #2 column and separate games or other priority from a huge list.

**Comment by tanujnotes** [comment]
To maintain the simplicity of the app drawer (and rest of the app), currently there's no plan to make any big changes in it. The search works quite well for anyone who has 200 apps. No need to scroll at all.

**Comment by tanujnotes** [comment]
I'm not denying the issues related to remembering the app names or scrolling a ton of apps. I'm just saying that these are not the problems that Olauncher aims to solve. For now, it will stay the way it is.

There are a few forks of Olauncher which are quite popular. Maybe you can suggest these features there.

Thank you.
