### ISSUE TITLE
Google Assistant

### ISSUE THREAD

**Issue by solankybasant** [tanujnotes/Olauncher#392]
Can somehow make this work with Olauncher.

**Comment by tanujnotes** [comment]
Can you explain a little more about what you mean?

**Comment by solankybasant** [comment]
The google assistant is not working when I changed the default launcher to Olauncher, is there any possible way such that I can use both.

**Comment by tanujnotes** [comment]
Olauncher has nothing to do with Google Assistant. Maybe try restarting your phone.
