### ISSUE TITLE
Hide keyboard when landing on home screen

### ISSUE THREAD

**Issue by harmtemolder** [tanujnotes/Olauncher#393]
When landing on the home screen coming from an app where I had my keyboard open, the keyboard remains open. I would expect the keyboard to be hidden, because it doesn't actually do anything on the home screen. When I then open the apps list by swiping up the keyboard hides, even though now I need it (and _Auto show keyboard_ is set to _On_).

Let me know if the above is unclear and you need a screen recording.

**Comment by tanujnotes** [comment]
A screen recording will be helpful. Also, what phone model and Android version you're using?

**Comment by harmtemolder** [comment]
I'm on a Hisense A9 running Android 11

https://github.com/tanujnotes/Olauncher/assets/8167752/ef09c0b7-a48f-4d8a-8fbe-a9e41d444972

**Comment by tanujnotes** [comment]
Would you be able to quickly test this launcher and see if the same is happening or not?
https://play.google.com/store/apps/details?id=app.prolauncher

**Comment by harmtemolder** [comment]
I cloned and built the repository: the issue is fixed! Thanks!
