### ISSUE TITLE
Shortcut to DuckDuckGo

### ISSUE THREAD

**Issue by Baps-P** [tanujnotes/Olauncher#397]
As you say, this app IS perfect, but may I suggest something that'd make it "perfecter" ?

It would be nice if we could set our own shortcut to search on DuckDuckGo. The "!" sign is not that accessible on my keyboard, it would be easier if I could set another shortcut more in line with the keyboard layout I use.

Also, when I type "!my search", DuckDuckGo search for "!my search" and not "my search".

**Comment by tanujnotes** [comment]
Use "!ddg my search" to search on DuckDuckGo and "!g my search" to search on Google.

**Comment by Baps-P** [comment]
Nice trick!

But that wasn't my concern. I use the French version of the OpenBoard keyboard and the layout of the "main" keyboard offers me only "," and ".". To type a "!", I need to go to the secondary keyboard with special characters.
So it would be nice if I could set Olauncher so the websearch would be triggered by either a "," or a "." (but, as everyone has a different keyboard and a different language, if we could choose for ourself the key that's more convenient to us, it'd be better).

Anyway, thanks for this app, I happily use it for almost 2 years now and my phone was never that easy and pleasant to use (and I think a phone set up with OLauncher would be way more accessible to old people), you bring joy to the world.
(I know, you prefer to receive positive feedback when it's not attached to a request, I'm sorry, I'm working on myself to do that)

**Comment by tanujnotes** [comment]
I appreciate it.

Adding such customisation is out of scope for Olauncher, especially for such a niche issue.

I'm not sure about the French version but in the regular OpenBoard, long pressing the "." gives you the option for "!".
