### ISSUE TITLE
[Feature Request] Shortcuts

### ISSUE THREAD

**Issue by akashpal-21** [tanujnotes/Olauncher#4]
Would you think about adding Shortcuts somehow? Enabling them in search would be a functional way i suppose.
I have some apps Containerised in Shelter.

**Comment by tanujnotes** [comment]
What exactly do you mean by shortcuts? Please explain how it would work or point me to some resource.

**Comment by akashpal-21** [comment]
https://android.jlelse.eu/nhandling-shortcuts-when-building-an-android-launcher-5908d0bb50d2

https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts

Although adding anything of this sort can take away the minimalist aesthetics of the app. The "All Apps" screen can quickly fill up with junk shortcuts i guess.

**Comment by tanujnotes** [comment]
As you mentioned, implementing this without cluttering the current clean look is going to be hard.
One possibility that makes sense to me is to implement shortcuts only for the apps on home screen (shown on long press).


I like this and thank you for the suggestion but I'm quite wary of adding new features unless more than a few people want it. I'll reconsider this in future. I hope you don't mind.

**Comment by akashpal-21** [comment]
Sure, thanks.
