### ISSUE TITLE
The writings in the settings menu overlap

### ISSUE THREAD

**Issue by Livio78** [tanujnotes/Olauncher#401]
The writings in the settings menu overlap, especially as the character size increases. Correct. P.S. It's a BUG

**Comment by Livio78** [comment]
Hi, has anyone encountered this problem (BUG)? Thank you

**Comment by pratikkabade** [comment]
try sharing screenshot it might make it easier to understand what your saying

**Comment by Livio78** [comment]
Here is the SCREENSHOT to make it clear that the writings in the settings menu are superimposed. Can it be made so that by enlarging the text, the writing in the settings menu does not change size? Correct. Thank you
![Screenshot_20231009-121451](https://github.com/tanujnotes/Olauncher/assets/96789413/09d51220-946e-44c3-befe-1458b9773448)

**Comment by tanujnotes** [comment]
I currently don't have time to work on this. If someone sends a PR, I'll be happy to accept.
