### ISSUE TITLE
[Feature request] More convenient renaming behaviour

### ISSUE THREAD

**Issue by shai8I** [tanujnotes/Olauncher#406]
|Regarding the action:|Current behaviour|Proposed behaviour|Pros of current behaviour|Pros of proposed behaviour|
|-|-|-|-|-|
|Hold app then tap "Rename".|Text box is empty; shows current name as hint.|Text box contains current name, highlighted (selected).|• Won't forget which app is being renamed.|• Won't forget which app is being renamed. • Can make small changes to name without retyping (e.g. fix typo, add tags, etc.).
|Deleting all text in text box.|Hint of current name is displayed.|Hint of default (original) name is displayed.|• Won't forget which app being renamed.|• Won't forget which app being renamed. •Lets the user know the default it'll change to after pressing "RENAME".|
|Typing text into empty text box.|Hint is displayed underneath.|Hint is hidden.|N\A.|• No overlapping of text.|
|Pressing "RENAME" with empty text box.|No action.|App is renamed back to the original name (as shown in the hint).|N/A.|• No need to manually check settings.|

**Comment by shai8I** [comment]
> highlighted (selected)

On second thought, maybe doing "Select all"/ double tap + drag whenever needed might be more convenient.

**Comment by VishnuSanal** [comment]
hi, I would like to work on this issue.

**Comment by tanujnotes** [comment]
@VishnuSanal Sounds good. Please DM on Twitter so we can discuss the implementation.

**Comment by tanujnotes** [comment]
@VishnuSanal Sounds good. Let me if you had any questions.
