### ISSUE TITLE
[Feature request] Standardised app name size.

### ISSUE THREAD

**Issue by shai8I** [tanujnotes/Olauncher#407]
Currently, the text size of the app names on the app list is smaller, in comparison to that of the home screen which is larger.

IMO the different sizes gives the impression that the smaller apps are lower in hierarchy, or that they represent two different things. (While they're different in that one is a shortcut, they're both still representations of apps.) It also makes it feel as though the apps on the main screen are 'too small', while simultaneously the apps in the app list are 'too large'.

Hence I'd like to propose a standardised text size for app names on both the home screen and the app list. (Probably match size of the app names on app list to that of the home screen to keep the app:clock size.)

P.S. I appreciate the dedication to minimalism! :) Like using app names for tags/ folders/ keyword shortcut/ arrangement instead of dedicated features. IMO the delegation of keyboard for launching and app list for searching makes sense to me. I'd go further to say that certain jobs like "Delete" can be left to app managers or 'Info > Uninstall' rather than an app launcher... but IG that's what's expected nowadays?

**Comment by tanujnotes** [comment]
The text size of home apps and app drawer apps is exactly the same and always has been. The vertical gap between the home apps is slightly smaller than the gap b/w app drawer apps.

Thank you for your kind words. People kept asking for Delete option and that's why it was added.

**Comment by shai8I** [comment]
You're right, my bad.

It does feel a little 'off' though. Perhaps a standard spacing somewhere in the middle?

**Comment by tanujnotes** [comment]
People seem okay with the way things are, including me, so no plan to make any changes. Try changing the text size to see if it looks better.

**Comment by shai8I** [comment]
I understand, no need to fix it if it ain't broke.

Actually, I just checked out your Pro Launcher -- the spacing seems to be consistent there.

(Neat name BTW. But, no FOSS? D: Surely there can be a separate proprietary billing module/ FOSS billing method + play store compatible version?)

**Comment by tanujnotes** [comment]
Olauncher did not have text resize earlier. The spacing on home screen is less so that 8 apps can fit on smaller screen. But since it does have text resize now, maybe spacing can be modified a little bit.

(Thank you. No plan to open source it for now because monetization is priority and it can be hard to monetize open source apps. Maybe someday... when money is less of an issue.)
