### ISSUE TITLE
Swipe left and right do not open any app

### ISSUE THREAD

**Issue by mlucchini** [tanujnotes/Olauncher#412]
- Phone: Pixel 7 Pro
- OS: Android 14

I'm not sure if this appeared with a new app update (I'm using v4.1.5). Swiping left or right works on occasions (usually on the second try) but mostly just does nothing and hides the whole menu. In other words, a swipe leads to an empty screen. I then have to swipe up to get the OLauncher again and it usually works after that.

**Comment by mlucchini** [comment]
- Phone: Pixel 7 Pro
- OS: Android 14

I'm not sure if this appeared with a new app update (I'm using v4.1.5). Swiping left or right works on occasions (usually on the second try) but mostly just does nothing and hides the whole menu. In other words, a swipe leads to an empty screen. I then have to swipe up to get the OLauncher again and it usually works after that.

Sadly, I just noticed that trying to open some apps from the OLauncher menu does the same thing. Sometimes.

**Comment by tanujnotes** [comment]
The latest Android 14 update, which is still be beta, is causing issues with most launchers. So this will most likely be fixed by the an OS update. I'll see if there's a way to fix it from the app side.

**Comment by mlucchini** [comment]
Settings > Accessibility > Remove animations

Not a proper fix but avoids the issue mentioned above.
