### ISSUE TITLE
Adhere to the system text size.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [tanujnotes/Olauncher#418]
There's no reason I should need to set it for OLauncher manually.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/418#event-10864196333

Why? It's the primary reason I don't use this Launcher, so I'd really like to have it fixed.

**Comment by tanujnotes** [comment]
You can change the text size from the Olauncher settings.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/418#issuecomment-1805095390

@tanujnotes, but it doesn't synchronize with the system, meaning that I must modify OLauncher's text size whenever I modify the system's text size.l

**Comment by tanujnotes** [comment]
I don't know. Ideally it should. Olauncher doesn't do anything special with text size. May or may not be a device specific issue.

**Comment by RokeJulianLockhart** [comment]
I've tested on the Pixel 3 running the CalyxOS A12 equivalent and on its stock A9 ROM, and also on the Fairphone 4's stock A9 to A13 ROM versions, so it shouldn't be device or distribution-specific.

**Comment by tanujnotes** [comment]
I'll see what I can do. No promises though.
