### ISSUE TITLE
Display app list instead of home screen when "Apps on home screen" is 0.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [tanujnotes/Olauncher#419]

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/419#event-10864196035

@tanujnotes, why? It seems redundant to force a user without favourites to perform unnecessary gestures *every* time they want to acess any application simply because they prefer searching to using favourites.

**Comment by tanujnotes** [comment]
Because.

**Comment by RokeJulianLockhart** [comment]
@tanujnotes, I don't understand.
