### ISSUE TITLE
[FEATURE REQUEST] Un-hide hidden apps

### ISSUE THREAD

**Issue by worthlessDev** [tanujnotes/Olauncher#42]
Currently to un-hide hidden drawer apps, one must clear app storage.
An option to repopulate app drawer with hidden apps in the launcher settings menu would be helpful.

**Comment by tanujnotes** [comment]
Open Olauncher settings and tap on 'Olauncher' text to see all you hidden apps. I apologize for the inconvenience and have already made changes to make it more obvious, coming in the next update. Thank you.
