### ISSUE TITLE
Searching apps keyboard strokes open apps

### ISSUE THREAD

**Issue by PennyS8** [tanujnotes/Olauncher#427]
I am using S22+ Samsung Android device running Android version 13 and Samsung Defaukt Keyboard (version 5.6.10.40).

I don't use the app search bar feature often so I only recently had an issue with it. It appears that my key strokes are, while still typing the letter at first, then will open an app. I found that without scrolling when I searched the same 2 letters "p" then "i" on the second key stroke woulf always open up the same app. I suspect that the app that is opened is the app that is hidden behind my keyboard. The keyboard overlay does not override the touch input on the app list screen behind the overlay.

Let me know if there is any more information that I can give you to assist you in correcting this bug.

**Comment by tanujnotes** [comment]
If your clicks are passing though the keyboard and opening the app behind it, it's a keyboard issue.
