### ISSUE TITLE
Daily new wallpaper malfunctions on closed Galaxy Z Flip 5

### ISSUE THREAD

**Issue by mreintz** [tanujnotes/Olauncher#437]
The Samsung Galaxy Z Flip 5 has a secondary "outside" screen. If I leave the phone closed throughout the night, the new wallpaper will appear on the exterior screen only. I have to open the phone and toggle the daily new wallpaper option to get the new wallpaper on the primary screen. 

Suggestion: Ensure that the wallpaper change is executed on the primary screen only, regardless of the phone open/closed state.

Otherwise love the app!

**Comment by ben-2357** [comment]
Sorry for asking here, because I don't know where else to, but where does OLauncher pull the daily wallpapers from?

**Comment by tanujnotes** [comment]
@ben-2357 mostly unsplash.com

**Comment by ben-2357** [comment]
@tanujnotes thanks!
