### ISSUE TITLE
App list loading is slow on Redmi Note 10 Pro after kill and relaunch

### ISSUE THREAD

**Issue by deepaks2112** [tanujnotes/Olauncher#439]
Device: **Redmi Note 10 Pro**
MIUI: **MIUI Global 14.0.1**
Android: **13 TKQ1.221013.002**

Current Behaviour:
When a lot of apps running simultaneously for a long time or I go to recent apps and clear all, then launch OLauncher and open app drawer **very quickly**, the app list is empty for **2-3 seconds**. [Video](https://www.file.io/yfPz/download/BflEBrD2iEbS).

Expected Behaviour:
App list should not appear to be empty when OLauncher is killed and launched afresh and drawer is opened up.

Steps to reproduce:
1. Open OLauncher
2. Swipe up to open app drawer
3. Ensure app list is loaded
4. Go to recent apps
5. Click on close all
6. Reopen OLauncher
7. **Quickly open app drawer**

@tanujnotes I was wondering if it is okay to persist the last fetched app list in shared preferences and use it as a cache while the app list gets populated asynchronously by the current implementation. I have coded a fix for it using shared prefs as a cache. I think MIUI is notorious and kills all background services including the default launcher.

**Comment by deepaks2112** [comment]
I have 181 apps installed on my phone including system apps.

**Comment by tanujnotes** [comment]
We already use livedata which takes care of the caching for the most part.
