### ISSUE TITLE
Homescreen shortcuts were not working

### ISSUE THREAD

**Issue by Nesaijn** [tanujnotes/Olauncher#44]
After the latest update in the fdroid store, version 1.5, the shortcuts in the homescreen weren't working anymore. Restarting Olauncher didn't help. I had to remap them.
Just a note if more people experience this and maybe this can be prevented in future releases.

On LineageOS 17.1

**Comment by SimonCDalzell** [comment]
Same issue here.

**Comment by tanujnotes** [comment]
An update has been released with this issue fixed. Might take a few hours to appear on Play Store and F-Droid. Your patience is appreciated.

For now you can long press on home screen apps and select the app again from the list. It will work again. Sorry for the inconvenience.
