### ISSUE TITLE
Keyboard reopening on app switch

### ISSUE THREAD

**Issue by guillaumeboehm** [tanujnotes/Olauncher#440]
The keyboard reopens on the android app switch view when launched from the olauncher app list view (the bug occurs on my system about 2/3 times).

I am running Android 12. 

Steps to reproduce:
- Go on home view
- Show App List (Swipe up in my case), this opens the keyboard
- Wait a second or two (It sometimes happens without waiting at all but less often it seems)
- Open the android app switch view
- Bug occurs (see screenshot)

I tested with UnexpectedKeyboard, Samsung keyboard and 3 other keyboards, this bug happens with all of them.
Same behavior with three apps no set to anything on the home screen and with 11 apps set to things, so this does not seem to be related.
The bug also occurs with OLauncher launched as a normal app and not set as home screen.

![Screenshot_20240110_172926_One UI Home](https://github.com/tanujnotes/Olauncher/assets/12833794/47e6a182-246a-4ac0-8e20-b5f2d50bf7d5)

**Comment by tanujnotes** [comment]
I could not replicate this on 3 different phones of different brands that I had access to.
