### ISSUE TITLE
Cache daily wallpapers after downloading them.

### ISSUE THREAD

**Issue by The-Hypervisor** [tanujnotes/Olauncher#442]
If there is no internet connection and I change the theme to dark or light, the wallpaper will not appear and I will be presented with black or white background.

I assume that this issue is because the launcher has to download the wallpaper every time it needs to change it, I also noticed some small delay to set the wallpaper when changing the theme, and maybe it is related to the same issue.

Please make download the daily wallpapers and cache them everyday (both for dark and light themes), it will help a lot.

Thank you for your time.

**Comment by tanujnotes** [comment]
This is a good idea but not planned for now. If someone creates a PR, I'll be happy to merge.
