### ISSUE TITLE
Hidden apps setting updates wrong

### ISSUE THREAD

**Issue by mariohuq** [tanujnotes/Olauncher#445]
https://github.com/tanujnotes/Olauncher/blob/20c18ba87a0d7e679e0c8ed053f4790d11e9d267/app/src/main/java/app/olauncher/helper/Utils.kt#L158

That should be with a delimeter `+ "|" +`:

```kotlin
else newHiddenAppsSet.add(hiddenPackage + "|" + android.os.Process.myUserHandle().toString())
```

That's a minor issue and probably would never produce `IndexOutOfBoundsException` (but can) in a line:
https://github.com/tanujnotes/Olauncher/blob/20c18ba87a0d7e679e0c8ed053f4790d11e9d267/app/src/main/java/app/olauncher/helper/Utils.kt#L132

**Comment by jacksongoode** [comment]
Yes, I've noticed apps cannot be hidden.

**Comment by aswinnnn** [comment]
is this why apps once hidden, cannot be showed again? Olauncher just crashes (and sometimes) removes itself as the default launcher after I try to un-hide an app.

**Comment by tanujnotes** [comment]
Did you guys try reinstalling the app once? I'm not able to replicate this issue. And not seeing any complaints either other than this thread.

**Comment by mariohuq** [comment]
@tanujnotes reinstalling fully resolves that issue.
