### ISSUE TITLE
 Theme System default

### ISSUE THREAD

**Issue by raquibCodes** [tanujnotes/Olauncher#447]
There is only two options for Theme Mode, Light or Dark. I think there should be another option of System Default, its more convenient to have.

![olauncher-theme](https://github.com/tanujnotes/Olauncher/assets/149041658/3f3fadd2-033d-4d67-8e17-7f3d0930fafa)

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/issues?q=system+theme
