### ISSUE TITLE
Olauncher Crashing After Opening Work Apps

### ISSUE THREAD

**Issue by axian32** [tanujnotes/Olauncher#45]
Hi tanujnotes,

Really appreciate the addition of work apps! Just wanted to notify you that when I open my work profile Whatsapp and work profile Instagram, Olauncher crashes. Video attached.

Alan

![olauncher-crash](https://user-images.githubusercontent.com/64721934/99752644-8b474a00-2a99-11eb-9552-8e6bffd088ba.gif)

**Comment by tanujnotes** [comment]
An update has been released with this issue fixed (v1.8). Might take a few hours to appear on Play Store and F-Droid. Thank you for your patience.

**Comment by axian32** [comment]
awesome!

Nov 19, 2020, 10:20 PM by notifications@github.com:
