### ISSUE TITLE
System theme mode

### ISSUE THREAD

**Issue by dessalines** [tanujnotes/Olauncher#456]
Currently there is only dark and light. It'd be nice if olauncher could add the system theme mode, so I can use it in conjunction with my theme-mode-specific wallpapers.

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/issues?q=system+theme

**Comment by dessalines** [comment]
Ah thx. 

I think what's confusing, is that it's only shown when you long press for some reason. Why is that necessary?
