### ISSUE TITLE
 "Switch apps" button stops working after a while

### ISSUE THREAD

**Issue by magical-heyrovsky** [tanujnotes/Olauncher#457]
On my phone I am using the classic "3-button navigation", where the right button is the "switch apps" button (see screenshot). If I click it it shows me all recently used apps and if I double tap it immediately switches to the previously used app. I think everyone knows this behavior.
For about 2-3 months now, it has been happening regularly that this button suddenly stops working. This means that when I click on the button, nothing happens. I have this problem about every 3 days. Even if I "force stop" Olauncher and start it again it still doesn't work. The only way to make it work again is to restart the phone OR switch to the default Android launcher, there it works. I also completely uninstalled Olauncher and installed it again, but the problem remains.

I was wondering if someone else is experiencing the same problem. It's quite annoying, I'm sure I'm not the only one who uses this "quick switch" button very often.

![android](https://github.com/tanujnotes/Olauncher/assets/155846140/5bdb7684-072f-4205-8a52-b1e8ee3c2617)

I am using a Google Pixel 6a with up to date Android 14. Olauncher version is 4.2.0.

**Comment by kfoxb** [comment]
I'm also noticing this on my pixel 7.

Here's something weird I happened to notice and have been able to reproduce twice now. When the "switch apps" button stops working I can go force stop Pixel Launcher in settings and that'll fix it immediately.

I'm curious if that works for anyone else. I don't really understand why that would fix it, but it seems to.

**Comment by tanujnotes** [comment]
Turn off the battery optimization for Olauncher from your phone settings. If that doesn't fix it, I'm not sure what will.
