### ISSUE TITLE
[Feature Request] Scroll Bar in App List

### ISSUE THREAD

**Issue by humptyhump** [tanujnotes/Olauncher#46]
Have a scroll bar in the app list for quick and easy one hand navigating. 

Something like Indistractable Launcher's app list

**Comment by ThatOneDev-Code** [comment]
id love to see this added

**Comment by ANDREW007CZ** [comment]
I'd love to see that too. Like "alphabet" scroll.

**Comment by topsy-turvy99** [comment]
Add light vibration to when the bar is scrolled
