### ISSUE TITLE
OLauncher freeze on the home screen

### ISSUE THREAD

**Issue by constarg** [tanujnotes/Olauncher#463]
Hello @tanujnotes,
First of all, I really like this project and it's philosophy to be minimal. 
I have a Samsung phone which recently updated to One UI 6.0. After the update, I had noticed that every now and then, the OLauncher stuck in the home screen, and i cannot do anything until I stop it with force, by going on settings > OLauncher info and press the force stop button. 
Thanks you, keep up with the good work,

**Comment by tanujnotes** [comment]
Turn off the battery optimization for Olauncher (from your phone settings) and restart your phone once.
