### ISSUE TITLE
Right-align app list

### ISSUE THREAD

**Issue by alessandrococco** [tanujnotes/Olauncher#47]
Hi @tanujnotes,
I just started using OLauncher and already love it!

I set the _home alignment_ to right. I wish I could set the same alignment in the app list, that would be nice!

![image](https://user-images.githubusercontent.com/2331798/101243852-465f1c80-3703-11eb-8ec1-1c55526bff70.png) ![image](https://user-images.githubusercontent.com/2331798/101243861-54ad3880-3703-11eb-83e9-7aa11c08e961.png)

What do you think?
Thank you!

**Comment by tanujnotes** [comment]
If you want to change app list alignment so that it's easier to click, you don't need to. Apps in the list are full width. You can click on the right most side to open the app.

Or is it because you think they'd look good that way? Let me know. Thank you for using Olauncher.

**Comment by alessandrococco** [comment]
> Or is it because you think they'd look good that way?

This! It's a matter of coherence between the two views 😄 

Maybe a new line in settings: _App list alignment: LEFT|CENTER|RIGHT|SAME AS HOME_

**Comment by tanujnotes** [comment]
The thing is, the current setup works for most people and I haven't had many people asking for this particular feature. For these reasons, it will stay the way is it for now. If more than a few people asked for something like this, I have no issue in adding it. Thank you.

**Comment by alessandrococco** [comment]
Ok, no problem! Anyway I'm a java/kotlin developer and during the Christmas holidays I could try to implement it myself - would you accept a pull request?

**Comment by tanujnotes** [comment]
Sorry but I won't be accepting changes regarding this particular feature because of the reasons I mentioned above.

**Comment by tanujnotes** [comment]
I made some changes. If you long press on home alignment settings, app drawer will follow the same alignment. It's not perfect but gets the job done for people who really want it while maintaining the minimalism. 
I have pushed the code so you can either build it yourself or wait for the next update. Thank you.

**Comment by Donkey-Doug** [comment]
> I made some changes. If you long press on home alignment settings, app drawer will follow the same alignment. It's not perfect but gets the job done for people who really want it while maintaining the minimalism. I have pushed the code so you can either build it yourself or wait for the next update. Thank you.

This does not work for me on version 3.3.
