### ISSUE TITLE
Filtering won't work at all

### ISSUE THREAD

**Issue by jdmerinor** [tanujnotes/Olauncher#471]
Hi!

I'm a constant user of Olauncher and I love it! Lately I've been having issues with the filtering of the apps, sometimes even though you are typing it is not filtering the results, but if you finish typing it will open the app.

I'm using Android 14 and a Samsung Galaxy s21 fe phone. I'm attaching a video that shows the problem. 

https://github.com/tanujnotes/Olauncher/assets/14632949/8b20c699-faf1-4de7-a93b-b19a39d5811e

**Comment by tanujnotes** [comment]
This is Android 14 specific issue. Haven't been able to find a permanent solution but turning off the battery optimization helps. Check out the About page in settings for more details.
