### ISSUE TITLE
request for feature

### ISSUE THREAD

**Issue by jaggernaut007** [tanujnotes/Olauncher#474]
Can we please have the search in app list to search the web. Like a quick search that, if the app is not found, searchs for the app on the web, rather than search for the app on the play store.

Would that be possible? 
![Screenshot_20240511-144529](https://github.com/tanujnotes/Olauncher/assets/39733172/0e1f8e4c-cb35-4cad-aade-b10cb9e859dc)

**Comment by tanujnotes** [comment]
It already supports !bang search.

**Comment by jaggernaut007** [comment]
Super cool! Guess I unlocked a hidden feature haha. Thanks!

**Comment by tanujnotes** [comment]
@jaggernaut007 Please check out the About page in the settings for more tips.
