### ISSUE TITLE
[Feature Request] Change font size to fit more apps in the main screen

### ISSUE THREAD

**Issue by JeremieSpiesser** [tanujnotes/Olauncher#48]
Hi, I just switched from "before launcher" (propriatery android launcher) to 0Launcher and I love the UI and the fact that it's open source.

However, as I usually use more than 8 apps on a daily basis (about 14 with all the different messaging apps) I miss the ability to see more than 8 apps on the main screen.

One way to make this possible would be to put in the settings and option to decrease the font size, so that more apps can fit and be pinned on the main screen.

~~Another thing that I would love to see is the ability to still see the top status bar, so that I can see if I'm connected to wifi, 4G or in airplane mode. This could ideally be toggled in the settings menu.~~
EDIT : I didn't have the latest version of the app so this last comment is irrelevant now

Cheers

**Comment by tanujnotes** [comment]
Users have access to 8 apps on home screen and 2 more by swiping left and right. This works well for most users while maintaining the simplicity so making any changes in it is not a priority. I hope you understand.

Thank you.
