### ISSUE TITLE
Keyboard becomes Green shaded

### ISSUE THREAD

**Issue by PraveenRajSG** [tanujnotes/Olauncher#487]
I installed on OnePlus 10R. The keyboard became red and green shaded depending on the wallpaper colour I suppose. The default colour came back only after I uninstalled and restarted the phone. 

Kindly look into this issue.

**Comment by tanujnotes** [comment]
This is not related to the launcher.
Quite possibly, Material You theming is ON in your phone. So apps, keyboards, etc, are changing color based on the wallpaper. Please Google how to turn it off from the phone settings.

**Comment by PraveenRajSG** [comment]
Understood and solved the issue. Thank you for taking time and clarifying. 🙂
