### ISSUE TITLE
Allow hiding status bar

### ISSUE THREAD

**Issue by ytsejam1138** [tanujnotes/Olauncher#49]
I prefer the UI in pre-v2.1. Could we have the option to turn the status bar off and show the larger time and date like in v2 0 and prior versions?

**Comment by Z7AL3G37VZ7** [comment]
I agree, had to go back to 2.0

**Comment by tanujnotes** [comment]
I'm waiting for more user feedback and will decide based on that. I suggest that you guys use it for a week and then let me know how you feel. Speaking from personal experience, it takes a few days to get used to.

**Comment by tanujnotes** [comment]
Please update to v2.4
