### ISSUE TITLE
[feature request] Include widgets

### ISSUE THREAD

**Issue by MajdWardeh** [tanujnotes/Olauncher#491]
Hi,

Thank you very much for this great launcher. It's really helpful!

Is it possible to request a feature of being able to add widgets to the home screen? there are some widgets that could be very useful e.g the ones for tracking the progress of a habit or the ones for smart devices.

Thanks in advance, :)

**Comment by tanujnotes** [comment]
Hi, widgets are available in the pro version called Pro Launcher. Please check out the About page in the settings for more details.
