### ISSUE TITLE
Remove the search function.

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [tanujnotes/Olauncher#493]
All I need is for the Apps to be sorted in alphabetical order, there is no need to always auto focus the search.
This is a minimalistic app, so I should have the ability to enable or disable the search function.
I have maybe 15apps in total because the whole idea of Olauncher is being minimalistic, why would I need a search for 15 apps?

I have it installed on phone and my tablet. All I need is a checkbox
`[_] Enable Search`

**Comment by tanujnotes** [comment]
If your complaint is regarding the keyboard popping up, you can disable it from the Olauncher settings.
