### ISSUE TITLE
[Bug] Apps alignment not working on menu

### ISSUE THREAD

**Issue by renzodus** [tanujnotes/Olauncher#499]
### Issue
The app alignment does not seem to come back from right in the menu.

### Bug reproduction
- Access OLauncher settings.
- Select app alignment to right.
- Go back and check that the main page and menu apps are aligned correctly.
- Access OLauncher settings again and set alignment to center or left.
- Go back and check that the main page apps are aligned correctly.
- Enter the menu and the apps would still be sligned to the right.

![main page](https://github.com/user-attachments/assets/98e2f7a1-ecde-430e-b2c5-84e15337cbf7)

![menu](https://github.com/user-attachments/assets/6c311054-fe77-4700-9780-a92797d5f42c)

**Comment by tanujnotes** [comment]
You have to long press the 'Center' text in the settings to change the app drawer alignment. Check out the About page in the settings for more details.
