### ISSUE TITLE
[Feature request] Add more items to the home screen 

### ISSUE THREAD

**Issue by teemue** [tanujnotes/Olauncher#5]
I'm looking for an FOSS alternative for my current launcher. OLauncher is superb but I'd like to have more items on home screen. There are more than four apps you need in daily life (commuting, bank, post, navigation) which shouldn't be behind too many taps :)

**Comment by tanujnotes** [comment]
It will be added in the next update which should be available by this weekend.

**Comment by teemue** [comment]
Awesome-thanks!

**Comment by tanujnotes** [comment]
Please update the app. You can now up to 6 apps on home screen.

**Comment by SelfhostedPro** [comment]
Why limit it to 6? I have around 10 apps I frequently use and plenty of screen real estate. Is there any way it could be increased?

**Comment by tanujnotes** [comment]
You can swipe left and right to launch 2 more apps of your choice. Now you have 8 customizable apps and I hope that's enough for you. 

Number of apps are limited to maintain the minimal design of the app. Earlier it was only 4. Also, too many apps on home screen may cause overlapping with the date on smaller screens. 

There's no strong reason to keep it at 6. It works for most people and looks good so we're sticking to it for now. That may change in the future.

**Comment by SelfhostedPro** [comment]
Would you consider folders to be too much clutter? Just thinking of ways to keep it minimal but add functionality.
