### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by williamson91** [tanujnotes/Olauncher#50]
Please add the ability to translate the application to transifex or crowdin.

**Comment by Dats1K** [comment]
I registered now, and i might help with translate on russian:)

**Comment by Heike-HS** [comment]
I would do the translation to German

**Comment by HipyCas** [comment]
I could help with Spanish and Galician! Hope to be able to help with it soon! Actually, seems like translation has been left behind.

**Comment by Ilithy** [comment]
@williamson91 @HipyCas @Dats1K and @Heike-HS This is a good idea, but the easiest way to be able to offer a translation to the developer is by sending a pull request, feel free, if you have the motivation, to fork Olauncher, perform the translation of the string.xml file, then make a PR to the main branch of Olauncher, This will greatly help new non-English speaking users in advance thank you <3

(Message from a simple user)

**Comment by Heike-HS** [comment]
Tried, but did not manage to do as you suggest.

**Comment by Ilithy** [comment]
> Tried, but did not manage to do as you suggest.

I can surely help you :), either by giving you the procedure to do a PR (I'll make you a little tuto to give you the steps), or, if it's easier for you, make the translation of the lines of the file [string.xml.txt](https://github.com/tanujnotes/Olauncher/files/7977310/string.xml.txt) _(don't worry about the .txt format, it's for easy transmission via github, which doesn't accept .xml by this way)_

Then send it to me, I will add it to my fork, and do the PR, You decide (this applies to anyone who wants to, of course)

**Comment by Heike-HS** [comment]
The file string.xml.txt is perfect! I'll do the translation in this file and then let you do the rest. ;-)

**Comment by Ilithy** [comment]
we do it like that :-)

**Comment by lichingyun** [comment]
@tanuj italian translation is ready :D

1 feb 2022 10:58:18 Ilithy ***@***.***>:

**Comment by Heike-HS** [comment]
What does that mean:
"lock layout description to be used a unique id to lock screen"

**Comment by Ilithy** [comment]
If I'm not mistaken, it refers to Olauncher as the device screen lock processing agent.
_(I did not find this in the Olauncher interface)_

**Comment by Heike-HS** [comment]
The German translation is ready.
[string.xml_ger.zip](https://github.com/tanujnotes/Olauncher/files/8099357/string.xml_ger.zip)

**Comment by Ilithy** [comment]
@Heike-HS Thanks a lot, I'll take care of it quickly; it's really great to be able to use an app in your own language, thanks to you, German speaking users will appreciate <3

**Comment by Ilithy** [comment]
Done on #160

**Comment by Ilithy** [comment]
@lichingyun Sorry I don't see any file to recover in your message of february 1st, otherwise yes of course, I'll add with pleasure your work with mine and the one of @Heike-HS, let me know if you still have the strings.xml file translated :), it will be added quickly

**Comment by lichingyun** [comment]
> @lichingyun Sorry I don't see any file to recover in your message of february 1st, otherwise yes of course, I'll add with pleasure your work with mine and the one of @Heike-HS, let me know if you still have the strings.xml file translated :), it will be added quickly

@Ilithy I am using my phone now and I don't know how to upload the file here :( I need some minutes to open my laptop

**Comment by Ilithy** [comment]
@lichingyun Don't stress, you have all the time you need, I am available when you need me

**Comment by Ilithy** [comment]
I'll get right on it, thanks <3

**Comment by Heike-HS** [comment]
Did you see the Turkish translation, done by Gaometri?

**Comment by Ilithy** [comment]
Hi @Heike-HS _Sorry, I missed the notification of your message_
Great! Thanks for the hard work!
I'll take care of it quickly, of course;
Indeed, I had noticed the work (and the outcome) of @gaometri, do you think it is useful to propose him to do the PR too?
 I don't mind :-)

**Comment by Heike-HS** [comment]
If you could do so? I'm sure it would be useful. :-)

**Comment by Ilithy** [comment]
Of course, I will offer it to him, thank you for highlighting this

Ps: your translation is in the PR.

**Comment by Agente-Xx** [comment]
translation into Portuguese-Brazilian

[strings.xml.pt-br.zip](https://github.com/tanujnotes/Olauncher/files/10429465/strings.xml.pt-br.zip)

**Comment by Livio78** [comment]
Hi, I have downloaded the Italian translation xml file. Once you download Olauncher, you can have a short tutorial on how to insert the translation file into Olauncher. Thank you, I hope to have the tutorial soon.

**Comment by Livio78** [comment]
In the next update, would it be possible to have the ITALIAN LANGUAGE? Thank you

**Comment by tanujnotes** [comment]
#324
