### ISSUE TITLE
Google pixel glitches

### ISSUE THREAD

**Issue by Marc-Morcos** [tanujnotes/Olauncher#500]
When I swipe up to search apps, sometimes keyboard comes up but no search bar.
Also when I swipe up from to manage open apps, olauncher merges with most recent app into strange transparent window.

This is on google pixel (both 4a and 8)

**Comment by tanujnotes** [comment]
This can be fixed with changing the battery settings. Please check out the About page in the settings for more details.

**Comment by codeinabox** [comment]
I have this problem too, and have enabled "Allow background usage", though I can't find a setting "Unrestricted (No restrictions".

**Comment by tanujnotes** [comment]
@codeinabox  Tap the "Allow background usage" text.
