### ISSUE TITLE
Recent app gesture 

### ISSUE THREAD

**Issue by solankybasant** [tanujnotes/Olauncher#506]
Give you please as recent app opening using sliding left or right on the home screen

**Comment by tanujnotes** [comment]
Why?

**Comment by solankybasant** [comment]
Opening apps from the left and right swipe and just write a few char and the app is opened is such a cool thing, it makes me faster, but to open recent activity it takes Lil longer
That's why I asked.

**Comment by tanujnotes** [comment]
That's an Android issue and out of scope for this launcher.

**Comment by solankybasant** [comment]
Thanks for your time.
