### ISSUE TITLE
Navigation menu disappears when battery saving mouse is enabled

### ISSUE THREAD

**Issue by Evertvz** [tanujnotes/Olauncher#509]
Hello, 

On Android 14, whenever my phone goes into battery save mode it will remove the three button navigation bar from the bottom of the screen. This issue did not exist with the default launcher. 

A workaround is to go into settings, enable gesture navigation and immediately put it back to three button navigation.

Thanks

**Comment by tanujnotes** [comment]
Xiaomi phones do not support navigation gestures with downloaded launchers.

**Comment by Evertvz** [comment]
This is not a Xiaomi phone but a Fairphone, and both gesture and navigation buttons work fine generally speaking.

**Comment by tanujnotes** [comment]
Olauncher has no control over the bottom navigation. Could you please install any other launcher and see if the issue still exists?

**Comment by Evertvz** [comment]
You're correct. I tried with another launcher and the default and both give the issue. So this is not related to your code. Thanks!
