### ISSUE TITLE
Need to double click app to open

### ISSUE THREAD

**Issue by diogodh** [tanujnotes/Olauncher#51]
After switching to home with the gesture, if i click immediately in any app name of the launcher home screen it does nothing when it was suppose to open the app. So i need to click again to open.
This only happena when i click fast after the home screen appears.
I believe this is related to google assistant on pixel devices (with that bottom borders flashing) but i am not sure.

**Comment by tanujnotes** [comment]
If anyone else is facing the same issue, please comment. Need more info because I'm not able to replicate this.

**Comment by diogodh** [comment]
If you need any kind of log or debugg just tell me and i will do it.
Here i uploaded the problem. U can see that after it use the home gesture to go to the launcher, if i click on the app name fast, it doesnt open it.
Maybe a pixel or android 11 thing, didn't have it on my OnePlus

Video https://streamable.com/auw0c6

**Comment by tanujnotes** [comment]
> Video https://streamable.com/auw0c6

Link not working.

**Comment by diogodh** [comment]
Working here, both in Android and Windows (Firefox)... :(

**Comment by tanujnotes** [comment]
Unable to replicate and haven't heard anyone else having this issue.
