### ISSUE TITLE
Release v4.3.3 on F-Droid

### ISSUE THREAD

**Issue by alpha-tango-kilo** [tanujnotes/Olauncher#512]
As far as I can see, the latest version hasn't yet hit F-Droid, does this need a nudge?

Really looking forward to having a bug I raised fixed, I've been waiting & checking!

Thanks for all your work on Olauncher ❤

**Comment by tanujnotes** [comment]
It usually takes 2-3 days, sometimes longer.

**Comment by alpha-tango-kilo** [comment]
Ah okay no problem, thanks for letting me know!
