### ISSUE TITLE
Why appears that emoji (wich i dont put here)

### ISSUE THREAD

**Issue by MadhouseBox** [tanujnotes/Olauncher#515]
![Screenshot_2024-09-17-22-12-14-412_app olauncher](https://github.com/user-attachments/assets/4a4f90ec-ea18-42bf-aac6-4e0cf13a2c4e)

I tried renaming, but doesn't work. It's only for that app. I tried in other phone and it's the same, so... It's something on purpose in the launcher?

Sorry for my bad English

**Comment by tanujnotes** [comment]
It indicates newly installed apps. It'll automatically disappear in an hour.
