### ISSUE TITLE
[Feature Request] - Calendar Widget

### ISSUE THREAD

**Issue by fabiantorrestech** [tanujnotes/Olauncher#516]
Hello,

I'm someone who suffers from severe ADHD to the point where I will forget daily tasks frequently. **One thing that has been tremendously helpful for this is adding a calendar widget to my homescreen (specifically the schedule view one) on the same page as the homescreen.**

Is possible to add in a custom calendar widget like this and the ability to make it grayscale to match the rest of the black/white OLauncher aesthetic? I usually run my phone in grayscale mode too to help with eliminating distractions.

This is the 1 thing that is stopping me from daily driving OLauncher, but if I were able to add in this 1 widget I use, then I think I would have my endgame distraction-free phone setup.

Below is what my current solution is with Lynx Launcher (all other pages and app drawer disabled, only app searching allowed on swipe down):
![Screenshot_20240920-120217](https://github.com/user-attachments/assets/eb48849f-5d2b-41b3-9493-d9f606926305)

**Comment by tanujnotes** [comment]
No plans to make any changes in Olauncher. Widgets and many other features are available in the pro version called Pro Launcher. Let me know if you want a free trial.
