### ISSUE TITLE
Tries to opens Play Store again and again

### ISSUE THREAD

**Issue by diwash007** [tanujnotes/Olauncher#517]
When not connected to the internet, my device tries opening play store again and again. It tries to open the olauncher page on play store. It restricts me from doing each and everything by going on loop of opening play store.
It doesn't happen everytime when I am offline ... but I face it most of the time.

**Comment by diwash007** [comment]
> I'm recently experiencing the same issue and I'm most of the time offline 😓, is this caused by a recent update?

Yeah since few recent updates .. I have been facing the issue
Previously it was fine
I first thought it was some kind of malware on my device .. but later found out it was the launcher itself.

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/issues/504#issuecomment-2374255541

**Comment by tanujnotes** [comment]
Fixed in the latest update v4.3.4.

**Comment by diwash007** [comment]
Thank you, Tanuj

> Fixed in the latest update v4.3.4.
