### ISSUE TITLE
[Feature Request] Timer when starting specific app

### ISSUE THREAD

**Issue by freezy63** [tanujnotes/Olauncher#518]
Hey, I would suggest a feature, that I can select a app for example Instagram, and activate a Timer every time I open it it would be great if I can decide the seconds the time waits until the apps opens.

Usecase:
If someone opens a specific app brianless like tiktok or Instagram he can rethink it while the Timer is counting down. The timer option is optimal and has to be activated by the user.

**Comment by tanujnotes** [comment]
This won't be a part of Olauncher but I'm working on a separate app for this. That way, users of any launcher would be able to use it. It won't be free or open source though.
