### ISSUE TITLE
[Feature Request] Change Font Color

### ISSUE THREAD

**Issue by ytsejam1138** [tanujnotes/Olauncher#52]
Ability to change font color. The white sometimes blends into certain wallpaper.

**Comment by subnut** [comment]
@tanujnotes I think I saw somewhere that It would be better if the Font could be controlled more precisely, (e.g. changing font face, size, bold, italic, etc)

I think that it's a reasonable request to make, after all _text_ is the primary interface of this app...

**Comment by tanujnotes** [comment]
If default appearance is working well for most people, there's no need to provide tons of options.
