### ISSUE TITLE
Android Predictive Back

### ISSUE THREAD

**Issue by erbenjak** [tanujnotes/Olauncher#531]
I know this does not impact many users just yet, but would it be possible to get support for android predictive back?

Thanks in advance!

**Comment by florianloewen** [comment]
Please revisit this issue.

"For apps targeting Android 16 or higher and running on an Android 16 or higher device, the predictive back system animations (back-to-home, cross-task, and cross-activity) are enabled by default. "

https://developer.android.com/about/versions/16/behavior-changes-16
