### ISSUE TITLE
tapping on the clock opens camera app instead of clock app

### ISSUE THREAD

**Issue by SirKaon** [tanujnotes/Olauncher#537]
title says it all.

tapping on the homescreen clock used to open the clock app, but now it opens camera instead... strange, is there a setting I'm missing?

**Comment by tanujnotes** [comment]
Long press on the date/time to select which apps to open on click. Check the [About](https://tanujnotes.substack.com/p/olauncher-minimal-af-launcher) page in the settings for more tips.
