### ISSUE TITLE
"Device locked by admin" error at login after double tap to lock screen used

### ISSUE THREAD

**Issue by vtkhatri** [tanujnotes/Olauncher#54]
After I lock device using double tap feature,
Fingerprint cannot unlock the phone.

Error message `Device locked by admin` is shown at login screen.

![image](https://user-images.githubusercontent.com/30864864/101944597-fc020200-3c12-11eb-8e4e-b1001ec73ec2.png)

**Comment by tanujnotes** [comment]
When you turned ON double tap to lock, did you see the instructions and follow them?
