### ISSUE TITLE
Feature request: User feedback when search found an app

### ISSUE THREAD

**Issue by jgoedde** [tanujnotes/Olauncher#546]
I know, this project aims to be very minimalistic and that's great. But one thing that I stumbled on was the search function.

When there is exactly one app matching your search input, the app instantly opens. I think you could have a small delay before opening the app and maybe add a very short vibration so the user is not so surprised by what is going to happen next.

In my case, I am typing and all of a sudden the keyboard disappears and the app instantly opens, I was not expecting that. So in my opinion a small visual or haptic feedback when an app was found and is about to open on the search drawer would be great.

**Comment by HeCodes2Much** [comment]
You could also disable that feature if you don't like it.

**Comment by jgoedde** [comment]
What do you mean by "disable it"? Are you speaking of the auto keyboard feature?

This issue is suggesting a new feature or at least an adjustment to the app search, so I am not sure what exactly you are suggesting now.

**Comment by HeCodes2Much** [comment]
You can disable the app search to not auto open apps when only 1 app is left that way you wouldn't be surprised when it does.

**Comment by OndrejKulhavy** [comment]
The instant app opening feature of the search function is the main reason I use this launcher. You can always press `space` before entering your query to disable the automatic opening.

**Comment by tanujnotes** [comment]
I've experimented with vibration based feedback earlier in different parts of the app.

People hated it.
