### ISSUE TITLE
Android 15 Private Space

### ISSUE THREAD

**Issue by Charcoxl** [tanujnotes/Olauncher#548]
Any planned support for Private Space, introduced in Android 15?

**Comment by tanujnotes** [comment]
I haven't looked into it yet and won't be able to for some time. Maybe next year.

**Comment by hashworks** [comment]
I guess this could be integrated in the "Hidden Apps" Feature. You could add a "Lock/Unlock Private Apps" at the bottom of the Hidden-Apps-List activity and list the private apps if it's unlocked?

Also, the long-press-menu for apps needs to include "move to private space", maybe just trigger it on "hide" long press.

Alternatively "Hidden Apps" could just become Private Space on Android 15+.
