### ISSUE TITLE
F-Droid can't build 

### ISSUE THREAD

**Issue by licaon-kter** [tanujnotes/Olauncher#55]
Tags don't point to the updated versions eg. `v2.5` should point to 7ab87026fd78eab0eae241ec10345ed76e3dde9f  where you've actually updated the version

Could you please retag?

Ref: https://f-droid.org/wiki/index.php?title=app.olauncher/lastbuild_24&oldid=283993

**Comment by tanujnotes** [comment]
Resolved. Latest version is available on F-Droid.
