### ISSUE TITLE
Add Support For Android's Gesture Navigation

### ISSUE THREAD

**Issue by RickAndTired** [tanujnotes/Olauncher#57]
Feature Request: Add support for Android's Gesture Navigation

Currently Olauncher only supports 3-button navigation and 2-button navigation

![Screenshot_20201218-223255](https://user-images.githubusercontent.com/53553229/102682830-476f5f80-4181-11eb-8e07-c73df1c1dc89.png)

**Comment by jorisvandijk** [comment]
Gesture navigation works fine on my device. (OnePlus 7 Po, with LineageOS for MicroG). I do not think the launcher has any effect on system navigation. Are you sure it only does not work with this launcher?

**Comment by tanujnotes** [comment]
https://play.google.com/store/apps/details?id=com.digitalwellbeingexperiments.desertisland

This is a minimal launcher by Google called Desert Island. Try it on your device and please update here if gesture navigation is working for Desert Island on your phone or not.

**Comment by RickAndTired** [comment]
@jorisvandijk I'm sure, if I click the info button it says "Not supported by your default home app, Olauncher"

@tanujnotes Gesture navigation is disabled with Desert Island also

The default home app "Quickstep" does work with Gesture navigation
I'm on a stock Android One phone with Android version 10

**Comment by tanujnotes** [comment]
For third party launchers, gesture navigation is working well devices some devices and not on others. It will be fixed either by Google or your device manufacturer through an update. I've looked into this issue but so far I haven't found any solution and I'm not sure if there's anything I can do.

**Comment by RickAndTired** [comment]
Thanks for the update, I'll close this then and hope they fix it.

I'm thinking of getting a Pixel phone in the future, anyone happen to know if Gesture navigation works on those with Olauncher?

**Comment by tanujnotes** [comment]
@RickAndTired As far as I know, it works well on Pixel phones (and OnePlus/Xiaomi/Oppo). Most complaints are coming from Samsung users.
