### ISSUE TITLE
[Feature Request] Add the ability to hide apps

### ISSUE THREAD

**Issue by arneschlag** [tanujnotes/Olauncher#6]
There a couple of apps that i use a lot, so they are on the mainscreen. Some apps I use rarely, so then i can swipe up and choose on of them. 

But some apps i never used and probably will never use them. It would be awesome to hide those apps completely, so that they will not appear.

Maybe you this feature could be added in the settings section. If there is no time for that, i would also programming that and making a merge request, but i dont have any Kotlin experience or android programming experience at all, so it would be a nice task for me to start into this section.
But you can deside.

**Comment by tanujnotes** [comment]
Hi, I understand the desire to have a fine grained control on the app list, but, this is not a feature that a lot of people require so I won't be adding it in the app at least in the near future. But that doesn't mean you can have this on your phone.

There's function called ```getAppsList(context: Context)``` in ```Utils.kt``` file and that's where you have to make the changes to achieve what you want. Fork the repository, make the changes and install it on your phone. Please let me know if you need more help. You can message me on [Twitter](https://twitter.com/tanujnotes/).

**Comment by arneschlag** [comment]
Thanks a lot, i can understand that this ability is not required by many. I look into the function, maybe I comeup  with clean solution, then i would create a pull request.
You could look into the code and decide whether this feature/code should be added or not.
If I have any questions about your code, is there a other way to contact you, since i am unable to communicate over twitter?

**Comment by tanujnotes** [comment]
Email: thetanuj1@gmail.com
