### ISSUE TITLE
[Feature Request] Plain white background

### ISSUE THREAD

**Issue by jmbmkn** [tanujnotes/Olauncher#60]
I am using Olauncher on a phone with a black and white e-ink screen (Hisense A5 precisely) and to work optimally it needs a contrast. A plain white background and black text is ideal.
I looked throught the Issues and couldn't see this being dimissed as a possible feature. I accept this is probably a fringe use case, but there may be others who would like no wallpaper for zero distractions.

**Comment by tanujnotes** [comment]
This feature will be added in future updates.

Fascinating to hear that Olauncher is running on an e-ink display. If possible, please send me screenshots/images on Twitter. Thank you.
https://twitter.com/tanujnotes

**Comment by waynehoover** [comment]
Any updates on this?

**Comment by tanujnotes** [comment]
@waynehoover  You can change the Theme in Olauncher settings to change the text color to black of white.
