### ISSUE TITLE
Globally rename apps

### ISSUE THREAD

**Issue by glpzzz** [tanujnotes/Olauncher#62]
It's possible to rename apps for home screen but isn't possible to rename it for the long apps list. In some cases, I would like to rename apps (as in Aero Launcher)

The issue is not by then launcher itself but by the apps: Facebook Lite and Messenger Lite appears as "Lite". The Xiaomi apps have Mi as prefix. If I want "Mi Calculator" I need to scroll to "M" or type "Cal..."

The launcher could help with this although I understand it's not it's responsability (as a minimal launcher)

**Comment by tanujnotes** [comment]
Adding a global renaming feature will require adding a database in the app. It will increase the app size and overall complexity. That's why this feature is not available. I hope you understand. Thank you for using Olauncher.
