### ISSUE TITLE
[Feature Request] Landscape mode

### ISSUE THREAD

**Issue by CactiChameleon9** [tanujnotes/Olauncher#63]
I am using olauncher in a tablet, and I wonder if you could provide an option to disable the portrait lock. A landscape optimised layout would be nice, but that can be lots of work and therefore just an option is fine (sorry for the rare usecase)

Edit: the app does work fine in landscape mode, I checked using tap and turn from fdroid

**Comment by tanujnotes** [comment]
[Olauncher-v2.6-landscape.zip](https://github.com/tanujnotes/Olauncher/files/5785654/Olauncher-v2.6-landscape.zip)

Proper tablet support will be added at some point but until then, here's a apk with portrait mode disabled. Unzip it first. Thank you.

**Comment by CactiChameleon9** [comment]
Thanks!
