### ISSUE TITLE
Bug? Cannot change display timeout in Android 10

### ISSUE THREAD

**Issue by Heike-HS** [tanujnotes/Olauncher#66]
When I have Olauncher as active launcher, it is not possible to change display timout to another value than 30 seconds. In fact, I 
 can change, for example to 5 minutes, but when I leave the settings the value goes back to 30 seconds. This problem does not exist with the standard launcher (Quickstep), Nova or even Olauncher lite. Only when Olauncher is active.

**Comment by tanujnotes** [comment]
Yes it is a bug. Please update to the latest version v2.6 and let me know if you're still having this issue.
Latest version is not yet available on Play Store or Fdroid so you'll have to download the apk from the latest release.

**Comment by Heike-HS** [comment]
It works fine now. Thank you!
