### ISSUE TITLE
Check for update

### ISSUE THREAD

**Issue by diogodh** [tanujnotes/Olauncher#69]
For those who use the apk from github, could be useful a small and fast notification (in the form of toast notification or a small symbol) to inform that a new apk is available.

**Comment by tanujnotes** [comment]
Until this gets done, people can follow me on Twitter for all the latest update about Olauncher... and other apps that I might be working on. Thank you. 

https://twitter.com/tanujnotes

**Comment by Ammako** [comment]
Alternatively, for those who have a Github account, you can click Watch at the top-right, go under Custom, and check Releases, then Apply. This will send you email notifications when new releases happen, with a link to the release page so you can download the new apk.
