### ISSUE TITLE
[Feature request] Ability to change background

### ISSUE THREAD

**Issue by arneschlag** [tanujnotes/Olauncher#7]
An option to change the background in the settings, so that you dont have do go in the devices settings. 
Because the background is a primary part of the launchers design, it would makes sense to addthe option in the launcher.

**Comment by tanujnotes** [comment]
I agree that it would be a lot more convenient. But I also think that manually changing wallpaper is not something that people do frequently so maybe this feature is not a priority.
I'm planning to add daily wallpaper auto update at some time. I hope that that would be enough for most people.

**Comment by arneschlag** [comment]
That would be a nice feature. But how would it work with offline images that you can select or an online image, like image of the day from unsplashed?

**Comment by tanujnotes** [comment]
Images will come from UnSplash. They'll be updated once a day whenever the Internet is available. I'll think about offline image support later.
