### ISSUE TITLE
Olauncher version

### ISSUE THREAD

**Issue by lichingyun** [tanujnotes/Olauncher#75]
Hello, in Github and inside the Playstore Olauncher version number is 2.9, in Fdroid version number is 2.7
do you have plan to update the Fdroid version?

**Comment by tanujnotes** [comment]
F-Droid should automatically fetch the latest release from Github which is v2.9. That's how it works. Not sure why it didn't this time. I'll drop them a message and if anyone knows what to do in this situation, please let me know. Thank you.

**Comment by lichingyun** [comment]
Hello @tanujnotes and thank for your answer.
Olauncher is absolutely perfect and I can pay for it (better in Fdroid or Github or in app purchase, not in playstore)
