### ISSUE TITLE
2 "shadow" 

### ISSUE THREAD

**Issue by lichingyun** [tanujnotes/Olauncher#76]
![Screenshot_20210216-225828](https://user-images.githubusercontent.com/79099214/108127565-b26ae300-70ab-11eb-8b8c-caa572a10492.png)
Hello, In the upper and lowest part of the homescreen there are 2 "shadows"( I don't know how to named these).
In the next update is possible to " delete" the shadows?
I think to see the clear wallpaper in Olauncher is more beautiful

**Comment by tanujnotes** [comment]
Hi, I'd need to know about the phone and Android version you're using.

**Comment by lichingyun** [comment]
Hi Tanuj, sorry for the lack of info, I'm using Android 11 (ArrowOs) on a Xiaomi Redmi Note 5 Whyred

**Comment by lichingyun** [comment]
Hi I forget to write I am using version 2.9 from github.
The "shadows" are also in version 2.7 from Fdroid

**Comment by lichingyun** [comment]
the "shadows" are present also in version 3.0

**Comment by lichingyun** [comment]
Hello Tanuj,

I discover the "shadow" in the upper part of the screen is not present using Tinybit Launcher or Kiss Launcher

**Comment by lichingyun** [comment]
but I like use Olauncher more and more... This is really the best launcher for android.

@tanujnotes I discover the 2 "shadows" are also present using the light theme and in the upper part of the screen the icons and the clock remains white instead of black

**Comment by lichingyun** [comment]
![Screenshot_20210423-065753](https://user-images.githubusercontent.com/79099214/115820533-4b4a1180-a401-11eb-904e-fd828fe6c038.png)
Here I show you a light screenshot from my phone.
Thanks for your work @tanujnotes 🙏

**Comment by tanujnotes** [comment]
I'll see if I can fix this in next update. I'm really sorry about the inconvenience. Thank you for your patience.

**Comment by lichingyun** [comment]
> I'll see if I can fix this in next update. I'm really sorry about the inconvenience. Thank you for your patience.

No problem @tanujnotes take your time, I can wait 🙏 always thank you

**Comment by lichingyun** [comment]
Hello Tanuj, any news?
here in South Europe we enter in the fist days of summer, there is too much sunshine and a totally white Olauncher can help my eyes 😇

**Comment by lichingyun** [comment]
Hello Tanuj,
in the play store I find Takan Launcher, their developers have resolved the "shadows" problem... but is not open source...
Maybe this can help, have a nice day

**Comment by lichingyun** [comment]
![Screenshot_20210610-163415](https://user-images.githubusercontent.com/79099214/121544729-3b66ab00-ca0a-11eb-9353-0b4d81e249d5.png)
hello Tanuj
today I play with some light launcher and I discover the latest version of Olauncher Light doesn't have the upper shadow! see my screenshot,
can this be implemented in the Olauncher complete version?
For me this can be the best 🙏🙏🙏

**Comment by lichingyun** [comment]
and maybe this can help to delete the bottom "shadow" in having a total white phone 😍

**Comment by lichingyun** [comment]
@tanujnotes any news? 🙏

**Comment by tanujnotes** [comment]
Hey man, the problem is that I can't reproduce this issue in any of the phones I have access to.  That's why I'm unable to fix it. Not sure what to do here.

**Comment by lichingyun** [comment]
ok pal, sorry for asking 🙏 this is the only problem in Olauncher.
Maybe is a rom's problem 🤔

**Comment by lichingyun** [comment]
Hi Tanuj, I am back here in gihub after some weeks, which kind of PR I can send you?

**Comment by TBog** [comment]
I am the developer of [Tinybit Launcher](https://github.com/TBog/TBLauncher)
If you have the fullscreen decor flag and a hidden keyboard you can make the navigation bar and the notification bar go away.

**Comment by tanujnotes** [comment]
@TBog What do you mean by nav bar will go away? Will it become transparent or completely hide away? We only want to make it fully transparent. A PR will be highly appreciated.

**Comment by TBog** [comment]
I'm not sure I can write Kotlin so a PR is unlikely but I'll  link to some relevant code from my launcher.

**Comment by lichingyun** [comment]
hello friends,

I can confirm there is this "2 shadows" problem also using the official lineage os for xiaomi whyred

**Comment by lichingyun** [comment]
@tanujnotes maybe I find a solution for this problem:

Here is a related StackOverflow answer:
You just need to disable auto system content protection by this code <item name="android:enforceNavigationBarContrast">false</item> in your theme.

I am not a programmer but maybe this code can help you 🙏
what do you think? have a nice day

https://stackoverflow.com/a/65941609

**Comment by lichingyun** [comment]
@tanujnotes I resolve this problem updating my Xiaomi Redmi Note 5 Whyred  to Android 12 (the rom is Arrow Os) now the shadows are gone and I can use the beauty of Olauncher at 100%
![Screenshot_20220310-195811_Olauncher](https://user-images.githubusercontent.com/79099214/157766181-c67db479-adbd-4571-aaec-76bc5a03fc61.png)

Now I need to configure the homescreen 👍

**Comment by vljukap98** [comment]
I hope I understood the issue correctly. @lichingyun if you put "Show status bar" field value "On" you'll have the top shadows, or whatever you're calling them. Also if you find on your phone settings using gestures instead of the navigation bar which inevitably shows the second shadow you're complaining about.
