### ISSUE TITLE
The Calendar shortcuts don't work

### ISSUE THREAD

**Issue by lichingyun** [tanujnotes/Olauncher#77]
Hello, until today the shortcut for the calendar (tapping the date) works very well, and open the Etar calendar app from Fdroid.
Today I decide to use the default calendar app built in the rom (Simple Calendar) but the shortcut isn't working anymore.
I have restart the phone but nothing change.
I am using Olauncher on a Xiaomi Redmi Note5 Whyred with ArrowOs (android 11)

Edit: if I install Google Calendar or Etar ( this one from Fdroid) the date shortcut work very well

**Comment by tanujnotes** [comment]
Can you please provide the download link for the calendar app that isn't working? I'll try to fix it.

**Comment by lichingyun** [comment]
https://f-droid.org/packages/com.simplemobiletools.calendar.pro

Hello this is the calendar app that is not working

**Comment by tanujnotes** [comment]
Hi, please try the latest release (v3.0) and close the issue if it's fixed. Let me know if it's not.

**Comment by lichingyun** [comment]
> Hi, please try the latest release (v3.0) and close the issue if it's fixed. Let me know if it's not.

Many thanks Tanuj! the latest release work perfectly, I can use my rom default calendar without problems, many thanks!

**Comment by lichingyun** [comment]
issue closed, always thanks Friend
