### ISSUE TITLE
Apps with shortcuts

### ISSUE THREAD

**Issue by EffToyz** [tanujnotes/Olauncher#79]
Some of apps using shortcuts like syncthing-fork and syncthing-fork camera (something like command line with extra parameter). It is the same app, but you can tap one of them and get different function. Problem is that Olauncher uses same shortcut on both names (usually not the one I want). markor, for example, opens quick edit and there is no way to open files list.

I tried to hide on the shortcuts, but then Olauncher hides both options.

**Comment by tanujnotes** [comment]
Hi, I'm aware of this issue and the solution for this issue. It will take some time though. Stay tuned and thank you for using Olauncher.
