### ISSUE TITLE
Disable clock and calendar links

### ISSUE THREAD

**Issue by daetoCh0** [tanujnotes/Olauncher#80]
I'm interested in a configuration to disable the links for clock and calendar ("Settings > Show date time"). I like the visual cue of date/time by itself for its information, but not for launching an app.

I use the the datetime current values on other platforms without ever accessing an app, too. My desire is to keep the home screen minimal with only the Phone and Messages app launchers available for interaction and no other links.

The Olauncher is, however, a launcher, so I understand if merely presenting information isn't within the scope of the project.

**Comment by tanujnotes** [comment]
Hi, I don't think we'll be able to provide this level of customization. It's a minimal launcher after all. I hope you understand.
