### ISSUE TITLE
[Feature Request] Make hour and date position location not the same as apps

### ISSUE THREAD

**Issue by Minibus93** [tanujnotes/Olauncher#86]
Hi Tanuj, 
first of all, I'd like to thank you for the amazing application you provided to us! That's a really sweet launcher!

I thought that a nice thing to add is the possibility to be able to place clock and date at center (or any other side) while having apps to the left (or any other side).
This is a thing that would improve the customization while keeping it minimal :D It would be very nice, maybe consider this ^^

**Comment by tanujnotes** [comment]
No plan to add this for now.
