### ISSUE TITLE
Wallpapers from the Github Readme

### ISSUE THREAD

**Issue by breuerfelix** [tanujnotes/Olauncher#87]
Hey, awesome project!  
Is there a way to get the 4 Wallpaper you used to create the Screenshots for the Splash Image on the GitHub Readme?  
I really love those!

Cheers

**Comment by tanujnotes** [comment]
Hey, that image is actually thumbnail from a YouTube video. You can find the links in the video description. https://youtu.be/25CWsKI4aqU
