### ISSUE TITLE
Setting for vertical padding of the app list

### ISSUE THREAD

**Issue by Ka-hu** [tanujnotes/Olauncher#88]
The padding is a bit "tight" in the app list, and since we can have only 8 apps on the main screen, it would be nice to have a setting for vertical padding, giving the list items a little more room to breathe. We could select from some predefined values or manually set a number for the vertical padding.

Example:

![example image](https://i.imgur.com/t94wlyX.png)

**Comment by tanujnotes** [comment]
No plan to add this level of customisation.
