### ISSUE TITLE
Bug: Double tap to lock

### ISSUE THREAD

**Issue by lichingyun** [tanujnotes/Olauncher#89]
Hello Tanuj
the "Double tap to lock" in version 3.1 doesn't work for me, Olauncher crash and open the original launcher.
I have try both the version 3.1 from GitHub and from Playstore.
My phone is Xiaomi Redmi Note 5 with the latest rom Arrow Os android 11

The latest version 3.0 from Fdroid works well.
Thanks for your work Tanuj

**Comment by tanujnotes** [comment]
Hi, can you please try the latest release and let me know if the issue is fixed? Thank you.
https://github.com/tanujnotes/Olauncher/releases/tag/v3.2

**Comment by lichingyun** [comment]
Hello Tanuj,
version 3.2 works well, thanks

10 mag 2021 10:27:09 Tanuj M. ***@***.***>:

**Comment by tanujnotes** [comment]
Awesome!
