### ISSUE TITLE
Olauncher/Olauncher+ Suggestions & Feature Requests

### ISSUE THREAD

**Issue by CrimsonBloodfang** [tanujnotes/Olauncher#9]
1.) A "scroll up & down gesture with fade animation" to switch list of apps at the home screen. Maximum of 8 or 10 total apps, while maintaining the minimal look by just showing 4 or 5 apps in each list.

- I was thinking, if I needed fast and easy access for more apps at the home screen (like maximum of 8 apps) rather than always relying on the app drawer, while also maintaining the minimal look, 4 apps should be shown and 4 apps will be hidden or switchable with a fade animation by a scroll up and down gesture.

- The same with a maximum of 10 apps, 5 apps (shown), 5 apps (hidden).

- Half the total apps (shown or hidden), so that every hidden app will fit in the list and will be shown with just a flick of a finger, while not cluttering the home screen with texts.

- Should only be scrollable within the list of apps. Shouldn't overlap or conflict with the other scroll up and down gestures.

- Range of the gesture should also reach the rightmost part of the screen.

- When it reaches the end of the scroll up and down gestures and the gesture is repeated, it should default back to prioritizing the scroll up gesture for the app drawer and the scroll down gesture for showing the notification panel.

- Right and Left scroll gestures should still work anywhere on the home screen. The free or empty spaces above and below is for the scroll up and down gestures of the app drawer and showing the notification panel.

- The "fade animation" I mentioned is the same animation used when long pressing Olauncher home screen. I wanted scroll animations at first, but that fade animation looks better.

2.) The apps on the home screen should also be tapped or selected at the "rightmost part of the screen".

- So that we don't have to stretch our right thumbs to tap and reach the apps.

- If possible, include an animation like those default ripple touch animation or any snappy touch animation, with a disable option. Since we'll be tapping at an empty space of the right side. The disable option is for those who don't want touch animations.

- Also animate the touches on apps at the app drawer, if you ever decide to add touch animations.

3.) Custom fonts

- An option to add our own custom fonts by maybe adding .ttf files to Olauncher? Is that possible or gonna work?

- This will make Olauncher even more appealing and standout among others. I really wish this can be done, intuitive, minimal looking, beautiful fonts with a beautiful wallpaper is my ideal home launcher.

4.) An option to apply white border for Olauncher's black text color option and a black border for the white text color option. 

- So that texts are still readable with the same colored wallpapers.

5.) Sort the app drawer "search results" by Best Match, not by Name, Title or not by keywords found in random apps.

- Like searching for MALClient. Search keyword used is "_ma_". 

Search results are: 

Automate
File Manager
Gmail
MALClient

- Should only show MALClient.

- Shouldn't show random apps, with names or titles that doesn't begin with the keyword used.

6.) Skip "symbols" when searching for an app in the app drawer.

- Like searching just "fdroid", skipping "-" symbol, would bring up "F-Droid" in the search result. 

- Having to switch the keyboard layout to symbols is a delay.

7.) Better compatibility in adding extra shortcuts from their main apps.

- Like adding "Private Browsing" shortcut from Firefox Beta. Olauncher doesn't add or support it. 

- Maybe because its destination is the home screen? Can you trick apps to treat the app drawer as a home screen for these type of functions or shortcuts?

8.) Be able to convert those one tap widgets as texts for Olauncher???

- Would be fine if it isn't a feature, but just instructions in GitHub on how to add or convert those widgets that functions only with taps. Like "Greenify's Hibernate Widget" or a "Flashlight Widget", etc.

9.) Custom apps or functionality for scroll down, right & left gestures, with the exception of scroll up.

- Like scroll down to "Show Notification Panel + Clear Notifications".

- Scroll right or left to open selected apps.

10.) Place the search bar and search results on the app drawer a bit higher.

- With the keyboard (OpenBoard) always covering the search results, I can only tap and see 2 ½ apps on my screen.

11.) Improve scrolling on the app drawer while keyboard is shown.

- It always bounces up and down, then keyboard disappears and app drawer covers or skips the first four apps when I scroll it.

- I flick scroll it and sometimes it goes back to the home screen. Scrolling isn't smooth on the app drawer when keyboard is shown. 

12.) Selecting wallpaper

- Other users have requested this, but switching wallpapers is very glitchy of a task for me. 

- I change Olauncher wallpapers by setting the wallpaper first on other Launchers or by choosing "Set as wallpaper" in Simple Gallery app, then switch back to use Olauncher. 

Results are: 
- Wallpaper doesn't change.
- Only navigation bar is showing the new wallpaper.
- It crashed.

Fixed it by:
- Temporarily hibernating Olauncher using Greenify. Now it shows the new wallpaper. (Not sure if a reboot fixes it, will not attempt anymore)

I intended to "Force close" Olauncher, but I didn't know at the time that it was protected as a Device Administrator (for double tap to lock option), so I couldn't tap force close. I also couldn't clear data, which is fine.

13.) Include default images or wallpapers shown in the sample pics at GitHub and Playstore.

- They really look good, any links? Where can I download them in high quality? 

- New users might be installing the app for the sake of trying those wallpapers and designs, in the sample pics.

14.) Almost forgot this, please add support for landscape mode. 

Other problems or minor things I've encountered are:

- It crashes at version 0.4, I think it's because I was on landscape mode. (I will report back with logcat if it still crashes)

- On version 0.4, it sometimes glitches and hides some apps in the app drawer. Maybe because I cleared cache or because of the crashes. (Again, I will test and see if this still occurs in version 0.5)

- With no icons, apps or split apps with the same names are difficult to identify at first.

- Google Playstore, GitHub Releases and F-Droid still didn't show version 0.5. Fortunately, I downloaded Aurora Store and updated Olauncher there.

- Couldn't install it without deactivating it on Device Administrators, because I enabled "double tap to lock" option. I thought it was incompatible at first. GitHub description for Olauncher should have FAQ for this. 

Olauncher version 0.5
Device: Huawei Nova Lite
Android version: 7.1.2
Resurrection Remix Custom Rom

This launcher app is really nice. My first minimal launcher. Thanks for creating this. I hope it's okay to pile up these suggestions or requests of mine here. Kinda new to GitHub, since I usually email.

**Comment by teemue** [comment]
I second suggestions number 2 and 5. Plus function to rename apps on the home screen would be superb.

**Comment by tanujnotes** [comment]
Thank you for such detailed comment. Lots of really good suggestions. I'm already familiar with roughly half of the issues mentioned here. Updates will come slow as I'm busy with other stuff but I'll do whatever I can. Stay tuned.
Regarding the app drawer scrolling problem, there's one issue where it closes unexpectedly otherwise it works really well on all the phones and emulators I have tested on. I'm wondering if it's a device specific issue. If it's possible, please test it one other phones and update me. Thank you.

**Comment by tanujnotes** [comment]
@teemue Both points are doable and I'll try to make them available in the next update.

**Comment by tanujnotes** [comment]
I made a lot of changes in the latest update (v1.0) based on suggestions on this thread. Please give it a try.

I'm closing this issue. If you have any suggestion/feature request/bug report, please create a new issue. And please create a separate issue for every point you have. It's easier to keep track that way. Thank you.
