### ISSUE TITLE
[Feature request] Diacritics to not play a role in search

### ISSUE THREAD

**Issue by ANDREW007CZ** [tanujnotes/Olauncher#92]
Hi,
for languages that use symbols such as "ěščřžýáíé" I'd love to see a functionality where
ě=e
š=s
..where letter with diacritics means the same as one without it in regards of search.
Typical use:

I want to search and run app call ČHMÚ (a czech weather app). Now I need to write "Č" for app to show. Would be great and simple if app with "Č" in name would also appear when I write "C".

Oreo 8.0
app version 3.3
czech language as default

**Comment by jlemonde** [comment]
I would need that too!

**Comment by tanujnotes** [comment]
Can you update to the latest version and check?

**Comment by ANDREW007CZ** [comment]
It is working! Thank you very much, Tanuj!
