### ISSUE TITLE
[feature request] Clock and date separation + alarm

### ISSUE THREAD

**Issue by ANDREW007CZ** [tanujnotes/Olauncher#93]
Would be great if clock could be for example on left side of the screen whereas date on the right side. Thus taping on them would be easier not so tap-precision based. Also reading them could be easier that way.
Also I'm missing seeing the next alarm set.

**Comment by tanujnotes** [comment]
Hi, no plan to make such changes for now.

**Comment by ANDREW007CZ** [comment]
Well, yeah, I thought so, that's why I suggested it. :D Thanks for reply.
