### ISSUE TITLE
[Feature Request] usage stats

### ISSUE THREAD

**Issue by Radd-max** [tanujnotes/Olauncher#95]
could you add a small box next to the app name showing the amount of time spent in that app. 
something like this 
![box](https://user-images.githubusercontent.com/62344221/121222934-82bc3280-c876-11eb-812c-e702d88cf560.jpeg)

**Comment by tanujnotes** [comment]
This is beyond the scope of this minimal launcher. Please use Digital Wellbeing app. It's already available by default in most Android devices today. Thank you for using Olauncher.
