### ISSUE TITLE
In Japanese, strings could be replaced by the Input Method after typing

### ISSUE THREAD

**Issue by m-hayabusa** [tanujnotes/Olauncher#96]
It would be nice to be able to choose just whether to open the app if there is only one result.
Because the string in the text field while typing could be not the character I want to type.
 
In Japanese input, the characters already entered to text field may change later.
If I want to input "隼", typing "hayabusa" will input "はやぶさ", and choose "隼" from the list provided by keyboard, then "はやぶさ" is *replaced* by "隼".
This is the same as auto-correct with other languages.

or, could use [this flag](https://developer.android.com/reference/android/text/Spanned.html#SPAN_COMPOSING) or like that?

**Comment by m-hayabusa** [comment]
あいみょん: https://play.google.com/store/apps/details?id=net.aimyong.sp 
アイシティ: https://play.google.com/store/apps/details?id=jp.co.eyecitypocket 
and Input Method: https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

typing "ai" in GBoard's Japanese(QWERTY) to input "あい", and then tap "アイ" to input it.

**Comment by tanujnotes** [comment]
Can you please update to the latest version and confirm if this issue is resolved or not?

**Comment by m-hayabusa** [comment]
It seems not resolved yet on v3.4.1.

**Comment by addlistener** [comment]
I'm experiencing the same issue. Suffering from the auto open app feature.

Eg I want "隼"

1. Typing "hayabusa"
2. I have only 1 app starting with "h"
3. Then the app staring with "h" is auto opened, not "隼"

A switch to disable the auto open feature would be nice

**Comment by tanujnotes** [comment]
@addlistener You can press SPACEBAR and then type to search to temporarily disable the auto-launch feature.
Would you be able to upload a video of this issue?
